### ISSUE TITLE
libsolv seems to ignore the location base set in the primary xml

### ISSUE THREAD

**Issue by yavor-atanasov** [openSUSE/libsolv#101]
Hey guys,

We encountered a problem using `dnf` with one of our repositories. The packages metadata in our primary.xml specifies a location base, like so:
```
<location href="minimal-1.2.3-9.noarch.rpm" base="https://some-service/packages"/>
```
Here is the full package snippet for context:
```
<?xml version="1.0" encoding="UTF-8"?>
<metadata xmlns="http://linux.duke.edu/metadata/common" xmlns:rpm="http://linux.duke.edu/metadata/rpm" packages="1">
<package type="rpm">
  <name>minimal</name>
  <arch>noarch</arch>
  <version epoch="0" ver="1.2.3" rel="9"/>
  <checksum pkgId="YES" type="sha256" rel="9">c49dd53ba485b77753edf80adc04e79a9db29f94a1d89032f5e90efdd50d4be7</checksum>
  <summary>Minimal package</summary>
  <description>Minimal RPM</description>
  <packager/>
  <url/>
  <time build="1411659282" file="1411659282"/>
  <size package="1400" archive="124" installed="0"/>
  <location href="minimal-1.2.3-9.noarch.rpm" base="https://some-service/packages"/>
  <format>
    <rpm:license>Public Domain</rpm:license>
    <rpm:vendor/>
    <rpm:group>Applications/System</rpm:group>
    <rpm:buildhost>buildhost</rpm:buildhost>
    <rpm:sourcerpm>minimal-1.2.3-9.src.rpm</rpm:sourcerpm>
    <rpm:header-range start="280" end="1284"/>
    <rpm:provides>
      <rpm:entry flags="EQ" epoch="0" ver="1.2.3" name="minimal" rel="9"/>
    </rpm:provides>
    <rpm:requires>
      <rpm:entry ver="3.0.4" epoch="0" flags="LE" name="rpmlib(CompressedFileNames)" rel="1"/>
      <rpm:entry ver="4.6.0" epoch="0" flags="LE" name="rpmlib(FileDigests)" rel="1"/>
      <rpm:entry ver="4.0" epoch="0" flags="LE" name="rpmlib(PayloadFilesHavePrefix)" rel="1"/>
      <rpm:entry ver="5.2" epoch="0" flags="LE" name="rpmlib(PayloadIsXz)" rel="1"/>
    </rpm:requires>
  </format>
</package>

</metadata>
```

By the looks of it `dnf` does not use that `base` attribute and is trying to locate the package using the `href` and the repository url specified in the config. As far as I can see this might be an issue with `libsolv`. This is where it parses the location tag and extracts the `href` attribute and then it looks for a `xml:base` attribute as opposed to just `base` - https://github.com/openSUSE/libsolv/blob/6806d31042c836b34cbfbea225b7268f3c479f71/ext/repo_rpmmd.c#L780
Can you confirm that's a bug? Happy to create a pull request if it is.

Thank you
Yavor

**Comment by mlschroe** [comment]
I'm afraid i don't know the answer to that. createrepo puts "xml:base" in the repodata and not "base". The "xml:" part normally describes a namespace, but the metadata does not contain a definition for such a namespace.

The C code of Fedora's yum-metadata-parser also only looks for "xml:base". So which tool did you use so that the metadata contains yust "base"?

**Comment by yavor-atanasov** [comment]
Thank you @mlschroe,

I just confirmed what you said. That is a bug on our end. We have a repository service that offers a REST API for people to create versioned repositories and manage rpms within those. It extracts the metadata of each uploaded rpm, stores it and generates the repo metadata on the fly as required. Up until recently it was just serving sqlite metadata as that is faster with YUM. We've now extended it so it serves the XML metadata as well (to be forward compatible with DNF) and as these things are poorly documented we've missed that (even though we did use `createrepo` to check the metadata, we missed running it with `--baseurl` to see that there is difference in the way that attribute is specified)

Anyway, easily fixed. Thank you again for the quick reply.

Yavor

**Comment by yavor-atanasov** [comment]
After we fixed that at our end, we stumbled on a bug with DNF that you might be interested in:
https://bugzilla.redhat.com/show_bug.cgi?id=1257965

Seems like when you set the `xml:base` DNF treats the resulting url as a local file path and errors with `OSError: [Errno 2] No such file or directory`

This seems purely a DNF issue.
