### ISSUE TITLE
mechanism to prefer some repo in distroupgrade

### ISSUE THREAD

**Issue by jsilhan** [openSUSE/libsolv#103]
Hi,
we're dealing with [system-upgrades](https://bugzilla.redhat.com/show_bug.cgi?id=1263677) and we would like to prefer fedora repo and in case of package conflicts rather remove the third party package.

Could I by changing repository priority / subpriority and using `SOLVER_DISTUPGRADE|SOLVER_SOLVABLE_ALL` achieve that?
I understand priorities like when one package of some name is about to be installed then it will choose the one with higher priority. This is a bit different case, we want packages from fedora to stay installed rather than conflicting packages of *different names* from other repo.

The other solution that I thought about is to iterate over all installed packages and for the names that are in fedora repo, do `SOLVER_SOLVABLE|SOLVER_DISTUPGRADE` otherwise `SOLVER_SOLVABLE|SOLVER_DISTUPGRADE|SOLVER_WEAK`

Or is there any other libsolv mechanism that I am missing?

**Comment by mlschroe** [comment]
libsolv has a mechanism for dropping conflicting packages with SOLVER_DISTUPGRADE|SOLVER_SOLVABLE_ALL, but it relies on the 3rd party repos not being enabled, i.e. the 3rd party packages must be "orphaned".

It seems that you want some method to tell the solver "you're free to drop those installed packages if they get in the way", i.e. like allowuninstall (aka allowerasing) but just for a specific set of packages.

**Comment by kparal** [comment]
From a high-level perspective, I think we would like to cover three basic cases during N -> N+1 system upgrades:

1. third-party repos exist for N+1 and contain package updates with non-problematic dependencies: In this case we want to upgrade those packages together with the rest of the system.

2. third-party repos don't exist for N+1 and the current packages have problematic dependencies, meaning they prevent current packages from upgrading. Alternatively the N+1 repos do exist, but the package updates still have problematic dependencies: In this case we want to prioritize packages from our official repositories at the expense of third-party repositories (removing their packages if needed).

3. third-party repos don't exist for N+1 (or the packages were not installed from any repository at all), but they don't cause any problematic dependencies while the rest of the system upgrades to N+1. In that case we want to keep those packages installed and don't remove them.

I'm not sure how much of it is related to libsolv and what is a higher-level problem, so please forgive me if I'm completely off-topic here.

**Comment by jsilhan** [comment]
> libsolv has a mechanism for dropping conflicting packages with SOLVER_DISTUPGRADE|SOLVER_SOLVABLE_ALL, but it relies on the 3rd party repos not being enabled, i.e. the 3rd party packages must be "orphaned".

We would like to keep them if possible.

> It seems that you want some method to tell the solver "you're free to drop those installed packages if they get in the way", i.e. like allowuninstall (aka allowerasing) but just for a specific set of packages.

Yes, that would resolve 1), 2), 3) specifications. The new Repo int attribute or Pool map attribute would be sufficient. Thanks.

**Comment by mlschroe** [comment]
I added the  SOLVER_ALLOWUNINSTALL job type, please check if it meets your requirements.

**Comment by jsilhan** [comment]
I am struggling with understanding the semantic of `SOLVER_ALLOWUNINSTALL`.

If `pkg D` is not in allowed to be uninstalled then it will fail. Fine.
```
repo system 0 testtags <inline>
#>=Pkg: A 1 1 x86_64
#>=Pkg: B 1 1 x86_64
#>=Pkg: C 1 1 x86_64
#>=Pkg: D 1 1 x86_64
repo fedora 0 testtags <inline>
#>=Pkg: A 1 2 x86_64
#>=Pkg: B 1 2 x86_64
#>=Con: D
system x86_64 rpm system
solverflags keeporphans
job allowuninstall pkg A-1-1
job allowuninstall pkg C-1-1
job allowuninstall pkg D-1-1
job distupgrade all packages
result transaction,problems <inline>
#>erase D-1-1.x86_64@system
#>problem bbe6eb7e info package B-1-2.x86_64 conflicts with D provided by D-1-1.x86_64
#>problem bbe6eb7e solution 20a5cb70 erase D-1-1.x86_64@system
#>problem bbe6eb7e solution 81759705 allow B-1-1.x86_64@system
```

I allow him to be erased. Works as expected.
repo system 0 testtags <inline>
#>=Pkg: A 1 1 x86_64
#>=Pkg: B 1 1 x86_64
#>=Pkg: C 1 1 x86_64
#>=Pkg: D 1 1 x86_64
repo fedora 0 testtags <inline>
#>=Pkg: A 1 2 x86_64
#>=Pkg: B 1 2 x86_64
#>=Con: D
system x86_64 rpm system
solverflags keeporphans
job allowuninstall pkg D-1-1
job distupgrade all packages
result transaction,problems <inline>
#>erase D-1-1.x86_64@system
#>upgrade A-1-1.x86_64@system A-1-2.x86_64@fedora
#>upgrade B-1-1.x86_64@system B-1-2.x86_64@fedora

But when I add `pkg B` to allow_uninstall set, the B will not get upgraded anymore. I expect it to work like in the previous example.
epo system 0 testtags <inline>
#>=Pkg: A 1 1 x86_64
#>=Pkg: B 1 1 x86_64
#>=Pkg: C 1 1 x86_64
#>=Pkg: D 1 1 x86_64
repo fedora 0 testtags <inline>
#>=Pkg: A 1 2 x86_64
#>=Pkg: B 1 2 x86_64
#>=Con: D
system x86_64 rpm system
solverflags keeporphans
job allowuninstall pkg B-1-1
job allowuninstall pkg D-1-1
job distupgrade all packages
result transaction,problems <inline>
#>upgrade A-1-1.x86_64@system A-1-2.x86_64@fedora
```

From docs: `Allow the solver to deinstall the matching installed packages if they get into the way of resolving a dependency. This is like the SOLVER_FLAG_ALLOW_UNINSTALL flag, but limited to a specific set of packages.`
why at some point it `SOLVER_FLAG_ALLOW_UNINSTALL` flag protects packages rather than letting them to be erased?

**Comment by mlschroe** [comment]
I think this is already fixed with the latest commits. (Especially 80ddee19786b7b96d28cde1b972721dc631ee055)

**Comment by jsilhan** [comment]
Confirming that it works now, thanks.
