### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [openSUSE/libsolv#104]
I would like to point out that identifiers like "[`_Chksum`](https://github.com/openSUSE/libsolv/blob/8b0605afac1bfe8e1e67af2936f4f6a315c539c3/src/chksum.h#L17)" and "[`_Transaction`](https://github.com/openSUSE/libsolv/blob/09da37be742a1cec7002339f94b71dd9c8918e1a/src/transaction.h#L28)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by mlschroe** [comment]
Those are pretty much internal to libsolv, as library users should use the typedef instead. So I wouldn't mind changing the code to s_Chksum or something like that.

**Comment by mlschroe** [comment]
Fixed with commit 94c4c4e97974ed2cd63e7a7bcf31d876f19eca80

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/openSUSE/libsolv/commit/94c4c4e97974ed2cd63e7a7bcf31d876f19eca80 "Fix reserved identifier violation").
