### ISSUE TITLE
Multiversion packagers treated by evr substring

### ISSUE THREAD

**Issue by jsilhan** [openSUSE/libsolv#110]
Hi,
Is possible to distinguish multiversion packages from evr in libsolv? Eg. Say we have java-1.8.0-openjdk and java-1.7.0-openjdk. These packages should be upgraded to the newest release of 1.7 and 1.8. So far the packages have the version in their name (java-1.8.0-openjdk-1.8.0.R.A) while packagers and users expect them to be named just java-openjdk. Ruby packages have similar issue. 

We will have a meeting with java and ruby packagers and rpm guys to resolve this problem. We don't know yet how we should deal with them. I wanna do a research beforehand if it is possible in libsolv to deal with such cases when another rpm tag would be made. Have you tried to solve specific language packaging with different versioning, that doesn't fit to rpm package management, in SUSE too?

**Comment by mlschroe** [comment]
(back from parental leave)

From libsolv's point of view, multiversion packages can be marked with standard job elements, i.e. by provide, by name, or by id. If you have some weird heuristic that decides which package is supposed to be multiversion, you can run that over all packages and just feed to package ids into the libsolv job list.

(BUT: I'd rather you stay away from mis-using multiversion packages, it's much cleaner to just put the distinguishing component into the package name.)

**Comment by jsilhan** [comment]
Ok, thanks for response. I didn't like that idea either.
