### ISSUE TITLE
Conflicts between glib2-2.46.1-2.fc23.i686 and glib2-2.46.0-1.fc23.x86_64

### ISSUE THREAD

**Issue by csoriano89** [openSUSE/libsolv#114]
Trying to update on f23 gives the following full output, asked on fedora channel and told me is a libsolv bug:

The downloaded packages were saved in cache till the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction check error:
  file /usr/share/doc/glib2/README from install of glib2-2.46.1-2.fc23.i686 conflicts with file from package glib2-2.46.0-1.fc23.x86_64
  file /usr/share/doc/glib2/NEWS from install of glib2-2.46.1-2.fc23.i686 conflicts with file from package glib2-2.46.0-1.fc23.x86_64
  file /usr/share/locale/cs/LC_MESSAGES/glib20.mo from install of glib2-2.46.1-2.fc23.i686 conflicts with file from package glib2-2.46.0-1.fc23.x86_64
  file /usr/share/locale/eu/LC_MESSAGES/glib20.mo from install of glib2-2.46.1-2.fc23.i686 conflicts with file from package glib2-2.46.0-1.fc23.x86_64
  file /usr/share/locale/sr/LC_MESSAGES/glib20.mo from install of glib2-2.46.1-2.fc23.i686 conflicts with file from package glib2-2.46.0-1.fc23.x86_64
  file /usr/share/locale/sr@latin/LC_MESSAGES/glib20.mo from install of glib2-2.46.1-2.fc23.i686 conflicts with file from package glib2-2.46.0-1.fc23.x86_64
  file /usr/share/locale/vi/LC_MESSAGES/glib20.mo from install of glib2-2.46.1-2.fc23.i686 conflicts with file from package glib2-2.46.0-1.fc23.x86_64
  file /usr/share/man/man1/gapplication.1.gz from install of glib2-2.46.1-2.fc23.i686 conflicts with file from package glib2-2.46.0-1.fc23.x86_64
  file /usr/share/man/man1/gdbus.1.gz from install of glib2-2.46.1-2.fc23.i686 conflicts with file from package glib2-2.46.0-1.fc23.x86_64
  file /usr/share/man/man1/gio-querymodules.1.gz from install of glib2-2.46.1-2.fc23.i686 conflicts with file from package glib2-2.46.0-1.fc23.x86_64
  file /usr/share/man/man1/glib-compile-schemas.1.gz from install of glib2-2.46.1-2.fc23.i686 conflicts with file from package glib2-2.46.0-1.fc23.x86_64
  file /usr/share/man/man1/gsettings.1.gz from install of glib2-2.46.1-2.fc23.i686 conflicts with file from package glib2-2.46.0-1.fc23.x86_64
  file /usr/share/man/man5/cert8.db.5.gz from install of nss-3.20.1-1.0.fc23.i686 conflicts with file from package nss-3.20.0-1.0.fc23.x86_64
  file /usr/share/man/man5/cert9.db.5.gz from install of nss-3.20.1-1.0.fc23.i686 conflicts with file from package nss-3.20.0-1.0.fc23.x86_64
  file /usr/share/man/man5/key3.db.5.gz from install of nss-3.20.1-1.0.fc23.i686 conflicts with file from package nss-3.20.0-1.0.fc23.x86_64
  file /usr/share/man/man5/key4.db.5.gz from install of nss-3.20.1-1.0.fc23.i686 conflicts with file from package nss-3.20.0-1.0.fc23.x86_64
  file /usr/share/man/man5/pkcs11.txt.5.gz from install of nss-3.20.1-1.0.fc23.i686 conflicts with file from package nss-3.20.0-1.0.fc23.x86_64
  file /usr/share/man/man5/secmod.db.5.gz from install of nss-3.20.1-1.0.fc23.i686 conflicts with file from package nss-3.20.0-1.0.fc23.x86_64
  file /usr/share/doc/harfbuzz/NEWS from install of harfbuzz-1.0.6-1.fc23.i686 conflicts with file from package harfbuzz-1.0.4-1.fc23.x86_64
  file /usr/share/doc/pango/NEWS from install of pango-1.38.1-1.fc23.i686 conflicts with file from package pango-1.38.0-1.fc23.x86_64
  file /usr/share/man/man1/pango-view.1.gz from install of pango-1.38.1-1.fc23.i686 conflicts with file from package pango-1.38.0-1.fc23.x86_64
  file /usr/share/doc/gnutls/NEWS from install of gnutls-3.4.6-1.fc23.i686 conflicts with file from package gnutls-3.4.5-1.fc23.x86_64
  file /usr/share/locale/cs/LC_MESSAGES/gnutls.mo from install of gnutls-3.4.6-1.fc23.i686 conflicts with file from package gnutls-3.4.5-1.fc23.x86_64
  file /usr/share/locale/de/LC_MESSAGES/gnutls.mo from install of gnutls-3.4.6-1.fc23.i686 conflicts with file from package gnutls-3.4.5-1.fc23.x86_64
  file /usr/share/locale/en@boldquot/LC_MESSAGES/gnutls.mo from install of gnutls-3.4.6-1.fc23.i686 conflicts with file from package gnutls-3.4.5-1.fc23.x86_64
  file /usr/share/locale/en@quot/LC_MESSAGES/gnutls.mo from install of gnutls-3.4.6-1.fc23.i686 conflicts with file from package gnutls-3.4.5-1.fc23.x86_64
  file /usr/share/locale/eo/LC_MESSAGES/gnutls.mo from install of gnutls-3.4.6-1.fc23.i686 conflicts with file from package gnutls-3.4.5-1.fc23.x86_64
  file /usr/share/locale/fi/LC_MESSAGES/gnutls.mo from install of gnutls-3.4.6-1.fc23.i686 conflicts with file from package gnutls-3.4.5-1.fc23.x86_64
  file /usr/share/locale/fr/LC_MESSAGES/gnutls.mo from install of gnutls-3.4.6-1.fc23.i686 conflicts with file from package gnutls-3.4.5-1.fc23.x86_64
  file /usr/share/locale/it/LC_MESSAGES/gnutls.mo from install of gnutls-3.4.6-1.fc23.i686 conflicts with file from package gnutls-3.4.5-1.fc23.x86_64
  file /usr/share/locale/ms/LC_MESSAGES/gnutls.mo from install of gnutls-3.4.6-1.fc23.i686 conflicts with file from package gnutls-3.4.5-1.fc23.x86_64
  file /usr/share/locale/nl/LC_MESSAGES/gnutls.mo from install of gnutls-3.4.6-1.fc23.i686 conflicts with file from package gnutls-3.4.5-1.fc23.x86_64
  file /usr/share/locale/pl/LC_MESSAGES/gnutls.mo from install of gnutls-3.4.6-1.fc23.i686 conflicts with file from package gnutls-3.4.5-1.fc23.x86_64
  file /usr/share/locale/sv/LC_MESSAGES/gnutls.mo from install of gnutls-3.4.6-1.fc23.i686 conflicts with file from package gnutls-3.4.5-1.fc23.x86_64
  file /usr/share/locale/uk/LC_MESSAGES/gnutls.mo from install of gnutls-3.4.6-1.fc23.i686 conflicts with file from package gnutls-3.4.5-1.fc23.x86_64
  file /usr/share/locale/vi/LC_MESSAGES/gnutls.mo from install of gnutls-3.4.6-1.fc23.i686 conflicts with file from package gnutls-3.4.5-1.fc23.x86_64
  file /usr/share/locale/zh_CN/LC_MESSAGES/gnutls.mo from install of gnutls-3.4.6-1.fc23.i686 conflicts with file from package gnutls-3.4.5-1.fc23.x86_64
  file /usr/share/doc/libwebp/AUTHORS from install of libwebp-0.4.4-1.fc23.i686 conflicts with file from package libwebp-0.4.3-3.fc23.x86_64
  file /usr/share/doc/libwebp/README from install of libwebp-0.4.4-1.fc23.i686 conflicts with file from package libwebp-0.4.3-3.fc23.x86_64
  file /usr/share/doc/libwebp/NEWS from install of libwebp-0.4.4-1.fc23.i686 conflicts with file from package libwebp-0.4.3-3.fc23.x86_64
  file /usr/share/doc/libwebp/PATENTS from install of libwebp-0.4.4-1.fc23.i686 conflicts with file from package libwebp-0.4.3-3.fc23.x86_64

Error Summary
-------------

**Comment by mlschroe** [comment]
Why would that be a libsolv bug? It's the rpm library that reports the conflicts.
