### ISSUE TITLE
transaction_order incorrectly adds obsolete elements at the end of transaction->steps.elements

### ISSUE THREAD

**Issue by adelcast** [openSUSE/libsolv#120]
My configuration does not have SOLVER_TRANSACTION_SHOW_OBSOLETES on, which maps obsolete packages as erase/install operations. In the case of a repo with A & B:

Package A 
   Installed
Package B (Replaces A, Provides A, Conflicts A)

When B is installed, the transaction->steps.elements array has:
[0] Install B
[1] Remove A

after calling transaction_order(trans, 0). From inspecting the code, I can see that transaction_order adds the obsolete elements (in this case, A) at the very end, when calling transaction_add_obsoleted.

In this case, sounds like the the desired output is to add the obsolete packages at the beginning of the array (so they are removed first), not the end since B might have files also installed by A.

**Comment by mlschroe** [comment]
IIRC this can be closed.
