### ISSUE TITLE
Install supplements ASAP

### ISSUE THREAD

**Issue by luizluca** [openSUSE/libsolv#125]
Hello,

I faced a problem with the order packages are installed in OpenSUSE.
https://bugzilla.opensuse.org/show_bug.cgi?id=969961

When any pam-xyz module (hypothetical name) is installed and pam-32bit is also installed, the pam-xyz-32bit module must be installed or pam-config will fatally fail. This is solved in OpenSUSE using:

Supplement: packageand(pam_xyz:pam-32bit)

This is not ideal because the need is for a "conditional strong reverse dependency". Anyway, it normally works as recommended packages are installed by default.

As nothing requires the pam-xyz-32bit (it only supplements its 64bit variant), it could be installed at any order after pam-xyz is installed. libsolv sometimes decides to install it just after the pam-xyz and everything work as expected. The problem is that sometimes libsolv decides to install pam-xyz-32bit later or even at end of the transaction. If any package requires pam-xyz and uses pam-config in a %post, it will fail when pam-xyz-32bit is still not avaiable.

Would it be possible to hint libsolv to install Supplement packages ASAP (like after its dependencies and the package it supplements are installed)?

**Comment by mlschroe** [comment]
Why should it install supplemented packages that no other package depends on?

There are two problems here:
1) supplements are weak. By definition it's always ok to not install them. If this results in some error like in your case, using supplements was a mistake. (I.e. the correct dependency would not be a supplements, but a hard requires. But to do this, you need dependencies with and/or/if, like rpm upstream is currently implementing.

2) if both pam-xyz and pam-xyz would provide some common dependency, like pam(xyz), your package could have a "Requires: pam(xyz)", and libsolv would try to install both providers before installing your package. (At least I think so ;) ). So this might be the correct solution for now. I don't think there's a sane way to fix this in libsolv.
