### ISSUE TITLE
Use cmake's GNUInstallDirs

### ISSUE THREAD

**Issue by rossburton** [openSUSE/libsolv#128]
Instead of hand-coding your own "what paths to install to" logic, and in our environment breaking mandir, please consider using GNUInstallDirs so it behaves as per the GNU coding standards and existing autoconf behaviour.

**Comment by mlschroe** [comment]
But GNUInstallDirs  doesn't exist for older cmake versions...

**Comment by ignatenkobrain** [comment]
@mlschroe it has been added in [https://cmake.org/cmake/help/v2.8.5/cmake.html#module:GNUInstallDirs](2.8.5) (July 2011). Even Ubuntu 12.04 has 2.8.7 in repos. so just use `GNUInstallDirs` and bump `cmake_required_version (VERSION 2.8.5)`

**Comment by mlschroe** [comment]
So? SLE-11 doesn't have it so I can't require it.

**Comment by Conan-Kudo** [comment]
@mlschroe That's not true. I'm building software for SUSE Linux Enterprise 11 SP4 using `cmake-2.8.12.1-1.35` from the official target on build.opensuse.org. You can totally use it.
