### ISSUE TITLE
expose testcase_read() via bindings

### ISSUE THREAD

**Issue by lnussel** [openSUSE/libsolv#129]
Would it make sense to expose testcase_read() via bindings so scripts don't have to parse the output of a program?
e.g.
https://github.com/openSUSE/package-lists/blob/master/gen.pl#L50

**Comment by mlschroe** [comment]
Dunno, it doesn't make much sense for the package-lists app. If you switch over to the bindings it is easier to create the solver job yourself.

**Comment by mlschroe** [comment]
closing for now.
