### ISSUE TITLE
Using libsolv to determine which package provides a file

### ISSUE THREAD

**Issue by jessp01** [openSUSE/libsolv#142]
Hello,

Firstly, let me state I am rather new to this project. I have gone through some of the documentation and did some Google searches but I may have missed an obvious example somewhere, if so, I do apologise.

Here is what I am looking for:
I need a method that accepts a file path, say "ssl.h" for example, and returns all packages [interested in deb and RPM for now, depending on the distro in question] that provide this file.

Right now, I am doing this using yum whatprovides "*/ssl.h" and apt-file search ssl.h accordingly.

The reasons why I'd rather try to use libsolv are: 
- yum whatprovides is quite slow and the output returned requires elaborate parsing [I know dnf uses libsolv and from a few tests, it seems to also return much faster but dnf is not installed by default on RHEL/CentOS 7 and is not running correctly even when installed on RHEL/CentOS 6]
- I'd like to have a unified method for doing this, regardless of the repo type I'm working against

Ideally, I'd like to be able to also pass along the arch I am interested in.

This will need to run from a shell script so I figure I may have to use libsolv and produce my own binary to use from the shell.
Would appreciate any help/code samples.

Thanks in advance,

**Comment by mlschroe** [comment]
Hmm, libsolv itself doesn't do repository management and repodata downloading, so maybe it's not the right tool for this. It also currently doesn't parse the debian Contents information, so it can't look up files from repositories.

**Comment by jessp01** [comment]
Hi @mlschroe,

Understood and thank you for your answer. Do you have plans to do so in your roadmap?

**Comment by Conan-Kudo** [comment]
@jessp01 At least for RPMs, you might want to look at [libdnf](https://github.com/rpm-software-management/libhif), which provides the interfaces you're looking for. Alternatively, the older [hawkey](https://github.com/rpm-software-management/hawkey) library may work for your purposes.
