### ISSUE TITLE
Ignore Obsoletes from system repo

### ISSUE THREAD

**Issue by ignatenkobrain** [openSUSE/libsolv#154]
```
repo system 0 testtags <inline>
#>=Pkg: python 2.7 1 x86_64
#>=Obs: python2
repo available 0 testtags <inline>
#>=Pkg: python2 2.7 2 x86_64
#>=Obs: python < 2.7-2
system x86_64 rpm system
poolflags implicitobsoleteusescolors
solverflags allowvendorchange keepexplicitobsoletes bestobeypolicy keeporphans yumobsoletes
job update all packages
result transaction
```

Looks like in F1X era someone added unversioned obsoletes. Now we are trying to rename `python` -> `python2`, but people already have this obsoletes in their system packages. We can't enforce them to upgrade to latest version before updating to next release.

**Comment by mlschroe** [comment]
Hmm. distro-sync should solve this.

**Comment by ignatenkobrain** [comment]
@mlschroe distro-sync probably should, but it should be working with normal updates as well.

**Comment by mlschroe** [comment]
It would lead to package ping pong if I ignore the obsoletes and there's some cycle. I.e., if repo available contains both foo and bar that obsolete each other and foo is installed, the next update would install bar, the update after that foo and so on...

**Comment by ignatenkobrain** [comment]
@mlschroe it's not problem of llibsolv. If there is such foo/bar, then now it will report broken updates because installed package obsoletes package from repo.

**Comment by mlschroe** [comment]
libsolv will not report broken updates. In your example libsolv simply does not know which if the packages is newer. It switches to python2 with no problems if you add a "job install name python2" job or if some other package requires python2.

**Comment by mlschroe** [comment]
The solver sees python and python2 as alternatives, as you can see if you add "alternatives" to the result line.

**Comment by ignatenkobrain** [comment]
@mlschroe question was about upgrading all packages. If you don't have Obs on `@system` package, then update will update package. If you have Obs on `@system` package then update will ignore update (older package obsoletes newer).

I don't see any other solution except ignoring `@system` obsoletes. Or at least to give it somehow lower priority.

**Comment by mlschroe** [comment]
Nope, ignoring them (or lower prio) won't work because of the ping-pong effect it would have.

**Comment by ignatenkobrain** [comment]
I still don't see how. Once you will get update from `available` you will not have package with Obs anymore.

**Comment by mlschroe** [comment]
That's true for your example. But in general the "python" can come from another configured repo.
