### ISSUE TITLE
 Useless error message for mixed arch dependency chain

### ISSUE THREAD

**Issue by ignatenkobrain** [openSUSE/libsolv#156]
From https://bugzilla.redhat.com/show_bug.cgi?id=1375477:

Description of problem:
When solving dependency chain of packages with different architectures (e.g. x86_64 and noarch) error message does not explain the root cause of failure.
When all packages are of the same arch, solver reports missing package as a root cause of failure. In mixed arch chain solver reports useless 'none of the providers can be installed' for an intermediate lib.

Version-Release number of selected component (if applicable):
libsolv-0.6.23-4.fc24.x86_64

How reproducible:
always

Steps to Reproduce:
1. cat >dep-chain-samearch.t <<EOF
repo system 0 empty
repo test 0 testtags <inline>
#>=Pkg: gimp 2:2.8.18 1.fc24 x86_64
#>=Req: libgs.so.9()(64bit)
#>=Pkg: ghostscript-core 9.16 4.fc24 x86_64
#>=Prv: libgs.so.9()(64bit)
#>=Req: urw-fonts >= 1.1
#>=Pkg: urw-fonts 3:2.4 22.fc24 x86_64
#>=Req: xorg-x11-font-utils
system x86_64 rpm system
job install name gimp
result transaction,problems
EOF
2. sed '/urw-fonts/ s/x86_64/noarch/;' <dep-chain-samearch.t >dep-chain-mixedarch.t
3. testsolv dep-chain-samearch.t
4. testsolv dep-chain-mixedarch.t

Actual results:
# testsolv dep-chain-samearch.t
Found 1 problems:
Problem 1:
nothing provides xorg-x11-font-utils needed by urw-fonts-3:2.4-22.fc24.x86_64

# testsolv dep-chain-mixedarch.t 
Found 1 problems:
Problem 1:
package gimp-2:2.8.18-1.fc24.x86_64 requires libgs.so.9()(64bit), but none of the providers can be installed

Expected results:
Missing package reported even for mixed arch chain.

**Comment by mlschroe** [comment]
Another tweak for the problemrule finding heuristic... fixed with commit 0c833337bceca33ab3009522cac1a54edfe5dba3
