### ISSUE TITLE
Limit packages to a subset of available ones

### ISSUE THREAD

**Issue by MichaelMraka** [openSUSE/libsolv#159]
I'd like to limit set of packages to install to a subset of available, e.g. to security updates only.
It seems SOLVER_SOLVABLE_ONE_OF job should do that but
```
repo system 0 testtags <inline>
#>=Pkg: k 1 0 x86_64
repo available 0 testtags <inline>
#>=Pkg: k 1 1 x86_64
#>=Pkg: k 2 0 x86_64
#>=Pkg: k 3 0 x86_64
#>=Pkg: k 3 1 x86_64
#>=Pkg: k 3 6 x86_64
system x86_64 rpm system

job update oneof k-3-1
job update oneof k-2-0
job update name k
result transaction,problems
```
ignores 'oneof' set and updates to a highest version anyway.
Is it a bug or is there a different way how to limit initial package set?

**Comment by mlschroe** [comment]
That's not how oneof works. You need to specify a set of specific packages, all in one line.
Like:
```
system x86_64 rpm system

job update oneof k-2-0.x86_64@available k-3-1.x86_64@available
result transaction,problems
```

If you're writing code, convert a queue filled with package ids by calling pool_queuetowhatprovides and put the resulting id into the SOLVER_SOLVABLE_ONE_OF job.

Some more explanation: libsolv jobs always work with a set of packages. The other methods like SOLVER_SOLVABLE_NAME and SOLVER_SOLVABLE_PROVIDES are just there to simplify your life, internally they are also converted into a set of packages. SOLVER_SOLVABLE_ONE_OF lets you directly specify the packages you want.

Note that there's no need for that "job update name k" job.

Also note that you probably also want to specify SOLVER_TARGETED to make sure that you don't go into untargeted mode if the set of packages includes an installed one.

**Comment by MichaelMraka** [comment]
That's exactly the missing piece of puzzle :).
Thanks.
