### ISSUE TITLE
No documentation or uncompleate for c-api

### ISSUE THREAD

**Issue by j-mracek** [openSUSE/libsolv#162]
According to issue #159 and PR #160 there is no documentation or uncompleate of C-API.

Only manpage of the language bindings is available, therefore description like for SOLVER_SOLVABLE_ONE_OF is misleading for usage in C.

**Comment by mlschroe** [comment]
I know. Patches welcome.

**Comment by mlschroe** [comment]
(There are libsolv-pool and libsolv-repo manpages, though. So it's not just the bindings.)
