### ISSUE TITLE
Problem with SOLVER_SOLVABLE_ONE_OF with secondary arch

### ISSUE THREAD

**Issue by j-mracek** [openSUSE/libsolv#163]
If I create a job using SOLVER_SOLVABLE_ONE_OF with single package ID with secondary arch (i686), but package primary arch available (x86_64), the transaction contains both packages (incorrectly). If I select single package with primary arch, only that package is installed.
The problem is related to use of SOLVER_SOLVABLE_ONE_OF  in PR https://github.com/rpm-software-management/libhif/pull/209/files.
Please is this behavior a feature or a bug and what can we do wit it?

**Comment by j-mracek** [comment]
It helps to use SOLVER_SOLVABLE_ONE_OF with SOLVER_SETARCH, but anyway is that wanted behavior?

**Comment by mlschroe** [comment]
Yes, it's the wanted behavior. If SOLVER_NOAUTOSET is not set, the solver tries to automatically add SET flags. For SOLVER_SOLVABLE, it assumes that the user want's exactly this package to be installed. For SOLVER_SOLVABLE_ONE_OF, it doesn't know if it's not just coi9ncidence that there is only one package in the set.

(Also note that your "(incorrectly)" can be disputed, as installing a secondary arch package without the primary one could be considered a misfeature.)
