### ISSUE TITLE
[RFE] show reason why package is not installable

### ISSUE THREAD

**Issue by ignatenkobrain** [openSUSE/libsolv#167]
Steps to Reproduce:
# dnf install fwknop-2.6.5-1.fc23.x86_64.rpm
[...]
Error: package fwknop-2.6.5-1.fc23.x86_64 is not installable

# yum-deprecated install fwknop-2.6.5-1.fc23.x86_64.rpm
[...]
Cannot add package fwknop-2.6.5-1.fc23.x86_64.rpm to transaction. Not a compatible architecture: x86_64
Error: Nothing to do

**Comment by ignatenkobrain** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1209393

**Comment by mlschroe** [comment]
True. Fixed in commit def918cdc9c2f770caec3bb0c6c0799e34a0773b
