### ISSUE TITLE
SOLVER_FLAG_NEED_UPDATEPROVIDE

### ISSUE THREAD

**Issue by j-mracek** [openSUSE/libsolv#169]
According to your comment in bugzila (https://bugzilla.redhat.com/show_bug.cgi?id=1096506) I prepared the patch for libdnf (https://github.com/rpm-software-management/libhif/pull/230) to use SOLVER_FLAG_NEED_UPDATEPROVIDE flag for upgrade, but before I will let it into review process I would like to ask you what exactly is beneficial of this flag or haw it change behavior of solver. Then I can create tests that ensure that it does what is supposed. Unfortunately I was unable to find any description in libsolv. Thank you in advance.

**Comment by j-mracek** [comment]
Anyway I have found that default behavior of libsolv for updates was change and formally failing test for provide was already fixed without inclusion of  SOLVER_FLAG_NEED_UPDATEPROVIDE flag.

**Comment by mlschroe** [comment]
This is not really about bug 1096506, but about the discussion in the last comments of the bug.

What SOLVER_FLAG_NEED_UPDATEPROVIDE is that it cnanges what is *allowed* for an update. With this flag on the solver will only consider packages an legal update candidate that also provide the installed package name. So simply obsoleting a package without the corresponding provides is no longer good enough.

This is not about what packages are preferred, but what packages are *allowed*. I.e. you will get an error if you want to install a package that obsoletes an installed package without the provides. (allowerasing will help, of course)

**Comment by mlschroe** [comment]
some documentation added, closing this issue...

**Comment by j-mracek** [comment]
Thanks a lot
