### ISSUE TITLE
"cannot install" message - reduce duplicates

### ISSUE THREAD

**Issue by dmach** [openSUSE/libsolv#172]
dnf prints:
  - cannot install both foo-x-y.arch and foo-x-z.arch
  - cannot install both foo-x-z.arch and foo-x-y.arch

I was told this comes from libsolv that returns these messages as strings.
Would be possible to remove the duplicates in libsolv or (even better) return the messages as structures so the tools can easily parse them and decide what to do?

**Comment by mlschroe** [comment]
libsolv returns strings if you ask it for strings. You can also get the information as structures. But libdnf/hawkey does not use that interface yet.
