### ISSUE TITLE
Ignoring file provides from @Commandline repo

### ISSUE THREAD

**Issue by j-mracek** [openSUSE/libsolv#174]
Added rpm files into sack show file provides pkg.files but libsolv do not acknowledge it, but if same rpm is used from repo, the file provides are normally used. 
Example:
sudo package ```requires /usr/bin/vi``` that is provided by ```vim-minimal```.

```
do dnf install vim-minimal-7.4.1989-2.fc25.x86_64.rpm
Repository 'fedora' is missing name in configuration, using id.
Last metadata expiration check: 2:39:06 ago on Wed Jan 18 08:15:22 2017 CET.
Failed to synchronize cache for repo 'beaker-client', disabling.
Error: problem with installed package sudo-1.8.18p1-1.fc25.x86_64
  - package sudo-1.8.18p1-1.fc25.x86_64 requires /usr/bin/vi, but none of the providers can be installed
  - package sudo-1.8.18p1-1.fc25.x86_64 requires /usr/bin/vi, but none of the providers can be installed
  - cannot install both vim-minimal-2:7.4.1989-2.fc25.x86_64 and vim-minimal-2:8.0.160-1.fc25.x86_64
  - cannot install both vim-minimal-2:7.4.1989-2.fc25.x86_64 and vim-minimal-2:7.4.1989-2.fc25.x86_64
  - cannot install both vim-minimal-2:7.4.1989-2.fc25.x86_64 and vim-minimal-2:8.0.176-1.fc25.x86_64
  - conflicting requests
(try to add '--allowerasing' to command line to replace conflicting packages)
```
but ```<hawkey.Package object id 2942, vim-minimal-2:7.4.1989-2.fc25.x86_64, @commandline> ``` provides files (pkg.files):
```
['/etc/virc', '/usr/bin/ex', '/usr/bin/rvi', '/usr/bin/rview', '/usr/bin/vi', '/usr/bin/view', '/usr/share/man/man1/ex.1.gz', '/usr/share/man/man1/rvi.1.gz', '/usr/share/man/man1/rview.1.gz', '/usr/share/man/man1/vi.1.gz', '/usr/share/man/man1/view.1.gz', '/usr/share/man/man1/vim.1.gz', '/usr/share/man/man5/virc.5.gz']
```
Using --allowerasing results in removal of sudo package (due to libsolv assumption that rpm file does not provide ```/usr/bin/vi```)

Thank you very much for any information.

**Comment by ignatenkobrain** [comment]
I guess there is missing request to libsolv's pool to make provides...

**Comment by mlschroe** [comment]
There's nothing I can do on the libsolv side. Closing.

**Comment by j-mracek** [comment]
@ignatenkobrain Please can you be little bit more specific. I didn't found any functionality that has to be triggered to create from sack package provide files pool file provides. And that it has to be triggered specially for commandline repo. Thanks a lot
