### ISSUE TITLE
inconsistance of rpmDB and @System.solv cache

### ISSUE THREAD

**Issue by j-mracek** [openSUSE/libsolv#175]
The problem is that data provided by @System.solv can differ from rpmDB. The problem appears for install remove loops with single package that is completely empty. To prevent the problem it helps add ```sleep 1``` after each step but once it appears wait step do not help. To repair dbs helps remove cache, @system.solv, or install or ramove other package than the problematic one.

To compare check sums (@system.solv and /var/lib/rpm/Packages) we use checksum_stat function that use functionality from libsolv (see bellow). For rpmDB we look at { "/var/lib/rpm/Packages",  "/usr/share/rpm/Packages" }.
 
If checksums differs we use dnf_sack_load_system_repo in libdnf file dnf-sack.c 
```
int flagsrpm = REPO_REUSE_REPODATA | RPM_ADD_WITH_HDRID | REPO_USE_ROOTDIR;
rc = repo_add_rpmdb_reffp(repo, cache_fp, flagsrpm);
```
and if equals:
```
rc = repo_add_solv(repo, cache_fp, 0);
```

```
checksum_stat(unsigned char *out, FILE *fp)
{
    assert(fp);

    struct stat stat;
    if (fstat(fileno(fp), &stat))
        return 1;

    /* based on calc_checksum_stat in libsolv's solv.c */
    void *h = solv_chksum_create(CHKSUM_TYPE);
    solv_chksum_add(h, CHKSUM_IDENT, strlen(CHKSUM_IDENT));
    solv_chksum_add(h, &stat.st_dev, sizeof(stat.st_dev));
    solv_chksum_add(h, &stat.st_ino, sizeof(stat.st_ino));
    solv_chksum_add(h, &stat.st_size, sizeof(stat.st_size));
    solv_chksum_add(h, &stat.st_mtime, sizeof(stat.st_mtime));
    solv_chksum_free(h, out);
    return 0;
```

To resolve it I would like to kindly ask you for your experience or information how libsolv handle it or whats the best practice.
1. Do you use cache of @system repo for zypper?

2. Any idea why comparisons of checksums fails? it reports that content is identical, but it differs.

3. Do we use flags for ```flagsrpm``` for repo_add_rpmdb_reffp correctly?

I believe that this is probably not an issue of libsolv, but any information that can provided is more that welcome.

Thank you very much.

**Comment by mlschroe** [comment]
I guess I can explain this. It happens when Berkleydb has enough space so that the Packages file doesn't change size. The granularity of mtime is just seconds, so the checksum does not change.

libzypp does not use checksum_stat. It seems to use the sha1sum of /var/lib/rpm/Name as cookie.

Newer filesystem types like ext4 provide the mtime in nanoseconds which should help.

**Comment by ignatenkobrain** [comment]
So I think with explanation of @mlschroe it's clear that there is nothing to fix in libsolv. Closing.
