### ISSUE TITLE
Simililar flag to SOLVER_CLEANDEPS?

### ISSUE THREAD

**Issue by j-mracek** [openSUSE/libsolv#178]
I am looking for a flag that can represent yum behavior (remove_leaf_only) on remove. 

The option is used to determine yum's behaviour when a package is removed.
If remove_leaf_only is `0' (default) then packages, and their deps, will be removed.  If remove_leaf_only is `1' then only those packages that aren't required by another package will be removed.

Thank you very much for any information, guesses or ideas

**Comment by mlschroe** [comment]
I don't get it. What's the difference to SOLVER_CLEANDEPS?

**Comment by j-mracek** [comment]
The difference is:
installed:
PkgA requires PkgB
PkgB

When I ask to remove PkgB that is required by PkgA, non of packages will be removed.

**Comment by ignatenkobrain** [comment]
@j-mracek then you don't set SOLVER_CLEANDEPS, no?

**Comment by j-mracek** [comment]
@ignatenkobrain I am not talking in this case about dependency, but I am talking about package that was request to remove. The task is like that, remove the package only in case that there is any package that requires it.

**Comment by j-mracek** [comment]
From my point of view the problem should be solved on solver level, because I expect that if I set both packages from above example for remove, both packages will be removed because there will be no package left on the system that requires any of removed package.

**Comment by j-mracek** [comment]
I realize that the request here can be handled by alternative job creation in libdnf and it not requires any changes in libsolv (WEAK and not use SOLVER_ALLOWUNINSTALL). Thanks all for help and opinions.
