### ISSUE TITLE
undefined symbol: solvable_matchesdep

### ISSUE THREAD

**Issue by mhatina** [openSUSE/libsolv#179]
Steps to reproduce:
1. `$ python`
2. `>>> import solv`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/solv.py", line 28, in <module>
    _solv = swig_import_helper()
  File "/usr/lib64/python2.7/site-packages/solv.py", line 24, in swig_import_helper
    _mod = imp.load_module('_solv', fp, pathname, description)
ImportError: /usr/lib64/python2.7/site-packages/_solv.so: undefined symbol: solvable_matchesdep

Aditional info:
$ `nm -D /usr/lib64/libsolv.so.0 | grep "solvable_matchesdep"`
$ `nm -D /usr/lib64/python2.7/site-packages/_solv.so | grep "solvable_matchesdep" `
U solvable_matchesdep

$ `rpm -q libsolv`
libsolv-0.6.25-1.fc24.x86_64
$ `rpm -q python2-solv`
python2-solv-0.6.25-1.fc24.x86_64

**Comment by ignatenkobrain** [comment]
seems like regression...

**Comment by mlschroe** [comment]
Oops. It's not exported. Fixing...

**Comment by mlschroe** [comment]
Sigh. version 0.6.26 fixes this.
