### ISSUE TITLE
Opened files not immediately closed

### ISSUE THREAD

**Issue by mhatina** [openSUSE/libsolv#180]
... or not at all

Steps to reproduce:
$ `dnf makecache`
(try `valgrind --track-fds=yes dnf makecache`)

Use case:
In dnf it is not possible to load more than ~500 repos due to `ulimit -n` == 1024 (for every repo there are 2 files opened, `*.solv` and `*.solvx`)

**Comment by ignatenkobrain** [comment]
have code to reproduce this issue? this might be bug in libdnf..

**Comment by mhatina** [comment]
No, unfortunately I don't have a code.

**Comment by mlschroe** [comment]
The solv files stay open if they contain data that is paged in on demand. So this is not a bug.
You could load all the data into mem, but then dnf would need quite a lot of memory...

**Comment by jrohel** [comment]
>You could load all the data into mem, but then dnf would need quite a lot of memory...
We can map files into memory. That means open file and use mmap.
Then we can close file because no file descriptor is needed. File is accessed as memory.
