### ISSUE TITLE
API/ABI changes review for libsolv

### ISSUE THREAD

**Issue by lvc** [openSUSE/libsolv#188]
The review of API/ABI changes for libsolv since 0.6.7 version: https://abi-laboratory.pro/tracker/timeline/libsolv/

The report is updated 3 times a week. Hope it will be helpful for users and maintainers of the library.

Created with the help of open-source abi-tracker tool: https://github.com/lvc/abi-tracker

Thank you.

![libsolv-1](https://cloud.githubusercontent.com/assets/1517837/24091158/b29bbdc6-0d5f-11e7-98cd-607946282612.png)

![libsolv-2](https://cloud.githubusercontent.com/assets/1517837/24091161/b8bf68d8-0d5f-11e7-8a27-24c60e00c174.png)

**Comment by ignatenkobrain** [comment]
it's full of false positives...

**Comment by mlschroe** [comment]
100% compatible. Good! Closing...

**Comment by cbandy** [comment]
It is detecting ABI changes in `libsolv.so.0`.

**Comment by lvc** [comment]
> it's full of false positives...

The tool checks _all_ API symbols declared in header files (does't take docs into account), so there may be some false positives.
