### ISSUE TITLE
SOLVER_FLAG_STRONG_RECOMMENDS seems to install either all Recommends or none

### ISSUE THREAD

**Issue by adelcast** [openSUSE/libsolv#193]
While testing SOLVER_FLAG_STRONG_RECOMMENDS, I found an issue. In a repo that has the following (pseudo code form opkg ATS):

o.add(Package="x")
o.add(Package="a", Recommends="b")
o.add(Package="b", Recommends="c")
o.add(Package="c", Conflicts="x")

And package 'x' is installed, when an 'install a' operation is run, only 'a' is installed. Seems to me like a better solution would be to install 'a' AND 'b', which is what you get without SOLVER_FLAG_STRONG_RECOMMENDS.

**Comment by mlschroe** [comment]
That's what you get when you make rules out of recommends... Fixed with commit 373957f7c8bbcc85771e2a2bd98621a51c7f90d6
