### ISSUE TITLE
transaction_order default ordering prioritizes replacee installation before replaced removal

### ISSUE THREAD

**Issue by adelcast** [openSUSE/libsolv#194]
Given a system that has package 'a' installed, and 'b' on the repository (and 'b' Provides/Conflicts/Replaces 'a'), libsolv default ordering seems of. After calling

    transaction_order(transaction, 0);

The transaction ordering is

[0] Install 'b'
[1] Remove 'a'

Given that 'b' conflicts with 'a', they can't be unpacked at the same time. However, the default ordering gives you a transaction that will end up with 'b' and 'a' unpacked at the same time. I would have expected the ordering to be reversed.

**Comment by mlschroe** [comment]
I don't really understand this issue. Normally the underlying package management code (rpm, dpkg and the like) is supposed to do the erasure of replaced packages. There should be no need to act on the transaction elements of replaced packages, that's why SOLVER_TRANSACTION_RPM_ONLY filters them out.

(At least for rpm this is done so that the installation scriptlets are able to do migrations of old data, which wouldn't be possible if the old package is deleted first.)

**Comment by adelcast** [comment]
Maybe I am thinking this wrong, but in opkg after the transaction is computed, it orders the elements (via transaction_order) and then acts on them. Basically, it just acts on ERASE, {RE | MULTI}INSTALL, DOWNGRADE  and UPGRADE [1]. The order returned puts the installation of the replacee first, before the removal of the replaced. 

Thinking about this, this may be a subtle difference between dpkg and rpm. On dpkg, I can see how the replaced package is being deleted first [2]. If you confirm that in rpm the expected behavior is to first install the replacee (to do data migration), I can document the behavior difference and move on. Since a replace operation is more akin to an upgrade, I do see why you would want to install the replacee first.

[1] http://git.yoctoproject.org/cgit/cgit.cgi/opkg/tree/libopkg/solvers/libsolv/opkg_solver_libsolv.c
[2] https://bugzilla.yoctoproject.org/show_bug.cgi?id=11362

**Comment by Conan-Kudo** [comment]
@adelcast I believe that rpm does install new package first and then remove the old one. The scriptlets are executed in that manner, as well: https://fedoraproject.org/wiki/Packaging:Scriptlets#Scriptlet_Ordering

**Comment by mlschroe** [comment]
Hmm. Seems like dpkg doesn't do automatic handling of replaces with conflicts. At least apt seems to manually erase conflicted packages (pkgPackageManager::EarlyRemove).

**Comment by adelcast** [comment]
I believe this is not a bug and can be closed. 

Sounds like the correct behavior is to treat the operation described in this ticket as an upgrade, which is already possible using the SOLVER_TRANSACTION_SHOW_OBSOLETES && SOLVER_TRANSACTION_OBSOLETE_IS_UPGRADE flags. I was incorrectly assuming that the correct behavior was to have erase/install operations (since that was the behavior on the old opkg solver)....but I am convinced the correct solution is to treat this as an upgrade. Feel free to to close this ticket if you agree with me here. Thanks for the taking the time to dig into this.

**Comment by mlschroe** [comment]
Closing.
