### ISSUE TITLE
Release 0.6.28

### ISSUE THREAD

**Issue by sunweaver** [openSUSE/libsolv#213]
Hi,

now that 75fa844d8c3658c01b286f5c72d87fce373cfe0b is in and libsolv does not FTBFS against perl 5.26 anymore, it might be nice to kick out 0.6.28, wouldn't it?

/me wonders if he should wait for a new upstream release in order to fix https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=865033

Thanks!
Mike

**Comment by ignatenkobrain** [comment]
why not to just backport patch?

**Comment by sunweaver** [comment]
Hi,

On  Mi 28 Jun 2017 23:57:28 CEST, Igor Gnatenko wrote:

> why not to just backport patch?

This is, of course, possible, too. However, if upstream plans a  
release soon, I'd rather wait for that to get all other changes in, too.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by mlschroe** [comment]
I'll do a release this week.

**Comment by sunweaver** [comment]
On  Do 29 Jun 2017 14:37:12 CEST, Michael Schroeder wrote:

> I'll do a release this week.

Thanks!
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by Conan-Kudo** [comment]
@sunweaver Release is out, so you can close this issue.

**Comment by sunweaver** [comment]
Thanks, already uploaded to Debian.
