### ISSUE TITLE
RFE: whatmatchesdep in existing selection

### ISSUE THREAD

**Issue by ignatenkobrain** [openSUSE/libsolv#220]
`selection_make_matchdepid()` is creating new selection from all solvables in pool. I already have queue of solvables which I want dep to match against which is many times less than whole pool. I think this should give it quite speedup.

probably something like `selection_filter_matchdepid()` or such would be good name, not sure.

**Comment by mlschroe** [comment]
You can do this with commit 4b14fee368e242d5d839f00a6a1415a23ac9a101 by using SELECTION_FILTER as flag to the selection_make_* functions. The implementation is not as fast as it could be, but it's a start.
