### ISSUE TITLE
PATH_MAX usage not portable to GNU/Hurd

### ISSUE THREAD

**Issue by sunweaver** [openSUSE/libsolv#222]
We in Debian see an FTBFS due to usage of the non-portable PATH_MAX constant in ext/repo_rpmdb.c and possibly other places in the libsolv source tree.

The solution is simple: use dynamic memory allocation instead as suggested by Samuel Thibault (@youpi): https://www.gnu.org/software/hurd/community/gsoc/project_ideas/maxpath.html

Here is the most recent build.log showing the error:
https://buildd.debian.org/status/fetch.php?pkg=libsolv&arch=hurd-i386&ver=0.6.28-2&stamp=1500888460&raw=0

**Comment by mlschroe** [comment]
Fixed. Thanks for the report!
