### ISSUE TITLE
libsolv is broken with RPM using non-BDB RPMDB

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/libsolv#227]
libsolv currently assumes that the RPMDB is always BDB and interacts with it directly using libdb.

To begin with, this is pretty dangerous as it requires knowing exactly how the rpmdb bdb environment is configured (and libsolv doesn't read the configuration from rpm, it has it hardcoded in itself).

Additionally, the implementation of the rpmdb has always been considered _private_, which is why RPM provides methods for accessing information in the database through its rpmdb/rpmts API.

Of course, until recently, it was pretty safe to assume BDB 5 for everything as it was the only backend in RPM for a while, but there are now three backends: BDB, NDB (since 4.13), and LMDB (since 4.14). libsolv is currently completely broken with NDB and LMDB RPMDB backends, since it can't read it and generate a repo cache for the system package database state.

Please consider using the RPM APIs for rpmdb access instead of the database APIs.

**Comment by ignatenkobrain** [comment]
That's what @ffesti wanted to do in #123

**Comment by ignatenkobrain** [comment]
I think latest versions of libsolv support this pretty well if configured with ENABLE_RPMDB_LIBRPM.
