### ISSUE TITLE
add namespace function for bindings

### ISSUE THREAD

**Issue by lnussel** [openSUSE/libsolv#231]
testsolve allows something like

namespace namespace:language(de) \@SYSTEM

please add a similar method to the bindings.

**Comment by mlschroe** [comment]
Dunno. The "right" thing would be to expose the namspace callback.

**Comment by lnussel** [comment]
whatever, as long as it allows python bindings get the desired result :)

**Comment by lnussel** [comment]
any ETA here? This is needed for Leap 15

**Comment by lnussel** [comment]
@mlschroe ?

**Comment by mlschroe** [comment]
There's now pool.set_namespaceproviders and pool.flush_namespaceproviders

The namespace callback is still work in progress, but you should be able to live
without it for now.

**Comment by lnussel** [comment]
Thanks! I see that the package auto updated in the devel project. The version number did not change though, nor was it submitted to Factory. What is needed to make that happen?

**Comment by Conan-Kudo** [comment]
I think @mlschroe would have to tag a release for that to happen. It'd be nice if a couple of other issues could be addressed before he does that, but I think that's basically what has to happened.
