### ISSUE TITLE
libsolv is broken with DEB using control.tar.xz

### ISSUE THREAD

**Issue by suihkulokki** [openSUSE/libsolv#233]
Since dpkg 1.19, debian packages have now control.tar.xz by default. This has been possible for a while, but nobody has used the feature since a) needed to be explicitly requested and b) there is not much disk space win for the small control dataset. But now packages with control.tar.xz have landed to Debian unstable and testing, gradually breaking building debian packages in OBS.

For someone unfamiliar with the codebase like me, this appears major work - if one is to follow the same low-level approach without using helper libraries.

**Comment by mlschroe** [comment]
Fixed with commit 787619e62c204bdf3e7e8736c5219059a558bd28

**Comment by suihkulokki** [comment]
Thanks! I've done a brief testing and now I'm able to build Debian unstable again. :tada:
