### ISSUE TITLE
RFE: disable selection of packages

### ISSUE THREAD

**Issue by ignatenkobrain** [openSUSE/libsolv#242]
Right now libsolv (at least in testcase) expects `disable pkg` and there is no way to do `disable provides`.  It would be nice feature I think to disable all things which provide something.

I think internally it should be implemented by doing selection and disabling everything what matches.

**Comment by ignatenkobrain** [comment]
Probably there was reason not to do this which I'm not aware of.. Correct me here/

**Comment by mlschroe** [comment]
No reason except that I implemented what testcase_write uses and was to lazy to do the rest.

**Comment by ignatenkobrain** [comment]
Ack, I will send PR.

**Comment by mlschroe** [comment]
Fixed with commit d8a0a6717bcf3f53811b05b274e20ac58c27f6b4
