### ISSUE TITLE
RFE: conditional Provides

### ISSUE THREAD

**Issue by ignatenkobrain** [openSUSE/libsolv#252]
It would be nice if instead creating empty "subpackages" which would just depend on some other packages it would be possible to write something like `Prv: (feature(foo) if (foo and bar))`.. I don't think that it would be easy to implement anytime soon in RPM, but at least libsolv could implement this and I would hack it up in DNF.

**Comment by ignatenkobrain** [comment]
So basically if someone asks for `job install provides X + feature(foo)`, it would install "foo and bar".

I think it should be easy to implement for @mlschroe...

**Comment by ignatenkobrain** [comment]
This is still valid RFE from my POV and would be nice feature.

**Comment by mlschroe** [comment]
Maybe, but I don't see any way to implement that.

**Comment by mlschroe** [comment]
Sorry, closing this with E2HARD.

**Comment by ignatenkobrain** [comment]
@mlschroe =(
