### ISSUE TITLE
SOLVER_DISFAVOR doesn't work with SOLVER_FLAG_STRONG_RECOMMENDS

### ISSUE THREAD

**Issue by adelcast** [openSUSE/libsolv#254]
SOLVER_FLAG_STRONG_RECOMMENDS provides the upgrade behavior that i need: recommends are upgraded too, instead of favoring the least amount of change in the system. The problem is that SOLVER_FLAG_STRONG_RECOMMENDS takes precedence over SOLVER_DISFAVOR. In my case, I want to implement an option to ignore recommends for a list of packages (--ignore-recommends=a,b,c). On my code, I set SOLVER_DISFAVOR to all the solvables defined in --ignore-recommends. This works if SOLVER_FLAG_STRONG_RECOMMENDS is unset, and doesn't if it is set. It would be really beneficial if it would work when SOLVER_FLAG_STRONG_RECOMMENDS is set.

**Comment by mlschroe** [comment]
I hopefully fixed this with commit 841ea42d1c53a8dcf22eeb0dde73925f201dde0b. Please test.

**Comment by adelcast** [comment]
just tested it, and indeed, it solves the problem. Thanks a lot!
