### ISSUE TITLE
RFE: expose "considered" in bindings

### ISSUE THREAD

**Issue by ignatenkobrain** [openSUSE/libsolv#258]
This probably will need some work on exposing `map*` too.

**Comment by ignatenkobrain** [comment]
FTR, @dparalen is working on this.

**Comment by dparalen** [comment]
yeah, early stages tho O:-)

**Comment by dparalen** [comment]
@ignatenkobrain hey man! :)
So finally got some time to start looking into this. IIRC you recommended me exposing the `struct Map` in some generic way. So here's a brief (stand-alone) SWIG bindings file exposing that:

```swig
// bitmap.i
// SWIG interface to the libsolv bitmap object

%module bitmap
%{
  #include "bitmap.h"
  #include "pooltypes.h"
%}

%include "bitmap.h"

typedef int Id;

%typemap(freearg) Map {
  map_free($1);
}

%extend _Map {
  void set_id(Id id) {
    // If encountered an ID bigger than size: resize the mapping first for the
    // ID to fit. The initial `$self->size == 0` is cool thanks to the handling
    // in bitmap:map_grow ~> util:solv_realloc. map_grow checks whether a
    // resize is actually needed.
    map_grow($self, (int)id);
    map_set($self, (int)id);
  }
}

%extend _Map {
  Id test_id(Id id){
    map_grow($self, (int)id);
    return (Id) map_tst($self, (int)id);
  }
}

%extend _Map {
  void clear_id(Id id){
    map_grow($self, (int)id);
    map_clr($self, (int)id);
  }
}
```
This can be compiled and "tested" in python:
* `cd libsolv && mkdir tmp && cd tmp`
* `ln -s ../src/bitmap.c ../src/bitmap.h ../src/util.c ../src/util.h ../src/pooltypes.h ./`
* supposing the above binding is saved locally: `swig -python bitmap.i`
* I've been testing on Fedora28 with Python2 (Pulp) so: `gcc -fpic -DHAVE_QSORT_R util.c bitmap.c bitmap_wrap.c -I/usr/include/python2.7`
* `gcc -shared  bitmap.o bitmap_wrap.o util.o -o _bitmap.so`

Having done that, one can play with the binding:
```python
import bitmap
m = bitmap.Map()
m.set_id(1024)
m.size
```
So I'd like to get some early feedback before I dig into making the `map->size` and `map->map` attributes read only etc. What I'm wondering is whether to use the `Id` type since it can be negative inside the solver... Also whether a `Map` makes sense outside of a `Pool`...

Thanks!
milan

**Comment by ignatenkobrain** [comment]
I was thinking about something else. I would rather implement `__setitem__`/`__getitem__`, so that you can do something like:

```python
m = solv.Map(16)
print(m[0]) # False
m[0] = True
print(m[0]) # True
m.set_all()
print(m[-1]) # True
print(m.size) # 16
print(m[16]) # IndexError
```

**Comment by dparalen** [comment]
@ignatenkobrain I see; lemme get back with that.
FWIW the `m.size` attribute is tracked in bytes on `struct Map` while the `map_init` expects a bit count. 

Thanks!
milan

**Comment by dparalen** [comment]
@ignatenkobrain so here's a take two, comments/suggestions are welcome!

```
// bitmap.i
// SWIG interface to the libsolv bitmap object

%module bitmap
%{
  #include "bitmap.h"
  #define INDEX_CHECK(map, index) \
    ({do if (index < 0 || index >= map->size << 3) return SWIG_IndexError; while(0);})
  #define ABS_INDEX(map, index)((index < 0)? (map->size << 3) + index: index)

  const int _Map_size_get(struct _Map* map) {
    return map->size << 3;
  }

%}

%feature("python:slot", "mp_subscript", functype="binaryfunc") Map::__getitem__;

%typemap(check) int size {
  if($1 < 0) {
    SWIG_exception_fail(SWIG_ValueError, "Expected a positive value or 0.");
  }
}

%typemap(ret) int {
  if ($1 == SWIG_IndexError) \
    SWIG_exception_fail(SWIG_IndexError, "Index outside range of this bitmap.");
}

typedef struct _Map {
  unsigned char *map;
  %extend {
    const int size;
    _Map(int size=0) {
      // a custom constructor that allows size to be specified
      struct _Map *ret = (struct _Map *)malloc(sizeof(struct _Map));
      map_init(ret, size);
      return ret;
    }
    ~_Map(void) {
      map_free($self);
      free($self);
    }

    int __setitem__(int index, int value) {
      int abs_index = ABS_INDEX($self, index);
      INDEX_CHECK($self, abs_index);
      if (value) map_set($self, abs_index);
      else map_clr($self, abs_index);
      return 0;
    }

    int __getitem__(int index) {
      int abs_index = ABS_INDEX($self, index);
      INDEX_CHECK($self, abs_index);
      return map_tst($self, abs_index)? 1: 0;
    }

    void grow(int size) {
      map_grow($self, size);
    }
  }
} Map;
```

FWIW the index error was a pain in all my body parts to implement; sorta works tho....
BTW do we want the `map->map` thing writable from the target language?

**Comment by mlschroe** [comment]
(Do we really need to expose bitmaps in the bindings? Wouldn't a "enable package" and "disable package" method in the pool be enough? Just thinking out loud...)

**Comment by ignatenkobrain** [comment]
Good question, all my use-casesuse-cases are about enabling/disabling packages. And obviously listing them.

**Comment by dparalen** [comment]
I'm cool either way, the exposing of the `Map` might be more versatile though.

**Comment by mlschroe** [comment]
Some other idea: note that we currently don't expose Queue as well, but use language native lists/arrays. So to transfer this to the "considered" map, it would mean a "pool.set_considered" method that would take a python-native set as argument and converts it into a Map via a SWIG typemap.

**Comment by dparalen** [comment]
@mlschroe gotcha; I guess that would be your preference as well, correct?
I'm cool reimplementing, just going to take couple more days (me still in a conference).

**Comment by dparalen** [comment]
@mlschroe I gave your suggestion some more thought (or two) and I'm wondering about how to encode the "unconsidered" solvables.

Assuming we want the input map for the `pool.set_considered()` to denote the "considered" solvables, if we want to use a (python) set of enabled solvables as the input for the map, `pool.set_considered()` has to calculate a conjunction between the input map and all the solvables in the pool as the "unconsidered" solvable map; correct?

Another thing I'm a bit worried about is how the `%typemap(in) Map {}` has to handle the input (python) set of solvables as the "considered" ones while any "gaps" in the IDs between subsequent solvables have to be handled as "unconsidered":
```SWIG
%typemap(in) Map {
  if (!PyList_Check($input)) SWIG_exception_fail(SWIG_TypeError, "A list required");
  int size = PyList_Size($input);
  for (int i = 0; i < size; i++) {
    PyObject *o = PyList_GetItem($input, i);
    int v;
    int e = SWIG_AsVal_int(o, &v);
    if (!SWIG_IsOK(e)) SWIG_exception_fail(SWIG_ArgError(e), "list must contain only integers");
    /* the value being set might be outside of the map range */
    map_grow(&$1, v);
    map_set(&$1, v);
  }
}
```
Yet another thing that's bothering me right now is how to make the `%typemap(out) Map {}` return both the "considered" and "unconsidered" sets of units.

Please, take my questions with a grain of salt as I'm far from being versed in SWIG actually, just wondering what can be done.

Thanks a lot!

**Comment by dparalen** [comment]
@ignatenkobrain @mlschroe so I've created a PR https://github.com/openSUSE/libsolv/pull/288 that implements @mlschroe 's idea --- at least I hope I got it right O:-) a tiny test:

```ipython
In [1]: import solv

In [2]: pool = solv.Pool()

In [3]: pool.setarch()

In [4]: pool.get_considered()
Out[4]: set()

In [5]: repo = pool.add_repo('repo')

In [6]: s1 = repo.add_solvable()

In [7]: s1.name = 's1'

In [8]: s2 = repo.add_solvable()

In [9]: s2.name = 's2'

In [10]: considered = set([s1.id, s2.id])

In [11]: pool.set_considered(considered)

In [12]: pool.get_considered()
Out[12]: {2, 3}

In [13]: considered = set([s2.id, 7])

In [14]: pool.set_considered(considered)

In [15]: s2.id in pool.get_considered()
Out[15]: True

In [16]: 7 in pool.get_considered()
Out[16]: False

In [17]: 

```
