### ISSUE TITLE
solvable doesn't store sourcename/sourceevr if it's same as original name/evr

### ISSUE THREAD

**Issue by ignatenkobrain** [openSUSE/libsolv#265]
```
$ dumpsolv /var/cache/dnf/rawhide.solv | grep "solvable:source.\+(void)" | wc -l                                                                                                      15:33:57
72134
```

I think this is wrong because for some of them, sourcename is set, but not sourceevr. I'm pretty sure that all packages contain proper SOURCERPM tag.

```python
import solv

pool = solv.Pool()
repo = pool.add_repo("@cmdline")
pkg = repo.add_rpm("rust-serde-devel-1.0.45-1.fc29.noarch.rpm")
print(pkg.lookup_str(solv.SOLVABLE_SOURCEEVR))
```

shows `None` for following file.

[rust-serde-devel-1.0.45-1.fc29.noarch.rpm.gz](https://github.com/openSUSE/libsolv/files/1995468/rust-serde-devel-1.0.45-1.fc29.noarch.rpm.gz)

**Comment by ignatenkobrain** [comment]
hmmm. it seems that void means that evr is same as evr of a package... is it really expected?

**Comment by ignatenkobrain** [comment]
So after some thinking I suppose that this is done to save some memory.. It would be nice to get some convenient functions which would do this by themselves... Probably something like `solvable_get_sourcename()` + `solvable_get_sourceevr()` + `solvable_get_sourcearch()`?

**Comment by mlschroe** [comment]
You mean `pkg.lookup_sourcepkg()`? That already exists ;)

**Comment by ignatenkobrain** [comment]
@mlschroe I wanted to get just source name/evr (without getting full nvr).

**Comment by mlschroe** [comment]
Ah, ok. But that's not how the interface currently works: you set a sourcepkg string with `repodata_set_sourcepkg()` and get the string back with `solvable_lookup_sourcepkg()`. The split into name/evr/arch is pretty internal and only meant to save space.

Also note that other formats just store a name instead of rpm's name-evr.arch.rpm
