### ISSUE TITLE
Segfault when pool_setarch() is not called

### ISSUE THREAD

**Issue by dparalen** [openSUSE/libsolv#267]
Hi folks!

I'm trying to blend a Python software packages management service [Pulp](https://pulpproject.org/) and libsolv to gain some advanced features when it comes to dependency resolving but I'm receiving a [SIGSEGV](https://pulp.plan.io/issues/3528#note-11) in the Python libsolv interface once I call [`solver.solve([<install_job>])`](https://pulp.plan.io/attachments/92089#L211)

Most likely I've been using libsolv in some strange way but I thought I'd try asking around.
I'm not entirely sure this is the best place to get help; please point me to an IRC channel or Mailing list if I'm being OT.

Thanks a lot!
milan

**Comment by ignatenkobrain** [comment]
reason is that `pool.setarch()` was not called.

**Comment by mlschroe** [comment]
Hmm, where does it crash? It shouldn't crash, not calling pool.setarch is a vaild thing.

**Comment by ignatenkobrain** [comment]
@dparalen for depsolving you would need to choose "some" architecture. So if you want to check multiple architectures, just do same function for resolving deps and call setarch() before each call.

**Comment by mlschroe** [comment]
Now fixed with commit 965e0a767d3fbd965d93fa9204276958a54a0909. Thanks for reporting this bug!

**Comment by dralley** [comment]
@ignatenkobrain I'm interested in the answer to "is it cool to call setarch() multiple times or do I need to create a fresh pool every time?"

**Comment by ignatenkobrain** [comment]
I think you can call setarch() without any problems. probably some existing data will be invalidated, but that is okay.

**Comment by mlschroe** [comment]
(Don't forget that the "whatprovides" data depends on the arch, so you may need to call pool_createwhatprovides() again)
