### ISSUE TITLE
Different targeted / untargeted update behavior

### ISSUE THREAD

**Issue by m-blaha** [openSUSE/libsolv#287]
Steps to reproduce (see also https://bugzilla.redhat.com/show_bug.cgi?id=1644241):

1. download acpi-1.7-9.fc28 source from fedora source repo, build binary rpm from it

2. install this newly built local rpm

3. create repo "a" which contains only the original acpi-1.7-9.fc28.rpm downloaded from fedora binary repo

4. enable repo "a" and run # dnf update

DNF now always uses targeted updates and in this case libsolv suggests to reinstall acpi package from "a" repository. If I change this (in DNF) to untargeted update, installed package is being kept and no update/reinstall occurs.
The only relevant difference between original fedora package in repo "a" and my new build of it (installed) is in the build time tag.
Here you can find debugdata from both transactions.

[debugdata-minimal-targeted.tar.gz](https://github.com/openSUSE/libsolv/files/2552148/debugdata-minimal-targeted.tar.gz)
[debugdata-minimal-untargeted.tar.gz](https://github.com/openSUSE/libsolv/files/2552151/debugdata-minimal-untargeted.tar.gz)

I'm using 0.6.35 version, and I've already tried backport commit https://github.com/openSUSE/libsolv/commit/0ce04714c477f25fde16c57b5fdc478755794126 but without success, reinstall is still there.
When I apply this patch to libsolv, there is no reinstall attempt regardless the update is targeted or untargeted.

```
diff --git a/src/solver.c b/src/solver.c
index a4e0c4b6..a3f0b87d 100644
--- a/src/solver.c
+++ b/src/solver.c
@@ -2987,7 +2987,7 @@ add_update_target(Solver *solv, Id p, Id how)
        add_cleandeps_updatepkg(solv, pi);
       queue_push2(solv->update_targets, pi, p);
       /* remember an installed package that is identical to p */
-      if (s->evr == si->evr && solvable_identical(s, si))
+      if (s->evr == si->evr)
        identicalp = pi;
     }
   if (s->obsoletes)
```

**Comment by mlschroe** [comment]
I don't think this is a bug because the installed rpm is different to the rpm in the repo. In your case only the buildtime is different, but this is not always the case.

A targeted update tells the solver to bring the package in sync with the selected package, so that's what it does.

**Comment by Conan-Kudo** [comment]
I'd consider this actually to be good behavior, because that would allow for "upgrades" to work correctly even when the EVR is the same but it targets a different distro release or something like that.

**Comment by mlschroe** [comment]
(I find dnf's switch to targeted updates a bit questionable, what was the rationale for this?)

**Comment by j-mracek** [comment]
We have several reason for the change:
1. We start to compute provides before setting of considered (dnf_sack_make_provides_ready). The feature was required by modularity because excludes are dynamically applied. The consequence was that untargeted upgrade "SOLVER_UPDATE|SOLVER_SOLVABLE_ALL" took as a best candidate excluded packages.
2. If user requiresto  disable obsoletes it requires targeted upgrade. Disabling obsoletes in pool was not an option.
3. In some cases targeted and untargeted transaction differs. Like if upgrade transaction requires downgrade of single package. Targedet allow downgrade, untargeted suggests removal. We would like to ensure that commands ``dnf upgrade`` and ``dnf upgrade "*"`` will result always in same result, but in some case there is a difference.

**Comment by mlschroe** [comment]
About the initial issue: the problem in the attached testcase is that the targeted update job does not include the installed package. I think this must be a bug in DNF.

Regarding your reasons:
1. you'll run into a lot of trouble if the whatprovides data does not match the considered packages when you run the solver. Be warned...
2. I think you want to unset  SOLVER_FLAG_ALLOW_NAMECHANGE if you don't want obsoletes handling for updates.
3. This should be debugged. I think it's a bug if they differ.

**Comment by ignatenkobrain** [comment]
@j-mracek do you have any updates on last issue or should I close this?

**Comment by j-mracek** [comment]
I will provide an additional information, but please give me a little bit more time. I would like to thanks @mlschroe for nice explanation. It helps a lot.

**Comment by mlschroe** [comment]
@j-mracek any update on this?

**Comment by mlschroe** [comment]
As libsolv does what it's supposed to do I'm closing this issue.
