### ISSUE TITLE
update [forcebest] + allowuninstall + disable = erase

### ISSUE THREAD

**Issue by ignatenkobrain** [openSUSE/libsolv#290]
```
repo system 0 testtags <inline>
#>=Pkg: a 1 1 noarch
#>=Req: b = 1-1
#>=Pkg: b 1 1 noarch
repo available 0 testtags <inline>
#>=Pkg: a 2 1 noarch
#>=Req: b = 2-1
#>=Pkg: b 2 1 noarch

system x86_64 rpm system

poolflags implicitobsoleteusescolors
solverflags allowvendorchange keepexplicitobsoletes bestobeypolicy keeporphans yumobsoletes

disable pkg b-1-1.noarch@system
disable pkg b-2-1.noarch@available
job allowuninstall pkg a-1-1.noarch@system
job allowuninstall pkg b-1-1.noarch@system
job update name a [forcebest]
result transaction,problems <inline>
```

```diff
Results differ:
+erase a-1-1.noarch@system
```

I believe that libsolv should rather say that it can't update `a` because `b` is disabled.

**Comment by mlschroe** [comment]
That's the beauty of using a sat solver: erasing a package is a vaild solution if the job is to make sure only the best versions are installed and allowuninstall is set.

**Comment by ignatenkobrain** [comment]
> That's the beauty of using a sat solver: erasing a package is a vaild solution if the job is to make sure only the best versions are installed and allowuninstall is set.

Which unfortunately sucks for end users. Would it be possible to have some flag to not allow it to do so?

I'm curious why this never came up before.

**Comment by mlschroe** [comment]
I don't think that it sucks. Your telling the solver "it's ok to uninstall to fix problems". That's exactly what happens.

**Comment by mlschroe** [comment]
It's a bit weird because you had a specific update job. But lets say your update job is `job update all packages [forcebest]`. I.e. make sure that all packages have the newest version. With 'allowuninstall' set you tell the solver "erasing is also an option"...

**Comment by ignatenkobrain** [comment]
> I don't think that it sucks

I rather meant that it is very surprising for people.

> But lets say your update job is job update all packages [forcebest]. I.e. make sure that all packages have the newest version. With 'allowuninstall' set you tell the solver "erasing is also an option"...

yeah, true. it probably needs some special case for such job types.... not sure... but then `update all packages` and `update pkg …` with all packages would differ.

**Comment by mlschroe** [comment]
(I could special case force update jobs in the autouninstall code, though.)

**Comment by ignatenkobrain** [comment]
> (I could special case force update jobs in the autouninstall code, though.)

That won't help I think because if we finally workaround #149 by NOAUTOSET, then it will break this case. But if you add flag for us in #149, then this could help I think.

**Comment by mlschroe** [comment]
I think it will help, though. Try commit d17aa8f15c354c27b7231196bc9468ac7890fb8f
