### ISSUE TITLE
Install of update of nss.x86_64 adds i686 into transaction

### ISSUE THREAD

**Issue by j-mracek** [openSUSE/libsolv#292]
Install of higher version of nss.x86_64 result in installing i686 packages. Upgrade of nss.x86_64 result in correct behavior (upgrade of nss and nss-sysinit).

Debugsolver data with minimal reproducer is available in https://bugzilla.redhat.com/show_bug.cgi?id=1663136.

It looks like that nss-sysinit.x86_64 requires 'nss = 3.39.0-2.fc29'. If I want to install nss-3.41.0-1.fc29.x86_64 the require 'nss = 3.39.0-2.fc29' is fulfill by installing of nss-3.39.0-2.fc29.i686 instead of upgrade nss-sysinit.x86_64 into nss-sysinit-3.41.0-1.fc29.x86_64

**Comment by ignatenkobrain** [comment]
As I wrote in bugreport, I don't think this is a bug in libsolv.

You didn't ask solver to update nss-sysinit and it is possible not to update it by installing 32bit package which solver does.

This is definitely a bug in nss packaging, so I think NOTABUG.

**Comment by Conan-Kudo** [comment]
The solver should be filtering by architecture already. This is kind of a problem if it doesn't do that, especially on distros that do multiarch by enabling 32-bit and 64-bit repos rather than doing Fedora-style multilib packages in 64-bit repos.

**Comment by ignatenkobrain** [comment]
Just in case anybody wants simple testcase, here it is:

```
#>=Pkg: a 1 1 x86_64
#>=Req: b = 1-1
#>=Pkg: b 1 1 x86_64
repo available 0 testtags <inline>
#>=Pkg: a 1 1 i686
#>=Req: b = 1-1
#>=Pkg: b 1 1 i686
#>=Pkg: a 2 1 x86_64
#>=Req: b = 2-1
#>=Pkg: b 2 1 i686

system x86_64 rpm system

poolflags implicitobsoleteusescolors
solverflags allowvendorchange keepexplicitobsoletes bestobeypolicy keeporphans yumobsoletes

job install oneof a-2-1.x86_64@available [setevr,setarch]
result transaction,problems <inline>
#>upgrade a-1-1.x86_64@system a-2-1.x86_64@available
#>upgrade b-1-1.x86_64@system b-2-1.x86_64@available
```

**Comment by j-mracek** [comment]
Minimal reproducer:
```
repo system 0 testtags <inline>
#>=Pkg: nss 3.39.0 2.fc29 x86_64
#>=Pkg: nss-sysinit 3.39.0 2.fc29 x86_64
#>=Req: nss = 3.39.0-2.fc29
repo available 0 testtags <inline>
#>=Pkg: nss 3.39.0 2.fc29 i686
#>=Pkg: nss 3.41.0 1.fc29 x86_64
#>=Pkg: nss-sysinit 3.41.0 1.fc29 x86_64
#>=Req: nss = 3.41.0-1.fc29

system x86_64 rpm system

poolflags implicitobsoleteusescolors
solverflags allowvendorchange keepexplicitobsoletes bestobeypolicy keeporphans yumobsoletes

job install oneof nss-3.41.0-1.fc29.x86_64@available [setevr,setarch]
result transaction,problems <inline>
#>upgrade nss-3.39.0-2.fc29.x86_64@system nss-3.41.0-1.fc29.x86_64@available
#>upgrade nss-sysinit-3.39.0-2.fc29.x86_64@system nss-sysinit-3.41.0-1.fc29.x86_64@available
```

**Comment by mlschroe** [comment]
Yeah, that's a bit unfortunate. What happens is that you disable the lock-step ("infarch") rule for nss with that install job that has the setarch bit set. This allows the solver to pull in the i686 nss package to fulfill the dependencies of nss-sysinit.

This is somewhat related to issue #149 in the sense that forcing lock-step will prevent the problem.

(You can also fix this by setting the SOLVER_FLAG_FOCUS_BEST solver flag, but this is somewhat untested. It might make solving a bit slower in some cases.)

**Comment by mlschroe** [comment]
I fixed this with commit 5323eb7e5c0c8dcdf339113f091317afaed810cc: basically there's no need to disable infarch rules if you install the best arch, like with x86_64 in the testcase above.

**Comment by mlschroe** [comment]
(Btw the difference between an install and an update job is that update jobs don't disable policy rules.)

**Comment by j-mracek** [comment]
Thanks a lot, it works now like expected
