### ISSUE TITLE
Solutions with i686 are not disfavored but forbidden 

### ISSUE THREAD

**Issue by j-mracek** [openSUSE/libsolv#294]
I have discovered a side affect of https://github.com/openSUSE/libsolv/commit/5323eb7e5c0c8dcdf339113f091317afaed810cc. In case that the only solution is to install i686 package the transaction fails (previously it passed). Please do you think is it possible to implement a behavior where solution with i686 packages will be available but disfavored?

Reproducer:
```
repo system 0 testtags <inline>
#>=Pkg: nss 3 1 x86_64
#>=Pkg: nss-sysinit 3 1 noarch
#>=Req: nss = 3-1
repo available 0 testtags <inline>
#>=Pkg: nss 3 1 i686
#>=Pkg: nss 4 1 x86_64
#>=Req: nss = 4-1

system x86_64 rpm system

poolflags implicitobsoleteusescolors
solverflags allowvendorchange keepexplicitobsoletes bestobeypolicy keeporphans yumobsoletes

job install oneof nss-4-1.x86_64@available [setevr,setarch]
result transaction,problems <inline>
#>upgrade nss-3-1.x86_64@system nss-4-1.x86_64@available
#>install nss-3-1.i686@available
```

**Comment by mlschroe** [comment]
Doesn't that conflict with issue#149? You're breaking the lock-step in your testcase.

**Comment by j-mracek** [comment]
Good point @mlschroe, I am going to discuss it with DNF team.

**Comment by j-mracek** [comment]
Thanks @mlschroe for explanation that promotes the site affect into wanted feature. It means that there is no problem.
