### ISSUE TITLE
Better solutions a la PubGrub

### ISSUE THREAD

**Issue by kentyman23** [openSUSE/libsolv#300]
[Natalie Weizenbaum](https://github.com/nex3) of [pub](https://pub.dartlang.org/)/[Dart](https://www.dartlang.org/)/Google added better conflict resolution with an algorithm called [Pubgrub](https://github.com/dart-lang/pub/blob/master/doc/solver.md), which she wrote about [here](https://medium.com/@nex3/pubgrub-2fb6470504f):

> So far, PubGrub has only been implemented in [Dart](https://www.dartlang.org/)’s package manager, pub. But it’s designed to be a general-purpose algorithm that could be implemented anywhere that’s solving the same problem. So file an issue on your favorite package manager’s GitHub repo and ask them (very politely) to add support for PubGrub.
>
>One major benefit of the algorithm is its flexibility. I’ve only written here about the most basic sort of version solving, but PubGrub is capable of working with any relationships between packages that can be represented as logical relationships between package ranges. Pub supports features like locked versions, forced upgrades, SDK version constraints, and dependency overrides. It’s easy to customize the behavior by tweaking what incompatibilities are supplied for each package.
>
>If you work on a package manager yourself and you’re interested in giving PubGrub a shot, I recommend reading [the full documentation](https://github.com/dart-lang/pub/blob/master/doc/solver.md). It dives much deeper into the details of the algorithm than I can do in one blog post, including both how it works and why we can be confident in its answers. If you have any questions, feel free to [file an issue](https://github.com/dart-lang/pub/issues/new) so that I can improve the documentation after I answer it. You can also reach out to me [on Twitter](https://twitter.com/nex3) or [by email](mailto:nweiz@google.com).

It would be great if libsolv incorporated similar changes.

**Comment by Conan-Kudo** [comment]
These features already exist in libsolv in various forms, from what I understand. It sounds like pubgrub is catching up to libsolv. :smile:

**Comment by mlschroe** [comment]
Closing.

**Comment by dralley** [comment]
There is at least one major difference, which is that PubGrub doesn't require eager loading of all the rules.

https://github.com/dart-lang/pub/blob/master/doc/solver.md#lazy-formulas

But I don't think changing libsolv is warranted.  The existing approach works pretty well and the scenarios where PubGrub does have benefits would probably benefit from a different API.

**Comment by mlschroe** [comment]
Libsolv also doesn't create rules for all packages, only for those that are relevant for the current job.
