### ISSUE TITLE
SOLVER_LOCKed package is used as a best candidate

### ISSUE THREAD

**Issue by j-mracek** [openSUSE/libsolv#302]
I tried to solve our issue with using excluded packages as a best candidates. In closed PR https://github.com/openSUSE/libsolv/pull/301 I got a recommendation to use an alternative approach for exclusion using SOLVER_LOCK. But after refactor of libdnf https://github.com/rpm-software-management/libdnf/pull/692 I discovered that SOLVER_LOCKed packages are used anyway as a best candidates. Additionally error messages are less informative, because they do not mention exclusion or locking of packages of packages.
```
repo system 0 testtags <inline>
#>=Pkg: TestB 1 1 noarch
repo available 0 testtags <inline>
#>=Pkg: TestA 1 1 noarch
#>=Pkg: TestA 1 2 noarch
#>=Pkg: TestA 1 3 noarch

system x86_64 rpm system

poolflags implicitobsoleteusescolors
solverflags allowvendorchange keepexplicitobsoletes bestobeypolicy keeporphans yumobsoletes

job install provides TestA [forcebest]
job lock pkg TestA-1-3.noarch@available
result transaction,problems <inline>
#>install TestA-1-2.noarch@available
```
```
repo system 0 testtags <inline>
#>=Pkg: TestA 1 1 noarch
repo available 0 testtags <inline>
#>=Pkg: TestA 1 1 noarch
#>=Pkg: TestA 1 2 noarch
#>=Pkg: TestA 1 3 noarch

system x86_64 rpm system

poolflags implicitobsoleteusescolors
solverflags allowvendorchange keepexplicitobsoletes bestobeypolicy keeporphans yumobsoletes

job update all packages [forcebest]
job lock pkg TestA-1-3.noarch@available
result transaction,problems <inline>
#>upgrade TestA-1-1.noarch@system TestA-1-2.noarch@available
```

**Comment by ignatenkobrain** [comment]
I don't think you should be locking not installed packages. what would that mean at all?

**Comment by Conan-Kudo** [comment]
I think the idea is to exclude packages from inactive modules?

**Comment by ignatenkobrain** [comment]
> I think the idea is to exclude packages from inactive modules?

In this case, you should be using `disable pkg`, no?

**Comment by Conan-Kudo** [comment]
@ignatenkobrain does that allow it to give you information about dependencies that exist in inactive modules? I thought `disable pkg` removes it from the set?

**Comment by mlschroe** [comment]
(I said that I'll have a patch ready this week, but I need a couple of more days. So it'll be next week. Sorrry.)

**Comment by j-mracek** [comment]
@mlschroe No problem. Thanks

**Comment by Conan-Kudo** [comment]
@mlschroe Any progress on this?

**Comment by Conan-Kudo** [comment]
@j-mracek It looks like @mlschroe has committed something that may help: https://github.com/openSUSE/libsolv/commit/b717d12a2ad5369b05e5d260d5609535b0225ef5

Does this resolve the issue for you?

**Comment by j-mracek** [comment]
@mlschroe Thanks a lot for for the patch. I am just testing it.
I see one difference in reports of excluded/solver_locked packages in case all options were locked/ excluded (see bellow). The knowledge about excludes is really useful. Please do you think is it possible to implement the error report improvement?

New outputs:
with SOLVER_FORCEBEST
 Problem: cannot install the best candidate for the job
  - conflicting requests

without SOLVER_FORCEBEST
 Problem: conflicting requests

Formal reports:
with SOLVER_FORCEBEST
 Problem: cannot install the best candidate for the job
  - package nodejs-1:12.3.1-1.module_f30+4381+32f791f9.x86_64 is excluded

without SOLVER_FORCEBEST
 Problem: conflicting requests
  - package nodejs-1:10.15.2-1.module_f30+3181+3be24b3a.x86_64 is excluded
  - package nodejs-1:11.3.0-1.module_2530+44f6dacf.x86_64 is excluded
  - package nodejs-1:8.12.0-1.module_2180+1761d862.x86_64 is excluded
  - package nodejs-1:10.15.3-2.module_f30+4047+77c83006.x86_64 is excluded
  - package nodejs-1:11.14.0-1.module_f30+3903+cd71f01a.x86_64 is excluded
  - package nodejs-1:12.3.1-1.module_f30+4381+32f791f9.x86_64 is excluded

**Comment by j-mracek** [comment]
The problem reported in this issue is not relevant anymore, because we got POOL_FLAG_WHATPROVIDESWITHDISABLED flag that resolves all issues in our workflows. Thanks @mlschroe a lot.
