### ISSUE TITLE
Make libsolv cross platform

### ISSUE THREAD

**Issue by wolfv** [openSUSE/libsolv#304]
I tried compiling libsolv on Windows and ran into a couple of issues:

- CMake is not yet MSVC aware (i.e. uses GCC compiler flags everywhere)
- funopen/fopencookie is used. This might be solved by using https://github.com/Snaipe/fmem
- fnmatch is not available on MSVC, we might be able to re-use FreeBSD or Linux sources (or can we drop the functionality for windows?)
- sys/uio.h header is (I think) not available on MSVC
- clock_t for the benchmark function will need the windows equivalent

Are there any other concerns? 

Are you positive on merging adjustments to get it to build & run on Windows?

**Comment by Conan-Kudo** [comment]
@wolfv Is there a reason we need to build with MSVC? Would having libsolv built with MinGW work for your case? It is a C library after all...

**Comment by wolfv** [comment]
I've never tried MinGW. If it's not too much work (e.g. ~1 day) then I think having a _native_ solution would be much preferable.

**Comment by Conan-Kudo** [comment]
MinGW is native, it's just GCC for Windows. :)

The annoying thing (from my personal experience) is that MSVC C standard conformance is patchy, and it's not fun to figure out how to make it happy sometimes.

**Comment by wolfv** [comment]
I'm really no expert, but: is there really no need to have any runtime libraries from MinGW?
If yes, if it was just a build dependency, then it could indeed work out.
I believe there is a MinGW toolchain on conda :)

**Comment by Conan-Kudo** [comment]
@wolfv it should only require `msvcrt` libraries by default, which is what MSVC does too.

**Comment by SylvainCorlay** [comment]
There is a mingw toolchain on conda, although I would like to upvote the support of MSVC on windows.

MSVC is the platform's compiler and for most package managers, windows packages are built with it. Since libsolv is pure C, it should not be too hard to build it on MSVC, if we can polyfill these system calls.

**Comment by mlschroe** [comment]
- fopencookie is only used in the "ext" library, so you don't really need it for solving dependencies. We can make this a compile time switch.
- we need fnmatch(), but it should be easy to use some BSD implementation.
- I think that sys/uio.h include in sha2.c is bogus.
- I don't think we use clock_t

**Comment by wolfv** [comment]
@mlschroe I've successfully compiled libsolv core with MSVC using (mostly) implementations from musl where necessary.

Are you interested in an PR for this?

**Comment by mlschroe** [comment]
I think this can be closed now ;)

**Comment by wolfv** [comment]
yeah! I checked some recent CI badges, and I think you didn't sign up libsolv for appveyor yet. The appveyor.yml is there so it should be trivial :)
