### ISSUE TITLE
No relation between SOLVABLE_PKGID and pkgid="YES" in metadata

### ISSUE THREAD

**Issue by j-mracek** [openSUSE/libsolv#308]
Probably I have a wrong expectation, but when I try ```ret = solvable_lookup_bin_checksum(s, SOLVABLE_PKGID, type);```, ```ret``` is always NULL even if ```pkgid="YES"``` is in metadata (see bellow). Please could anyone explain me the relationship or point me to documentation? Or is value ```pkgid="YES"``` simply ignored and ```SOLVABLE_PKGID``` is used for different purpose or on different system?

```
<checksum type="sha256" pkgid="YES">c04ac571e47ea7e725a58e49fe02288450d5566cb939c039507a07d686322647</checksum>
```

**Comment by mlschroe** [comment]
The pkgid comes from rpm, it's the ms5sum over header+payload. It has nothing to do with repository metadata.

**Comment by j-mracek** [comment]
Thanks a lot for explanation.
