### ISSUE TITLE
When there is an update job with cleandeps for a package, update jobs for a dependency of that package don't have an effect

### ISSUE THREAD

**Issue by EricAustinYu** [openSUSE/libsolv#309]
I am seeing unexpected behavior with the following two test cases:

> repo system 0 testtags \<inline\>
> #>=Pkg: a 1 1 x86_64
> #>=Req: b
> #>=Pkg: b 1 1 x86_64
> repo available 0 testtags \<inline\>
> #>=Pkg: a 2 1 x86_64
> #>=Req: b
> #>=Pkg: b 2 1 x86_64
> 
> system x86_64 rpm system
> job update all packages [cleandeps]
> result transaction,problems \<inline\>

And

> system x86_64 rpm system
> job update name a [cleandeps]
> job update name b [cleandeps]
> result transaction,problems \<inline\>

I would expect in these two cases that both "a" and"b" get upgraded. However, only "a" gets upgraded.

**Comment by mlschroe** [comment]
Yes, that was an oversight in the cleandeps code. Now fixed with commit 7da0695e67e17d73bc62bbf079e997bac9c7edea

**Comment by mlschroe** [comment]
Thanks for the report!

**Comment by mehagar** [comment]
Thanks @mlschroe for the fix! Could you create a release of this for us to use?

**Comment by mlschroe** [comment]
Sure. I normally wait a bit with releases, but if it's an urgent fix you need I'll do a release this week.

**Comment by mlschroe** [comment]
libsolv-0.7.4 is released.
