### ISSUE TITLE
0.7.3/0.7.4 regression in SOLVER_FAVOR handling

### ISSUE THREAD

**Issue by hanzz** [openSUSE/libsolv#312]
Hi,

Fedora just updated to libsolv 0.7.4 and our tests for module-build-service started failing. I'm attaching solver test describing the issue:

[solv-0.7.4-regression.tar.gz](https://github.com/openSUSE/libsolv/files/3033350/solv-0.7.4-regression.tar.gz)

We favored gtk:2:0:c4-0.x86_64 solvable in a test, but the solver chose gtk:1:0:c2-0.x86_64 despite the fact that gtk:2:0:c4-0.x86_64 solvable has also satisfied dependencies.

This test worked as expected (chose gtk:2:0:c4-0.x86_64) in the older libsolv-0.7.2.

Can you please verify if that's regression in libsolv? Or do we need to change our code somehow?

Updated: I cannot reproduce it using "testsolv" and I can reproduce it only using python3.

**Comment by hanzz** [comment]
I also think this might be related commit, but haven't tried doing bisect to verify that: https://github.com/openSUSE/libsolv/commit/2645bc64b322460ac77d0d051de63434d4a90a0a

**Comment by ignatenkobrain** [comment]
```
⋊> ~/D/s/test testsolv testcase.t                                                                                                                                           12:05:11
Results differ:
-install gtk:1:0:c2-0.x86_64@available
+install gtk:2:0:c4-0.x86_64@available
⋊> ~/D/s/test rpm -q libsolv                                                                                                                                                12:05:15
libsolv-0.7.4-1.fc31.x86_64
```

**Comment by hanzz** [comment]
I'm using libsolv-0.7.4-1.fc29.x86_64.

**Comment by hanzz** [comment]
Hm, and I also cannot reproduce it using testsolv :(...

```
$ testsolv testcase.t 
Results differ:
-install gtk:1:0:c2-0.x86_64@available
+install gtk:2:0:c4-0.x86_64@available
```

**Comment by hanzz** [comment]
I also found out that in MBS test-suite, I can only reproduce that on python3.

**Comment by mlschroe** [comment]
I can't reproduce the problem here. If I run the testcase the solver correctly installs gtk:2:0:c4-0.x86_64@available. Can you please attach the output of 'testsolv -v -v -v testcase.t'?

**Comment by mlschroe** [comment]
(Ah, you already found that out yourself. I should have reloaded that github page)

**Comment by mlschroe** [comment]
So, can you please add a pool.set_debuglevel(3) call in the python3 code and attach the output?

**Comment by hanzz** [comment]
@mlschroe, sending using fpaste: https://paste.fedoraproject.org/paste/AzADetFvaz2Z41t6SA8tDA.

Note that we run `solve()` twice with the same pool but different list of jobs. The first list of jobs return expected value, the second list of jobs is where the issue is. So when checking the paste, it's actually the second solve() method which returns gtk:1.0.

Maybe those two started influencing each other somehow :(.

**Comment by hanzz** [comment]
Hmm, so it seems that if I create brand new `solver = self.pool.Solver()` for each `solve()` call, it works even in Python3.

**Comment by hanzz** [comment]
I will wait for your opinion on that, but it seems creating new solver fixed this for me at least.

**Comment by ignatenkobrain** [comment]
```
2645bc64b322460ac77d0d051de63434d4a90a0a is the first bad commit
commit 2645bc64b322460ac77d0d051de63434d4a90a0a
Author: Michael Schroeder <mls@suse.de>
Date:   Mon Dec 10 15:05:39 2018 +0100

    Do favor evaluation before pruning
    
    This allows to support favoring single packages. As a side effect,
    we'll have the best version displayed as alternative.
    
    This changes the code to use a favor id for every solvable, which
    means that it uses quite a bit of memory but makes the code much
    easier and faster.

:040000 040000 f78aecb275180a1b2ae4fc4ed0efcf3d7d720ee2 75a6cd7e52888d44478b06bfe519b20744440944 M	src
:040000 040000 cfc77ee8aa72bcb13ec1c707d4a674aaa8a855cf 627b9d0a208014133b09cc892c6c8d43e29f8d0a M	test
```

**Comment by hanzz** [comment]
@ignatenkobrain, see my last commits. Maybe it is MBS misusing the libsolv API in a way which used to work before, but stopped working later.

This is what fixed the tests for me in MBS: https://pagure.io/fm-orchestrator/pull-request/1195

**Comment by ignatenkobrain** [comment]
No, it is supposed to work without recreating solver object.

**Comment by hanzz** [comment]
Does recreating the Solver object breaks anything? Given the this libsolv is in all stable Fedora releases, we want to workaround this issue at least for now. It also breaks MBS tests which adds extra work when reviewing PRs...

**Comment by ignatenkobrain** [comment]
@hanzz it just makes your program slower (and using more memory if Python doesn't GC object in time).

**Comment by ignatenkobrain** [comment]
```diff
diff --git a/src/solver.c b/src/solver.c
index b335e6af..7957373e 100644
--- a/src/solver.c
+++ b/src/solver.c
@@ -3389,6 +3389,7 @@ solver_solve(Solver *solv, Queue *job)
   map_zerosize(&solv->cleandepsmap);
   map_zerosize(&solv->weakrulemap);
   solv->favormap = solv_free(solv->favormap);
+  queuep_free(&solv->favorq);
   queue_empty(&solv->weakruleq);
   solv->watches = solv_free(solv->watches);
   queue_empty(&solv->ruletojob);
```

**Comment by ignatenkobrain** [comment]
Here is the PR: https://github.com/openSUSE/libsolv/pull/313
