### ISSUE TITLE
Install ext headers

### ISSUE THREAD

**Issue by wolfv** [openSUSE/libsolv#321]
I think to properly be able to use the `ext` goodies, libsolv needs to install the header files. The library seems to be properly installed already.

**Comment by mlschroe** [comment]
It does install the headers. What's missing?

```
 INSTALL (FILES ${libsolvext_HEADERS} DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/solv")
```

**Comment by wolfv** [comment]
true, I think it's just the json_parser header that's missing. Also I didn't expect the headers to be installed into the same `solv/` prefix which is why I was missing them on the command line output from install. 

Since I will not need the json parser header anymore, I'm closing this.
