### ISSUE TITLE
OS X rpath handling

### ISSUE THREAD

**Issue by wolfv** [openSUSE/libsolv#322]
I have some linking on OS X (for conda)

On the one hand, we get the following CMake warning (e.g. on libsolv travis: https://travis-ci.org/openSUSE/libsolv/jobs/521730048)

```
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
  MACOSX_RPATH is not specified for the following targets:
```
And on the other hand, for some reason that I don't understand the libsolv cmake set's the 
`INSTALL_NAME_DIR` property on the target, which seems to be a property that's only used on OS X and actually breaks the rpath behavior for the conda package.

Is there a reason for `INSTALL_NAME_DIR` to be set? I am removing it with a patch on conda for now. 

And also, maybe we should set MACOSX_RPATH to some value (the default (ON) works well for me in the conda package)? That would silence the warning.

**Comment by mlschroe** [comment]
Closing.
