### ISSUE TITLE
Convert "pysolv" example to Python 3

### ISSUE THREAD

**Issue by dralley** [openSUSE/libsolv#324]
Python 2 EOLs end of 2019

**Comment by mlschroe** [comment]
Yes, pysolv should be changed to work with both python2 and pythone3.

**Comment by mlschroe** [comment]
Hmm, actually I think I already did that. Doesn't it work with python3?

**Comment by dralley** [comment]
@mlschroe I think you're right, I just assumed from the shebang line that it was a Python 2 script.

 So really the shebang line should just be updated from ```#!/usr/bin/python``` to ```#!/usr/bin/python3```.

**Comment by dralley** [comment]
No need to keep an issue open for something simple like that

**Comment by Conan-Kudo** [comment]
> So really the shebang line should just be updated from `#!/usr/bin/python` to `#!/usr/bin/python3`.

The shebang follows current guidance for polyglot scripts, so it should probably get a CMake script adjustment to change the shebang accordingly depending on how python-solv is built (py2 or py3).

**Comment by dralley** [comment]
Ah, didn't know that.
