### ISSUE TITLE
Problem with rpm5 using bdb 4.7

### ISSUE THREAD

**Issue by mambasoft** [openSUSE/libsolv#327]
Hello,
I'm trying to switch a rpm5 (using bdb 4.7) based distribution to use dnf with PackageKit. 
The dnf command seems to work, though with PackageKit (+ libdnf + libsolv) I get this error:
'Failed to load system repo: write_main() failed to re-load written solv file

I've investigated on the problem and it appears it might be related to libsolv unable to parse the .solve file it creates just before by dumping rpmdb.

If I do:
rpmdb2solv /var/lib/rpm/ > test.solv

I get:
$ dumpsolv test.solv
data_read_id_max: id too large (3674472448/0)
unexpected EOF, depth = 3
could not read repository: unexpected EOF, depth = 3

I know that this (quite old) rpmdb target may not be of your interest, but I would like to know if my thoughts above are correct and if you can give me any hint to go over this problem. I can share a rpmdb in case you would be so kind and helpful to check the problem yourself.

Thanks!

**Comment by Conan-Kudo** [comment]
@mambasoft Unfortunately, to use DNF with rpm5, you'll probably want to use [a derivative of the old version of the DNF stack](https://gitlab.com/rpm5-legacy).

Ultimately, distributions that wanted to use DNF migrated to rpm from rpm.org to get there. Both Yocto Project (with Yocto 2.3) and OpenMandriva ([with OpenMandriva Lx 4](https://www.openmandriva.org/en/news/article/switching-to-rpmv4) did that, and I would advise the same.

If you need help doing the same, let me know. I'd be happy to assist as I can.

**Comment by mambasoft** [comment]
@Conan-Kudo Thanks for all the information. Based on your experience I think I'll (re)consider switching back to rpm 4. I will let you know if I need some hint while working on this migration.

**Comment by mambasoft** [comment]
@Conan-Kudo Hi again, I made a preliminary build of rpm 4.14.2.1 and I wonder if you can give me a couple of basilar hints to work on migration. Please let me know if there is a better place to write about this topic.
My basic questions are:
1) do you have any hint on how the mentioned distros did migrate existing rpm db from rpm5 to rpm? As I said our current rpmdb is based on rpm 5.2.1 with internal bdb 4.7
2) what would be the best db backend to start with rpm 4? It currently built with bdb 5.1 because it found this as dependency on my build server altough this is not the most recent bdb release
Thanks again!
P.S. the distribution is openmamba (https://openmamba.org)

**Comment by Conan-Kudo** [comment]
So, your rpm5 should be old enough that `rpm --rebuilddb` should mostly work. I recommend using bdb 5.3, as that's actively tested in Fedora and Mageia.

**Comment by Conan-Kudo** [comment]
@mambasoft Use BDB 5.3 with the patches available here: https://src.fedoraproject.org/rpms/libdb

That will make it much more reliable.

(Also, I'm aware of OpenMamba, as I sent you an email nearly two years ago about OpenMamba adopting DNF)

**Comment by mambasoft** [comment]
That sounds good, thanks!
Oh sorry, I forgot about that email, although at that time I wasn't able to take in charge such a migration considering that we also have maintenance tools based on rpm 5.2 and ~40 patches applied to rpm itself to fit our needs. Now this migration becomes our priority hoping to fix current problems for a long term.
Thanks for your support, I will let you know how it goes.

**Comment by mlschroe** [comment]
Could you please make the broken test.solv file available to me, so that I can have a look what's wrong with it?

**Comment by mlschroe** [comment]
(Also note that libsolv must be configured with -DRPM5=1 to make it work with rpm5. But you probably already did that. But @Conan-Kudo is right, rpm5 seems to be dead, so switching to rpm4 is good advice ;) )

**Comment by mambasoft** [comment]
@mlschroe Sure, here is the file: https://openmamba.org/pub/tmp/test.solv.gz
This one was created with the rpmdb2solv command above, while here is also the tmp file created by PackageKit: https://openmamba.org/pub/tmp/System.solv.xboBUR.gz
I've tried using libsolv from 0.6.34 to 0.7.4 and different versions of PackageKit but the problem reported is always the same in the write_file() function (an unexpected EOF error somewhere). Yes, I use the -DRPM5=1 and have tried other options, like -DENABLE_RPMDB_LIBRPM=ON, but they would require further patching to build with rpm5.
I'm sure that migrating to rpm 4 is to be done, but if a quick analisys of the test.solv could suggest a quick fix that would be good as well for the short time. Thanks!

**Comment by Conan-Kudo** [comment]
@mambasoft RPM5 allows for highly custom BDB opts, and its defaults are quite different from rpm4 now. I had [made this patch](https://gitlab.com/rpm5-legacy/libsolv/commit/eea5159799e661a449a363d54e27f67cf66b273a.patch) to deal with that difference when I was working on it long ago, and that had helped things a bit.

**Comment by mambasoft** [comment]
@Conan-Kudo I think the patch is already integrated upstream and I've also tried playing with the alternative code provided by defines. One #ifdef RPM5 block is inside a #ifdef FEDORA, so I'm not sure that I've tried that, by the way since I don't know the format of the .solv file so I was just doing blind attempts, so I decided to ask for help here.

**Comment by mlschroe** [comment]
Ok, I fixed the problem that the solv file is not readable. It tuned out that it contained database ids bigger than 2^31.

So now the solv file can be read, *but*: the underlying issue is not fixed yet. The database ids are read in the wrong byte order.

**Comment by mlschroe** [comment]
So, could you upload rpm's Packages file (/var/lib/rpm/Packages)?

**Comment by mlschroe** [comment]
(And also /var/lib/rpm/Name)

**Comment by Conan-Kudo** [comment]
> So now the solv file can be read, but: the underlying issue is not fixed yet. The database ids are read in the wrong byte order.

That sounds like rpm5 doesn't force byte orders for the db like rpm4 does now...

**Comment by mlschroe** [comment]
AFAIR rpm5 switched to always use big endian for the database id. I'll see when I get access to the Packages file.

**Comment by mlschroe** [comment]
(Unfortunately rpm4 uses native byte order. Bah.)

**Comment by Conan-Kudo** [comment]
Oh, so I have it backwards? blech.

**Comment by mambasoft** [comment]
@mlschroe Maybe this would be somehow managed by this code:
`static inline Id db2rpmdbid(unsigned char *db, int byteswapped)
{
#ifdef RPM5
  return db[0] << 24 | db[1] << 16 | db[2] << 8 | db[3];
#else
# if defined(WORDS_BIGENDIAN)
  if (!byteswapped)
# else
  if (byteswapped)
# endif
    return db[0] << 24 | db[1] << 16 | db[2] << 8 | db[3];
  else
    return db[3] << 24 | db[2] << 16 | db[1] << 8 | db[0];
#endif
}`

(where the endianess swap is not considered if RPM5 is defined).

**Comment by mlschroe** [comment]
Yes, I know that code. I just don't know what's correct.

**Comment by mambasoft** [comment]
(sorry for above code formatting...) I'm preparing the rpm db files for download

**Comment by mambasoft** [comment]
Here it is: https://openmamba.org/pub/tmp/rpmdb.tar.bz2
Please, consider that there might be differences between rpm 5.2 which I'm using and 5.4 which might be the target of your past tests for other distros.

**Comment by mlschroe** [comment]
Well, that explains it. They switched to big endian in rpm 5.3.

**Comment by mlschroe** [comment]
I think rpm5 has a /usr/include/rpm/rpmversion.h header file we can use. Is that correct?

**Comment by mambasoft** [comment]
Yes! The file contains:

/* compile-time information */
#define RPMLIB_VERSION   RPMLIB_VERSION_ENCODE(5,2,r,1,0,_)
#define RPMLIB_TIMESTAMP RPMLIB_TIMESTAMP_ENCODE(2009,0,0,0,0)
#define RPMLIB_VENDOR    RPMLIB_VENDOR_ENCODE('R','P','M','5')

**Comment by mambasoft** [comment]
Now I remember that I had problems to upgrade to 5.3+ because it did not work on the arm target, so at the end the distribution stayed with 5.2.1 until today...

**Comment by mlschroe** [comment]
Ok, please test if commit 68d72a88d5dc983aff2ff5dce65581de0ee42b6d fixes this.
dumpsolv should show small numbers for the rpm:dbid lines.

**Comment by mlschroe** [comment]
The index databases also had array offsets, like with rpm4. Commit 841287dfb7a5992b374aa5326e776cd7d54fc0da fixes this as well.

**Comment by mambasoft** [comment]
Great, I'm going to test the patches, but I'm currently trying to fix this build error:
`/usr/src/RPM/BUILD/libsolv-0.7.4/ext/repo_rpmdb_bdb.h:32:6: error: pasting "RPMLIB_VERSION_ENCODE_T_" and "(" does not give a valid preprocessing token`

**Comment by mlschroe** [comment]
rpm's RPMLIB_VERSION_LT is buggy. sigh. I'll add a workaround.

**Comment by mlschroe** [comment]
commit ab54abba2ba4eac2fcf0f35cf05e61fb070212eb

**Comment by mambasoft** [comment]
I've applied the three patches and it works! Both dumpsolv and PackageKit no longer show thw error and go further, although I want to do a more complete test on a clean installation. Please let me know if you want me to do some specific tests. Thanks for the help, really appreciated!

**Comment by mambasoft** [comment]
Hello again,
after the solution to the above problem I faced further problems so I'm now testing the switch from rpm 5.2.1 to 4.14.2.1. Unfortunately 'rpm --rebuilddb' fails with this output:

error: rpmdbNextIterator: skipping h#     769 tag[65]: BAD, tag 1029 type 2 offset 1992 count 7 len 8
error: rpmdbNextIterator: skipping h#     259 tag[70]: BAD, tag 1029 type 2 offset 3976 count 19 len 8
error: rpmdbNextIterator: skipping h#    1028 tag[63]: BAD, tag 1029 type 2 offset 1340 count 3 len 8
error: rpmdbNextIterator: skipping h#     518 tag[67]: BAD, tag 1029 type 2 offset 2220 count 5 len 8
...
error: rpmdbNextIterator: skipping h#    1023 tag[68]: BAD, tag 1029 type 2 offset 2972 count 2 len 8
error: failed to replace old database with new database!
error: replace files in /var/lib/rpm with files from /var/lib/rpmrebuilddb.6013 to recover

This looks quite hard for me to understand and fix... the rpm5 should be db 4.8 based, but I'm not completely sure, rpm4 is currently built with db 5.1.

Any help on how to perform the db upgrade would really be appreciated... thanks!

**Comment by Conan-Kudo** [comment]
@mambasoft Those are because rpm5 packages have tags the rpm4 rpmdb doesn't understand. They _should_ go away as you rebuild and replace packages with rpm4 built ones.

**Comment by Conan-Kudo** [comment]
Also, the way rpm rebuilds databases changed with rpm 4.14... If you have alternatives in `/var/lib/rpm/alternatives`, it needs to be moved out to `/var/lib/alternatives` so that rpmdb rebuilds don't break.

**Comment by Conan-Kudo** [comment]
After you've corrected for that, do the rpmdb rebuild twice. It'll throw errors the first time, and the second time it'll succeed.

**Comment by mambasoft** [comment]
I don't have a /var/lib/rpm/alternatives and rebuilding twice or more still produces the same output.
If I look into /var/lib/rpmrebuilddb.* after rebuild I have a correct db but with only 3 packages, which seem to be the only ones in my db which don't provide files. I suppose rpm --rebuild is skipping all packages with the unknown tag 1029. Looking at rpm5 includes this tag is:

/usr/include/rpm/rpmtag.h:    RPMTAG_FILESTATES         = 1029, /* c[] */

Maybe I could try to patch rpm4 in order to understand this tag so that it won't skip the whole package entry? Just guessing at the moment...thanks!

**Comment by Conan-Kudo** [comment]
That tag exists in rpm4, the problem is the values are invalid for rpm4...

**Comment by mambasoft** [comment]
In rpm5 it is defined as:
        { "RPMTAG_FILESTATES",  1029,   RPM_UINT8_TYPE + RPM_ARRAY_RETURN_TYPE },

So I've tried the following patch and I don't see any more error in rpm --rebuilddb and the new db seems populated with all packages:

--- rpm-4.14.2.1/lib/tagtbl.C   2018-10-18 12:14:57.563260243 +0200
+++ rpm-4.14.2.1.patched/lib/tagtbl.C   2019-06-21 16:27:22.481132393 +0200
@@ -65,7 +65,7 @@ [...]
-    { "RPMTAG_FILESTATES", "Filestates", RPMTAG_FILESTATES, RPM_CHAR_TYPE, RPM_ARRAY_RETURN_TYPE, 0 },
+    { "RPMTAG_FILESTATES", "Filestates", RPMTAG_FILESTATES, RPM_INT8_TYPE, 

Now I should understand in more detail what are the consequences of this change and if I can rebuild the db while keeping the correct type (RPM_CHAR_TYPE) for this tag.

**Comment by eduardoj** [comment]
Related ONLY with the formatting of code in github comments, you can try ``` blocks. Taken from the code section from the [examples markdown help from github](https://guides.github.com/features/mastering-markdown/#examples). I hope it helps. For example:

In rpm5 it is defined as:
```
{ "RPMTAG_FILESTATES", 1029, RPM_UINT8_TYPE + RPM_ARRAY_RETURN_TYPE },
```
So I've tried the following patch and I don't see any more errors in rpm --rebuilddb and the new db seems populated with all packages and files:
```
--- rpm-4.14.2.1/lib/tagtbl.C 2018-10-18 12:14:57.563260243 +0200
+++ rpm-4.14.2.1.patched/lib/tagtbl.C 2019-06-21 16:27:22.481132393 +0200 @@ -65,7 +65,7 @@ [...]
- { "RPMTAG_FILESTATES", "Filestates", RPMTAG_FILESTATES, RPM_CHAR_TYPE, RPM_ARRAY_RETURN_TYPE, 0 },
+ { "RPMTAG_FILESTATES", "Filestates", RPMTAG_FILESTATES, RPM_INT8_TYPE, RPM_ARRAY_RETURN_TYPE, 0 },
```
[...]

**Comment by mambasoft** [comment]
@eduardoj thanks for the hint, it is one thing I was wandering about but didn't do a search outside the editor.

**Comment by mlschroe** [comment]
I don't think you should patch the tagtbl file. rpm5 contains this code:

```
        /* XXX Convert RPMTAG_FILESTATE to RPM_UINT8_TYPE. */
        if (info->tag == 1029 && info->type == 1) {
            info->type = RPM_UINT8_TYPE;
        }
```

Can't you do something similar (patch RPM_UINT8_TYPE back to RPM_CHAR_TYPE) in rpm's hdrblobVerifyInfo function?

**Comment by mambasoft** [comment]
Ok, I eventually patched it this way, so that, I suppose, rpmdb will have the standard format.
Just for info, the other way did work after fixing the only place in code where RPM_INT8_TYPE and RPM_CHAR_TYPE are treated differently:

```
--- rpm-4.14.2.1.orig/lib/rpmtd.c	2018-09-13 14:52:02.227221535 +0200
+++ rpm-4.14.2.1/lib/rpmtd.c	2019-06-22 15:00:23.436132478 +0200
@@ -151,7 +151,7 @@
 {
     char *res = NULL;
 
-    if (td != NULL && td->type == RPM_CHAR_TYPE) {
+    if (td != NULL && (td->type == RPM_CHAR_TYPE || td->type == RPM_INT8_TYPE)) {
 	int ix = (td->ix >= 0 ? td->ix : 0);
 	res = (char *) td->data + ix;
     } 
```

So going further, rpm 4 upgrade works although any subsequent rebuilddb always returns:

```
error: failed to replace old database with new database!
error: replace files in /var/lib/rpm with files from /var/lib/rpmrebuilddb.xxxx to recover
```

caused by a `rename('/var/lib/rpm', '/var/lib/rpmold.xxx')`. This might be caused by locking, btw is this normal behaviour?

Last, dnf and PackageKit are now working fine with rpm4, except I have problems in "color" support, i.e. allowing 64 and 32 bit packages support on the same system. Is this supported by libsolv / libdnf ?Should I open a more specific issue on this?

Thanks!

**Comment by Conan-Kudo** [comment]
This is supported, but multilib packages need to be the same NEVR to install correctly by default.

**Comment by Conan-Kudo** [comment]
As for `rpm --rebuilddb`, the behavior changed in rpm 4.14, you could try purging all the lock files before running the rebuild command.

**Comment by mambasoft** [comment]
> This is supported, but multilib packages need to be the same NEVR to install correctly by default.

Fine, but I faced some problems which may depend on my arch setup or understanding how this works.
The first problem is that if I do, e.g.:
`sudo dnf install libattr.i586`

I get a "Cannot install due to inferior arch" (sort of) error. I can patch this by adding in libdnf:
`solver_set_flag(solv, SOLVER_FLAG_NO_INFARCHCHECK, 1);`

but this is probably not the intended way (as it will also replace x86_64 packages with i586)...

**Comment by Conan-Kudo** [comment]
@mambasoft How can I try openmamba with DNF? It's hard to do debugging without being able to see the environment...

**Comment by mambasoft** [comment]
Well, if you have got some time this is one way:
1) download rolling livecd for x86_64 from `https://openmamba.org/en/downloads/`
2) you may boot the image as a VM, or on a real PC by dd-ing the image to a USB storage
3) to install rpm4 with dnf:
`sudo yum install dnf openmamba-release PackageKit rpm --enablerepo=unstable-misc`
4) (optional) I'm working on a system installed on a persistent storage pendrive so that I can quickly reset to an initial setup (but with e.g. ssh access configured) by copying/renaming the `/rwroot` directory used by overlayfs
