### ISSUE TITLE
broken with RPM5

### ISSUE THREAD

**Issue by mikhailnov** [openSUSE/libsolv#328]
libsolv seems to be severely broken with RPM5.
I made a file `/usr/include/rpm/rpm415compat.h`:
```c
/* Partial compatibility with RPM 4.15 */

#ifndef	H_RPM415COMPAT
#define	H_RPM415COMPAT		1

#include <rpm/rpm4compat.h>
#include <rpm/rpm46compat.h>
#include <rpmbuild.h>

enum rpmVSFlags_e {
    RPMVSF_DEFAULT	= 0,
    RPMVSF_NOHDRCHK	= (1 <<  0),
    RPMVSF_NEEDPAYLOAD	= (1 <<  1),
    /* bit(s) 2-7 unused */
    RPMVSF_NOSHA1HEADER	= (1 <<  8),
    RPMVSF_NOSHA256HEADER = (1 <<  9),
    RPMVSF_NODSAHEADER	= (1 << 10),
    RPMVSF_NORSAHEADER	= (1 << 11),
    /* bit(s) 12-15 unused */
    RPMVSF_NOPAYLOAD	= (1 << 16),
    RPMVSF_NOMD5	= (1 << 17),
    RPMVSF_NODSA	= (1 << 18),
    RPMVSF_NORSA	= (1 << 19)
    /* bit(s) 16-31 unused */
};

#define	RPMVSF_MASK_NODIGESTS	\
  ( RPMVSF_NOSHA1HEADER |	\
    RPMVSF_NOSHA256HEADER |	\
    RPMVSF_NOPAYLOAD |	\
    RPMVSF_NOMD5 )
#define	_RPMVSF_NODIGESTS	RPMVSF_MASK_NODIGESTS

#define	RPMVSF_MASK_NOSIGNATURES	\
  ( RPMVSF_NODSAHEADER |	\
    RPMVSF_NORSAHEADER |	\
    RPMVSF_NODSA |		\
    RPMVSF_NORSA )
#define	_RPMVSF_NOSIGNATURES	RPMVSF_MASK_NOSIGNATURES

#define	RPMVSF_MASK_NOHEADER	\
  ( RPMVSF_NOSHA1HEADER |	\
    RPMVSF_NOSHA256HEADER |	\
    RPMVSF_NODSAHEADER |	\
    RPMVSF_NORSAHEADER )
#define	_RPMVSF_NOHEADER	RPMVSF_MASK_NOHEADER

#define	RPMVSF_MASK_NOPAYLOAD	\
  ( RPMVSF_NOMD5 |		\
    RPMVSF_NOPAYLOAD |		\
    RPMVSF_NODSA |		\
    RPMVSF_NORSA )
#define	_RPMVSF_NOPAYLOAD	RPMVSF_MASK_NOPAYLOAD



#endif /* H_RPM415COMPAT */
```

Then patched libsolv:
```diff
diff --git a/ext/repo_rpmdb.c b/ext/repo_rpmdb.c
index fb1491b1..38f3f4bf 100644
--- a/ext/repo_rpmdb.c
+++ b/ext/repo_rpmdb.c
@@ -31,6 +31,11 @@
 #ifndef RPM5
 #include <rpm/header.h>
 #endif
+#ifdef RPM5
+#include <rpm/rpm4compat.h>
+#include <rpm/rpm46compat.h>
+#include <rpm/rpm415compat.h>
+#endif
 #include <rpm/rpmdb.h>
 
 #endif
```

That solved some build issues, but they remained:

```
In file included from /tmp/abf/rpmbuild/BUILD/libsolv-0.7.5/ext/repo_rpmdb.c:1235:
/tmp/abf/rpmbuild/BUILD/libsolv-0.7.5/ext/repo_rpmdb_librpm.h: In function ‘getinstalledrpmdbids’:
/tmp/abf/rpmbuild/BUILD/libsolv-0.7.5/ext/repo_rpmdb_librpm.h:125:3: error: unknown type name ‘rpmdbIndexIterator’; did you mean ‘rpmdbMatchIterator’?
   rpmdbIndexIterator ii;
   ^~~~~~~~~~~~~~~~~~
   rpmdbMatchIterator
/tmp/abf/rpmbuild/BUILD/libsolv-0.7.5/ext/repo_rpmdb_librpm.h:137:8: warning: implicit declaration of function ‘rpmdbIndexIteratorInit’; did you mean ‘rpmdbInitIterator’? [-Wimplicit-function-declaration]
   ii = rpmdbIndexIteratorInit(rpmtsGetRdb(state->ts), RPMDBI_NAME);
        ^~~~~~~~~~~~~~~~~~~~~~
        rpmdbInitIterator
/tmp/abf/rpmbuild/BUILD/libsolv-0.7.5/ext/repo_rpmdb_librpm.h:137:55: error: ‘RPMDBI_NAME’ undeclared (first use in this function); did you mean ‘RPMTAG_NAME’?
   ii = rpmdbIndexIteratorInit(rpmtsGetRdb(state->ts), RPMDBI_NAME);
                                                       ^~~~~~~~~~~
                                                       RPMTAG_NAME
/tmp/abf/rpmbuild/BUILD/libsolv-0.7.5/ext/repo_rpmdb_librpm.h:137:55: note: each undeclared identifier is reported only once for each function it appears in
/tmp/abf/rpmbuild/BUILD/libsolv-0.7.5/ext/repo_rpmdb_librpm.h:139:10: warning: implicit declaration of function ‘rpmdbIndexIteratorNext’; did you mean ‘rpmdbInitIterator’? [-Wimplicit-function-declaration]
   while (rpmdbIndexIteratorNext(ii, &key, &keylen) == 0)
          ^~~~~~~~~~~~~~~~~~~~~~
          rpmdbInitIterator
/tmp/abf/rpmbuild/BUILD/libsolv-0.7.5/ext/repo_rpmdb_librpm.h:156:23: warning: implicit declaration of function ‘rpmdbIndexIteratorNumPkgs’; did you mean ‘rpmdbInitIterator’? [-Wimplicit-function-declaration]
       for (i = 0; i < rpmdbIndexIteratorNumPkgs(ii); i++)
                       ^~~~~~~~~~~~~~~~~~~~~~~~~
                       rpmdbInitIterator
/tmp/abf/rpmbuild/BUILD/libsolv-0.7.5/ext/repo_rpmdb_librpm.h:159:38: warning: implicit declaration of function ‘rpmdbIndexIteratorPkgOffset’; did you mean ‘rpmdbGetIteratorOffset’? [-Wimplicit-function-declaration]
          entries[nentries].rpmdbid = rpmdbIndexIteratorPkgOffset(ii, i);
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                      rpmdbGetIteratorOffset
/tmp/abf/rpmbuild/BUILD/libsolv-0.7.5/ext/repo_rpmdb_librpm.h:164:3: warning: implicit declaration of function ‘rpmdbIndexIteratorFree’; did you mean ‘rpmdbInitIterator’? [-Wimplicit-function-declaration]
   rpmdbIndexIteratorFree(ii);
   ^~~~~~~~~~~~~~~~~~~~~~
   rpmdbInitIterator
/tmp/abf/rpmbuild/BUILD/libsolv-0.7.5/ext/repo_rpmdb_librpm.h: In function ‘count_headers’:
/tmp/abf/rpmbuild/BUILD/libsolv-0.7.5/ext/repo_rpmdb_librpm.h:208:37: error: ‘RPMDBI_NAME’ undeclared (first use in this function); did you mean ‘RPMTAG_NAME’?
   mi = rpmtsInitIterator(state->ts, RPMDBI_NAME, NULL, 0);
                                     ^~~~~~~~~~~
                                     RPMTAG_NAME
/tmp/abf/rpmbuild/BUILD/libsolv-0.7.5/ext/repo_rpmdb.c: In function ‘headfromfp’:
/tmp/abf/rpmbuild/BUILD/libsolv-0.7.5/ext/repo_rpmdb.c:1318:7: warning: implicit declaration of function ‘headerImport’; did you mean ‘headerInit’? [-Wimplicit-function-declaration]
   h = headerImport(buf, 8 + len - pad, HEADERIMPORT_FAST);
       ^~~~~~~~~~~~
       headerInit
/tmp/abf/rpmbuild/BUILD/libsolv-0.7.5/ext/repo_rpmdb.c:1318:40: error: ‘HEADERIMPORT_FAST’ undeclared (first use in this function); did you mean ‘HEADER_EXT_LAST’?
   h = headerImport(buf, 8 + len - pad, HEADERIMPORT_FAST);
                                        ^~~~~~~~~~~~~~~~~
                                        HEADER_EXT_LAST
```

Files rpm*compat.h from rpm5 are e.g. here: https://abf.io/soft/rpm5#?path=lib (they did not change in newer RPM5 versions)

All this means that libsolv's support for RPM5 is broken and would better be either fixed or removed...

However, I did not investigate thoroughly whether it is easy to port those functions from rpm4 to rpm5, may be it is not very difficult... and maybe other issues will not occure.

**Comment by Conan-Kudo** [comment]
@mikhailnov Unfortunately, rpm.org rpm (rpm4) is considerably different from rpm5. Many of the APIs and internal structures are _very_ different.

When I was working on porting DNF to OpenMandriva, I had started by trying to get everything working with rpm5. It was very hard... I was not completely successful (though it does kind of work...), but I've [left it all hosted for perusal](https://gitlab.com/rpm5-legacy). Your version of rpm5 looks like the version I was maintaining in OpenMandriva before I gave up, so this code may be of use to you.

Ultimately, distributions that wanted to use DNF migrated to rpm from rpm.org to get there. Both Yocto Project (with Yocto 2.3) and OpenMandriva ([with OpenMandriva Lx 4](https://www.openmandriva.org/en/news/article/switching-to-rpmv4)) did that, and I would advise the same.

If you need help doing the same, let me know. I'd be happy to assist as I can.

**Comment by mikhailnov** [comment]
@Conan-Kudo thank you for the link and sharing experience, I've looked into commits made to libsolv, commit https://gitlab.com/rpm5-legacy/libsolv/commit/eea5159799e661a449a363d54e27f67cf66b273a seems to be the only potentially helpful, but it definitely won't solved compilation errors above.

As for migrating ROSA to RPM 4, it will probably be done, but not exactly now, it's a difficult question, dnf does not have some features of urpmi, for example, but there are some weird issues in rpm5 and perl-URPM/urpmi.

I was investigating the possibility to use e.g. zypper on top of RPM5 (there is no real need for this in fact) and so tried to build libsolv.

**Comment by Conan-Kudo** [comment]
> dnf does not have some features of urpmi

Which features are you missing? Our experience in OpenMandriva was that basically every feature people used was available, and there are some new features you may be interested in (such as [delta repodata fetching with zchunk](https://fedoraproject.org/wiki/Changes/Zchunk_Metadata))

> As for migrating ROSA to RPM 4, it will probably be done, but not exactly now, it's a difficult question

We worked out the kinks of this process fairly well in OpenMandriva, so a transition can probably be done in a matter of weeks. It helps that ROSA Linux is built with ABF, so you can leverage our mdv platform scripts.

**Comment by mikhailnov** [comment]
> so you can leverage our mdv platform scripts

it won't be a problem for fedya :-)

> Which features are you missing?

Well, I don't remember, may be all of them are available and I just didn't know about them. @SergeyDjam said that dnf misses rsync backend but frankly speaking I don't know who and why uses it in urpmi.

**Comment by Conan-Kudo** [comment]
> Well, I don't remember, may be all of them are available and I just didn't know about them. @SergeyDjam said that dnf misses rsync backend but frankly speaking I don't know who and why uses it in urpmi.

As far as we knew in OpenMandriva, no one used the rsync backend. Moreover, it was horrifically expensive for mirrors to deal with, so it was better that we "lost" that feature moving to DNF.

That feature wouldn't exist in Zypper either, so you'd still lose it.

**Comment by mlschroe** [comment]
Can't you just build without ENABLE_RPMDB_LIBRPM/ENABLE_RPMPKG_LIBRPM?

**Comment by termim** [comment]
@mikhailnov  Please take a look at https://abf.rosalinux.ru/build_lists/3035441
It builds fine and its examples seems to work.

**Comment by mikhailnov** [comment]
Disabling ENABLE_RPMDB_LIBRPM and ENABLE_RPMPKG_LIBRPM helped, thanks. Which impact may it have?

**Comment by mlschroe** [comment]
No impact at all (unless rpm5 switches from berkeley db to a different database).
