### ISSUE TITLE
Unable to distinguish requieres  %pre, %post from %preun or %postun

### ISSUE THREAD

**Issue by j-mracek** [openSUSE/libsolv#330]
We use solvable_lookup_deparray(s, SOLVABLE_REQUIRES, &q, 0) to get requires. After marker SOLVABLE_PREREQMARKER we get all %pre, %post %preun or %postun. But even libsolv handles %pre, %post differently from %preun or %postun (%pre, %post could be removed after installation).

Why I have an interest in that?
1. We use the information for dnf check command to check that installed packages have all dependencies fulfilled - https://bugzilla.redhat.com/show_bug.cgi?id=1543449

2. We got a request to allow an automatic removal of packages that are not required for run-time - https://bugzilla.redhat.com/show_bug.cgi?id=1381332

Not sure if we use the correct approach or looking at the correct direction, but any information is welcome.

**Comment by mlschroe** [comment]
Libsolv has the SOLVABLE_PREREQ_IGNOREINST idarray which contains the ids that are safe to ignore for installed solvables.

**Comment by j-mracek** [comment]
@mlschroe Thanks, I will try to use it
