### ISSUE TITLE
Document keyname constants in the binding documentation

### ISSUE THREAD

**Issue by dralley** [openSUSE/libsolv#333]
e.g.  ```solv.SOLVABLE_REQUIRES```, ```solv.SOLVABLE_RECOMMENDS```, ```solv.SOLVABLE_PROVIDES``` and so forth

I know that they exist because I've seen code that uses them, but if I hadn't, I wouldn't have any idea what "keyname" means in the binding documentation.  As far as what they do, you can just defer to a document such as https://rpm.org/user_doc/dependencies.html

**Comment by mlschroe** [comment]
From the fine man page:
```
*ID_NULL*::
Always zero 

*ID_EMPTY*::
Always one, describes the empty string

*SOLVABLE_NAME*::
The keyname Id of the name of the solvable.

*...*::
see the libsolv-constantids manpage for a list of fixed Ids. 

```

Isn't that enough?

**Comment by dralley** [comment]
I suppose
