### ISSUE TITLE
Question: creating dependencies

### ISSUE THREAD

**Issue by kevinkwl** [openSUSE/libsolv#338]
Hi all,

Recently I've been trying to implement a package resolver with libsolv python-binding. I use the `add_deparray` method to attach dependency to a solvable package. Just notice that I can specify the dep id using `str2id`
```python
a.add_deparray(solv.SOLVABLE_REQUIRES, pool.str2id('B'))

a.add_deparray(solv.SOLVABLE_REQUIRES, pool.rel2id(pool.str2id('D'), pool.str2id('1.1.0'), solv.REL_EQ | solv.REL_LT))
```
Does the `str2id` way gives a valid dependency id, a requirement on package **B** with any version? (in my test, it did.)

Correct me if I'm wrong, I found out that the str ids and rel ids are generated independently, how does the solver know whether a depId is generated from str or rel?

Some advice on reading the libsolv source code would be appreciating!

**Comment by mlschroe** [comment]
Yes, the id returned by str2id() can be used for dependencies. rel ids have the 31th bit set, so there is no conflict.
