### ISSUE TITLE
Libsolv upgrade to older package

### ISSUE THREAD

**Issue by j-mracek** [openSUSE/libsolv#342]
There is a difference in behaviour of `job update oneof` and `job update all packages `. 
`job update all packages ` do not check build time at all and installs (upgrade) only packages with higher nevra.
`job update oneof` is able to install changed rpms, that could result in installing older rpm that is present on the system (downgrade).
I see here two issues:
1. `job update oneof` is capable to perform downgrade (package with same nevra but older).
2. `job update all packages ` and `job update oneof` behave differently

Please could be behaviours unified?
```
repo @System 0 testtags <inline>
#>=Pkg: testpkgpostun 1.0 1 noarch
#>=Prv: testpkgpostun = 1.0-1
#>=Tim: 1564501905

repo old 0 testtags <inline>
#>=Pkg: testpkgpostun 1.0 1 noarch
#>=Prv: testpkgpostun = 1.0-1
#>=Tim: 1564501818

system x86_64 rpm @System
poolflags implicitobsoleteusescolors
solverflags allowvendorchange keepexplicitobsoletes bestobeypolicy keeporphans yumobsoletes
job update oneof testpkgpostun-1.0-1.noarch@old
#job update all packages
#job update repo old

result transaction,problems <inline>
```

**Comment by j-mracek** [comment]
Also the problem is valid for `job update repo old [forcebest]`

**Comment by mlschroe** [comment]
I think what you're seeing is just the difference between 'targeted' and 'untargeted' updates. See the  section about targeted updates in the libsolv-bindings manpage about more information.

**Comment by mlschroe** [comment]
See issue #287

**Comment by j-mracek** [comment]
@mlschroe In past dnf uses un-targeted targed for `dnf upgrade` and targeted for `dnf upgrade foo`. We discovered that there were differences and users do not expect a different behavior for the same command. I would expect that commands `dnf upgrade` and `dnf upgrade '*'` should provide the same behavior. But as you mentioned above this is intended behavior and it means that DNF team is in dead end. In this particular case we want to have behavior of untargeted updates but how to provide it for `dnf upgrade foo`?

**Comment by mlschroe** [comment]
You're not in a dead end, you have to add the installed package to the update set if you want to allow that it is kept. See issue #287. You're telling the solver to update the package to the specified set and then complain if it fulfills your request.

If you want untarget mode you just need to select the installed package instead of specifying a set.

(According to James Antill this is exactly how yum worked in the past, btw.)

**Comment by j-mracek** [comment]
In case 
```repo @System 0 testtags <inline>
#>=Pkg: testpkgpostun 1.0 1 noarch
#>=Prv: testpkgpostun = 1.0-1
#>=Tim: 1564501905

repo old 0 testtags <inline>
#>=Pkg: testpkgpostun 1.0 1 noarch
#>=Prv: testpkgpostun = 1.0-1
#>=Tim: 1564501818

system x86_64 rpm @System
poolflags implicitobsoleteusescolors
solverflags allowvendorchange keepexplicitobsoletes bestobeypolicy keeporphans yumobsoletes
<job>
result transaction,problems <inline>
```

`job update oneof testpkgpostun-1.0-1.noarch@old` behaves same like 
`job distupgrade all packages` or `job distupgrade oneof testpkgpostun-1.0-1.noarch@old`. But only `job update all packages` differently.

The `distupgrade` is more powerful because it allow even downgrade, but `update` skips by default broken updates and only updates.

I am also looking for a  definition for what update means. @mlschroe, @Conan-Kudo, @ignatenkobrain   What about :
1. Packages with higher NEVRA? - This is without a discussion
2. Obsoletes when it is allowed? - Also clear
3. Packages with same NEVRA, but that differs?
   But it requires to exactly define what is the upgrade path and what not to prevent from jumping between packages with the same NEVRA and different buildtime according to what repo was loaded first. Also there is a question whatever packages with same NEVRA but different should be handled by `distupgrade` exclusively.

**Comment by j-mracek** [comment]
> You're not in a dead end, you have to add the installed package to the update set if you want to allow that it is kept. See issue #287. You're telling the solver to update the package to the specified set and then complain if it fulfills your request.
> 
> If you want untarget mode you just need to select the installed package instead of specifying a set.
> 
> (According to James Antill this is exactly how yum worked in the past, btw.)

I am sorry I provided wrong command example. DNF allows to use argument like `dnf upgrade foo-1.*-5.*`. In this case providing installed package with available packages results in ignoring pre-selected available packages.
installed - foo-1.4-5.1.noarch
available - foo-1.4-5.2.noarch, foo-1.4-5.3.noarch, foo-2.4-6.1.noarch.
- Untargeted update results in upgrade to foo-2.4-6.1.noarch.

What we also cannot do is to filtrate out the same NEVRAs with installed packages from targeted updates because it destroys honoring of priority repos.

**Comment by mlschroe** [comment]
Ok, I understand that you don't want untarget mode in that case. So why does `foo-1.*-5.*` not match the installed package? I.e. why is the installed package not in the set of packages given to the update job?

**Comment by mlschroe** [comment]
Don't you use the `SOLVER_TARGETED` flag?

**Comment by j-mracek** [comment]
> Ok, I understand that you don't want untarget mode in that case. So why does `foo-1.*-5.*` not match the installed package? I.e. why is the installed package not in the set of packages given to the update job?

We remove all installed packages from a query before providing packages to solver. Not sure if this is the best way.

> Don't you use the `SOLVER_TARGETED` flag?

We do not use `SOLVER_TARGETED` at all. We let solver to use auto-detection targeted/untargeted.

After weekend I can prepare a flag for solver job update that change a detection of identical rpms. The present behavior would be a default (no flag). And the flag will be selectively use on our side without any harm to anyone else. @mlschroe What do you think?

**Comment by mlschroe** [comment]
Please do not patch libsolv. It does exactly what it is told to do. Please use `SOLVER_TARGETED` if you want to provide a set of packages as update target.

Just do not remove the installed packages from the query and add `SOLVER_TARGETED`. That way it'll work exactly like you expect.

**Comment by mlschroe** [comment]
OTOH maybe you should just not remove the installed packages and let the solver switch between targeted/untargeted behavior. That means `dnf upgrade foo-1.*-5.*` will upgrade `foo-1.4-5.1.noarch` to `foo-2.4-6.1.noarch` like you said, but that's also what yum did if I understood James correctly. So maybe it's not a bad thing at all. (You may want to double-check if this is correct.)

Basically there's no way to know the user's intent for the operation.

**Comment by j-mracek** [comment]
@mlschroe I am going to make an investigation how behaves yum and during the next week I will provide additional data.

**Comment by mlschroe** [comment]
ok, thanks. If you decide you always want "targeted", you should not filter out the installed packages but instead set the `SOLVER_TARGETED` flag.

**Comment by j-mracek** [comment]
I did a small investigation with `yum` and `dnf`. The first difference is that there are several upgrade commands in yum and each with a different behavior, but dnf have one command with many aliases. Command are `update`, `upgrade`, `upgrade-to`.
I used following packages:
```
testpkg-0:1.0-1.noarch - installed, available
testpkg-0:1.1-1.noarch - available
testpkg-0:1.1-2.noarch - available
testpkg-0:2.0-2.noarch - available
```
`yum-deprecated update-to testpkg-1*-1` -> upgrade to `testpkg-0:1.1-1.noarch`
`yum-deprecated update testpkg-1*-1` -> upgrade to `testpkg-0:2.0-2.noarch`
`yum-deprecated update` -> upgrade to `testpkg-0:2.0-2.noarch`

Because DNF has one behavior for upgrade commands I would prefer to use the behavior of `yum upgrade-to` -> targeted transaction in libsolv. I suggest that majority of users always want to upgrade to when they use an argument with version-release like `testpkg-1*-1`.

I also test yum with testcase presented above
```
repo @System 0 testtags <inline>
#>=Pkg: testpkgpostun 1.0 1 noarch
#>=Prv: testpkgpostun = 1.0-1
#>=Tim: 1564501905

repo old 0 testtags <inline>
#>=Pkg: testpkgpostun 1.0 1 noarch
#>=Prv: testpkgpostun = 1.0-1
#>=Tim: 1564501818
```
YUM always take as an upgrade packages with higher NEVRA than installed package, therefore for packages with same NEVRA it result in ```No packages marked for update```.

@mlschroe I would like to ask you to suggest a way how to deliver behavior of targeted update transaction without upgrading to modified packages with the same NEVRA? Upgrading to packages with same NEVRA but newer build time is still explainable to customers. But explanation of upgrading to older packages would be too difficult.

**Comment by mlschroe** [comment]
[back from vacation]

But people will be surprised if 'dnf update testpkg' is suddenly targeted. You really need to offer a command line option instead of doing guesses by looking at the argument.

Regarding your second question: same NEVRA will not be a problem if the installed package is not filtered out of the job's package set. So just remove the code that does that.
It's dnf that decideds what package is included in the set when you do a targeted update, not libsolv.

**Comment by j-mracek** [comment]
@mlschroe Thanks a lot, marking transaction as targeted resolved the issue.
