### ISSUE TITLE
Upgrade of multiversion package from repository with lower priority

### ISSUE THREAD

**Issue by m-blaha** [openSUSE/libsolv#343]
Hi,

in dnf we came across a problem with unwanted upgrade of a multiversion package from repository with lower priority: [BZ#1733582](https://bugzilla.redhat.com/show_bug.cgi?id=1733582). The upgrade should not occur and the installed package should stay on the version available in the prioritized repository.

All these three conditions must be met for the problem to occur:
1. use [forcebest] flag for update job
2. package must be multiversion
3. installed package has lower version and came from repository with higher priority. Potential updates are available in lower priority repos

Here is the testcase to easily reproduce the issue:

```
repo system 0 testtags <inline>
#>=Pkg: k 1 0 x86_64

repo lower_priority 1 testtags <inline>
#>=Pkg: k 2 0 x86_64

repo higher_priority 2 testtags <inline>
#>=Pkg: k 1 0 x86_64

system x86_64 rpm system

job multiversion provides k
job update all packages [forcebest]

result transaction,problems <inline>
#>install k-2-0.x86_64@lower_priority
```

**Comment by mlschroe** [comment]
Nasty. Commit 927d72598ace6108b55dccd7ec452438b5bcfd2c fixes this, but I'm not 100% happy with it. There's also an underlying problem with the way libsolv generates forcebest rules that this test case uncovered.

**Comment by m-blaha** [comment]
Some problem still remains. The dnf bug reporter tried your patch with partial success - worked on one machine, didn't work at the other. I looked into his solver testcase and finally was able to come up with this reproducer which still installs package from repository with lower priority:

```
repo system 0 testtags <inline>
#>=Pkg: kernel-core 4.19 1 x86_64
#>=Pkg: kernel-core 4.18 1 x86_64
#>=Pkg: kernel-core 4.17 1 x86_64

repo high-priority-3 3 testtags <inline>
#>=Pkg: kernel-core 4.18 1 x86_64
#>=Pkg: kernel-core 4.19 1 x86_64

repo low-priority-1 1 testtags <inline>
#>=Pkg: kernel-core 5.20 1 x86_64

system x86_64 rpm system
job update all packages [forcebest]
job multiversion provides kernel-core
result transaction,problems <inline>
```

The problem is caused by kernel-core-4.17 in `system` repo, which is installed but is not available in any repo. Interestingly the order of packages in `system` repo matters - if I move the kernel-core-4.17 up, the problem disappears...

**Comment by mlschroe** [comment]
Yeah, I didn't think that one through. The last commit should be much better.

The current fix is just a good workaround. When I'm back from vacation I need to change the way the update candidate for multiversion packages is calculated. Plus I need to fix the way the "forcebest" rules are generated.
