### ISSUE TITLE
namespace provider callback missing

### ISSUE THREAD

**Issue by lnussel** [openSUSE/libsolv#349]
Following up on
https://github.com/openSUSE/libsolv/issues/231#issuecomment-358631744

it seems the namespace callback is still missing

**Comment by mlschroe** [comment]
I don't see the need. You've got `pool.set_namespaceproviders` and `pool.flush_namespaceproviders`.

**Comment by lnussel** [comment]
I just got reminded because of this: https://github.com/openSUSE/openSUSE-release-tools/blob/master/pkglistgen/tool.py#L169

I believe the callback would make that code less crappy :)

**Comment by lnussel** [comment]
permalink is probably better for later: 
https://github.com/openSUSE/openSUSE-release-tools/blob/master/pkglistgen/tool.py#L169

**Comment by lnussel** [comment]
https://github.com/openSUSE/openSUSE-release-tools/blob/514a0f5ea1c10f708f188bf5b5a4488b1121dc63/pkglistgen/tool.py#L169
