### ISSUE TITLE
libsolv assumes Berkeley DB rpmdb paths

### ISSUE THREAD

**Issue by pmatilai** [openSUSE/libsolv#354]
I thought the BDB assumptions got fixed by the librpm patches, but seems there's at least one more obstacle left in ext/repo_rpmdb.c / stat_database():

```
  /* XXX: should get ro lock of Packages database! */
  if (stat_database(&state, "Packages", &packagesstat, 1))
    {
      freestate(&state);
      return -1;
    }
```

This causes repo_add_rpmdb() to  fail on any non-BDB rpmdb backend, so it's a bit of a blocker... Incidentally this very same blocker check exists in libdnf too (https://github.com/rpm-software-management/libdnf/issues/362)

I plan to add an rpmdbStat() call to librpm, but I guess libsolv will want its own solution in addition.

**Comment by mlschroe** [comment]
Worked around with commit ea037722b0f2a1afc8416e08b36fd498a8bb14c4. Bah.

**Comment by pmatilai** [comment]
I do agree it's ugly :D but it does work. Thanks.
