### ISSUE TITLE
Upgrades of multiversion packages are handled inconsistently

### ISSUE THREAD

**Issue by j-mracek** [openSUSE/libsolv#364]
There is a difference between targeted and un-targeted upgrade jobs for multiversion packages. In case that available version is not higher than the latest installed package but higher then other installed packages un-targeted job correctly do not consider it for the upgrade, but targeted job installs `kernel-3.0-1.x86_64@updates`. See test case bellow. I would expect the same behaviour for all jobs in the test case.

See also https://bugzilla.redhat.com/show_bug.cgi?id=1720586.

```
repo @System 0 testtags <inline>
#>=Pkg: kernel 1.0 1 x86_64
#>=Prv: kernel = 1.0-1
#>=Pkg: kernel 2.0 1 x86_64
#>=Prv: kernel = 2.0-1
#>=Pkg: kernel 4.0 1 x86_64
#>=Prv: kernel = 4.0-1

repo updates 0 testtags <inline>
#>=Pkg: kernel 3.0 1 x86_64
#>=Prv: kernel = 3.0-1


system x86_64 rpm @System
poolflags implicitobsoleteusescolors

solverflags allowvendorchange keepexplicitobsoletes bestobeypolicy keeporphans yumobsoletes
job multiversion provides kernel
job update oneof kernel-1.0-1.x86_64@@System kernel-2.0-1.x86_64@@System kernel-4.0-1.x86_64@@System kernel-3.0-1.x86_64@updates [targeted,setevr,setarch]
#job update oneof kernel-1.0-1.x86_64@@System kernel-2.0-1.x86_64@@System kernel-4.0-1.x86_64@@System kernel-3.0-1.x86_64@updates [targeted,setevr,setarch,forcebest]
#job update all packages [forcebest]
#job update all packages

result transaction,problems <inline>
```

**Comment by mlschroe** [comment]
This should now be fixed. Thanks for the report!

(Multiversion is a pain to get correct!)

**Comment by j-mracek** [comment]
@mlschroe Thanks a lot.
