### ISSUE TITLE
Bogus problem report - requirement attributed to wrong package

### ISSUE THREAD

**Issue by m-blaha** [openSUSE/libsolv#367]
Sometimes libsolv returns bogus problems probably when rich dependencies are used. Here is minimal reproducer:

Let's have the testcase.t file with following contents:
```
repo @System 0 testtags <inline>
#>=Pkg: mpich 3.3.2 1.fc31 x86_64
#>+Req:
#>python(abi) = 3.7 <IF> python3
#>-Req:
#>=Pkg: python3 3.7.6 2.fc31 x86_64
#>+Prv:
#>python(abi) = 3.7
#>python3 = 3.7.6-2.fc31
#>-Prv:

repo p38 0 testtags <inline>
#>=Pkg: python3 3.8.0~b4 1.fc32 x86_64
#>+Prv:
#>python(abi) = 3.8
#>python3 = 3.8.0~b4-1.fc32
#>-Prv:

system x86_64 rpm @System

poolflags implicitobsoleteusescolors whatprovideswithdisabled
solverflags allowvendorchange keepexplicitobsoletes bestobeypolicy keeporphans yumobsoletes

job update oneof python3-3.7.6-2.fc31.x86_64@@System python3-3.8.0~b4-1.fc32.x86_64@p38 [forcebest]
```

```
$ testsolv testcase.t 
Found 1 problems:
Problem 1:
package python3-3.8.0~b4-1.fc32.x86_64 requires (python(abi) = 3.7 if python3), but none of the providers can be installed

Solution 1:
  - allow deinstallation of mpich-3.3.2-1.fc31.x86_64

Solution 2:
  - keep old python3-3.7.6-2.fc31.x86_64
```
The problem is reported for package  `python3` but this package does not have the requirement and the problem should be reported for `mpich` package.
If you change the order of `@System` and `p38` repositories in the testsolv.t file, the problem disappears.

Corresponding dnf bug: https://bugzilla.redhat.com/show_bug.cgi?id=1729465

**Comment by mlschroe** [comment]
Oh wow. Thanks for the report!

**Comment by m-blaha** [comment]
Thanks for quick fix! With the latest upstream libsolv I'm not able to reproduce the original bug.
