### ISSUE TITLE
disturl tags missing

### ISSUE THREAD

**Issue by lnussel** [openSUSE/libsolv#369]
I can't find any reference to disturl tags in libsolv. So when looking at solv file the link to the actual sources in OBS is lost compared to when looking at rpms directly.

**Comment by mlschroe** [comment]
There are not in the repository metadata.

**Comment by mlschroe** [comment]
s/There/They/

**Comment by mlschroe** [comment]
Or is that supposed to be something buildservice specific? Then you probably should open a bug against OBS.

**Comment by lnussel** [comment]
rpms2solv involves neither repomd nor OBS :) Not having that data in repomd is yet another issue.

**Comment by lnussel** [comment]
Short of disturl is there any other way to find the way back to obs given a binary rpm? Look at the source rpm and make a good guess?

**Comment by mlschroe** [comment]
Don't open issues in libsolv if you want something for OBS!

**Comment by mlschroe** [comment]
OBS doesn't even call rpms2solv.

**Comment by lnussel** [comment]
heh, the fact that libsolv doesn't map a perfectly valid rpm tag has nothing to do with OBS.

**Comment by mlschroe** [comment]
Libsolv maps all the tags it needs for solving dependency. Plus some tags needed for libzypp. Don't tell me you want it to map all known rpm tags? How about RPMTAG_BUILDHOST? Or RPMTAG_COOKIE? Or RPMTAG_PAYLOADCOMPRESSOR? RPMTAG_PLATFORM? RPMTAG_DISTTAG? RPMTAG_BUGURL (whatever that is)? RPMTAG_ENCODING?

**Comment by mlschroe** [comment]
It basically maps (almost) everything that is in the repository metadata. It doesn't map everything that is in local rpms because that's not the focus of libsolv.

**Comment by mlschroe** [comment]
And it would be really good to know your use case...

**Comment by Conan-Kudo** [comment]
I'd probably argue it doesn't need to map RPMTAG_DISTURL to begin with...

**Comment by lnussel** [comment]
`ext/repo_rpmdb.c:#define TAG_BUILDHOST          1007
src/knownid.h:KNOWNID(SOLVABLE_BUILDHOST,   "solvable:buildhost"),
`
ie libsolv knows about buildhost which is certainly one of the less useful tags, that's why I wondered :-) disturl is slightly more relevant, at least for SUSE distros.

The reason I ran into this is https://github.com/lnussel/websolv where I wanted to add a link for humans to quickly jump to the sources in order to take a look at spec files.

**Comment by mlschroe** [comment]
But the SOLVABLE_BUILDHOST is actually not used anywhere. Seems like we should delete it the next time we break the ABI.

Regarding websolv, its main usage seems to be to display data from the repositories, which currently does not contain the disturl...

**Comment by lnussel** [comment]
are you saying that if createrepo_c would add the disturl you'd include it in libsolv? If so I'll file an issue there.

**Comment by mlschroe** [comment]
The chances are much better, yes. But this will probably only be an option for createrepo_c, as the disturl makes the repodata somewhat bigger. And then you'll need to convince the obs folks to use that option when publishing a project.

**Comment by Conan-Kudo** [comment]
@mlschroe The reason `SOLVABLE_BUILDHOST` is there is because rpm-md includes that data.

**Comment by mlschroe** [comment]
I added it in commit 5931c40683bba9ef4cb98de314d8449b8c3fe342, but it was never set. Weird.
