### ISSUE TITLE
Is there a solv flag to meet dependencies from packages installed on a system rather than installing a new package

### ISSUE THREAD

**Issue by keerthanakalyan** [openSUSE/libsolv#370]
If a spec contains Requires: with or of multiple packages, lilbsolv always tries to solve the dependencies in alphabetical order rather than checking what is already installed on the machine. Consider below example:

Package X has below Requires:

Requires: ABC-D | ABC-A-D | ABC-B-D

When Libsolv tries to resolve dependencies for package X, it always tries to install package ABC-A-D even though package ABC-D is already installed on the machine. 
Do we have any libsolv flags to resolve this issue. Please suggest.

**Comment by ignatenkobrain** [comment]
Please provide testcase for this, libsolv should already do it this way.

**Comment by keerthanakalyan** [comment]
We are using libsolv for TDNF in Photon OS, where we have a package named photon-checksum-generator which has the following Requires in spec file:

Requires:        (linux-hmacgen or linux-secure-hmacgen or linux-aws-hmacgen or linux-esx-hmacgen)

Each linux hmacgen flavor internally Requires its linux base package.
linux-hmacgen -(Req)- linux
linux-secure-hmacgen -(Req)- linux-secure
linux-aws-hmacgen -(Req)- linux-aws
linux-esx-hmacgen -(Req)- linux-esx

you can refer the spec files here:

https://github.com/vmware/photon/blob/3.0/SPECS/photon-checksum-generator/photon-checksum-generator.spec
https://github.com/vmware/photon/blob/3.0/SPECS/linux/linux.spec
https://github.com/vmware/photon/blob/3.0/SPECS/linux/linux-aws.spec

When TDNF resolves dependencies it always tries to install linux-aws and linux-aws-hmacgen even though linux is already installed on the system.

Below snippet is the debugdata from solver:

repo @System 0 testtags @System.repo.gz
repo photon-extras 0 testtags photon-extras.repo.gz
repo test 0 testtags test.repo.gz
repo photon-updates 0 testtags photon-updates.repo.gz
repo photon 0 testtags photon.repo.gz
repo photon-debuginfo 0 testtags photon-debuginfo.repo.gz
system x86_64 rpm @System
poolflags forbidselfconflicts obsoleteusesprovides implicitobsoleteusesprovides havedistepoch noobsoletesmultiversion addfileprovidesfiltered
solverflags allowdowngrade allowvendorchange bestobeypolicy keeporphans yumobsoletes installalsoupdates
job install pkg photon-checksum-generator-1.0-1.ph3.x86_64@photon-updates
result transaction,problems solver.result

**Comment by ignatenkobrain** [comment]
You need to attach those files too.

**Comment by keerthanakalyan** [comment]
Attaching the debug data of solver




[debugsolver.zip](https://github.com/openSUSE/libsolv/files/4305038/debugsolver.zip)

**Comment by keerthanakalyan** [comment]
@ignatenkobrain : Any update on this? Thank you.

**Comment by Conan-Kudo** [comment]
@keerthanakalyan This is not a useful debugsolver test bundle. It's missing too much stuff.

```
$ testsolv -v testcase.t
testcase_read: could not open '@System.repo.gz'
testcase_read: could not open 'photon-extras.repo.gz'
testcase_read: could not open 'test.repo.gz'
testcase_read: could not open 'photon-updates.repo.gz'
testcase_read: could not open 'photon.repo.gz'
testcase_read: could not open 'photon-debuginfo.repo.gz'
```

**Comment by keerthanakalyan** [comment]
@Conan-Kudo Apologies for the files missing. Re-attaching the files. Thanks
[@System.repo.gz](https://github.com/openSUSE/libsolv/files/4329319/%40System.repo.gz)
[photon-extras.repo.gz](https://github.com/openSUSE/libsolv/files/4329321/photon-extras.repo.gz)
[photon-updates.repo.gz](https://github.com/openSUSE/libsolv/files/4329322/photon-updates.repo.gz)

[solver-testcase.zip](https://github.com/openSUSE/libsolv/files/4329331/solver-testcase.zip)

**Comment by mlschroe** [comment]
I don't see anything wrong:

photon-checksum-generator requires linux-hmacgen | linux-secure-hmacgen | linux-aws-hmacgen | linux-esx-hmacgen
None of those is installed. Libsolv chooses linux-aws-hmacgen (because it is the lexicographic first).

linux-aws-hmacgen in turn requires linux-aws. So that package is also installed.

**Comment by mlschroe** [comment]
Oh wait. I think I understand what you mean. You want "linux-hmacgen" instead. Well, for the solver those are just alternatives, none is better. It cannot know that there can be only one linux running.

I guess that you don't want the kernel packages to conflict, so you'll need to provide some hint to the solver that it is better to install a package matching the kernel.

You can do this by adding an "Enhances" dependency to each hmac package. I.e. the linux-hmacgen package should contain `Enhances: kernel`.

**Comment by keerthanakalyan** [comment]
@mlschroe: Thanks much for looking into this. Your suggestion of adding `Enhances: linux` works.
