### ISSUE TITLE
Prevent erasure/uninstallation of specific provide/package?

### ISSUE THREAD

**Issue by waddlesplash** [openSUSE/libsolv#382]
`SOLVER_ALLOWUNINSTALL` is a whitelist (i.e. allow only those packages to be uninstalled), and there is a global flag to allow any package to be uninstalled; but is there any way to allow uninstallation of any package *except* for a given set? I.e. any solution or request to uninstall those packages should be considered invalid, but they may be freely upgraded/downgraded/etc.

**Comment by ignatenkobrain** [comment]
I think you can SOLVER_VERSIONLOCK, but I did not test it.

**Comment by waddlesplash** [comment]
Won't that also prevent upgrading the package?

**Comment by ignatenkobrain** [comment]
Ah, now I understand what you want. I think beat way is to create jobs for all packages you can afford uninstalling . Check tests/allowuninstall examples.

**Comment by waddlesplash** [comment]
Yes, but what if requesting the uninstall of one package indirectly would cause the uninstall of one of the packages we do not want uninstalled?

**Comment by waddlesplash** [comment]
Specifying every package currently installed except for the ones we do not in ALLOW UNINSTALL seems rather inefficient...

**Comment by ignatenkobrain** [comment]
> Yes, but what if requesting the uninstall of one package indirectly would cause the uninstall of one of the packages we do not want uninstalled?

You will get an error from `solver_solve()`.

> Specifying every package currently installed except for the ones we do not in ALLOW UNINSTALL seems rather inefficient...

I think this is how DNF does it and I think it works quite fast.

**Comment by mlschroe** [comment]
With current libsolv I see two possibilities:
- add  SOLVER_ALLOWUNINSTALL jobs for each installed package not in your set
  (this does not slow down solving as each job just sets a bit in a bitmask)
- add SOLVER_INSTALL|SOLVER_NAME|SOLVER_ESSENTIAL for the package names you want to protect

The second way makes sure that a package with that name is installed after the transaction. The downside of the second way is that it does not work with package renames. I'm not sure if this is a problem for Haiku, though.

**Comment by waddlesplash** [comment]
```SOLVER_INSTALL|SOLVER_NAME|SOLVER_ESSENTIAL```

If that package is already installed, and a newer version is available, does this mean it will be upgraded even if the user did not request it? If not, that sounds like what I need.

> I'm not sure if this is a problem for Haiku, though.

Well, I want to use this specifically for the base system package, so it's not.

**Comment by mlschroe** [comment]
If you don't turn on the `SOLVER_FLAG_INSTALL_ALSO_UPDATES` flag it should not update.
