### ISSUE TITLE
How to copy some selected Solvables into a higher prio repo?

### ISSUE THREAD

**Issue by wolfv** [openSUSE/libsolv#385]
Hi,
for mamba I am trying to copy some selected Solvables from one repo to another. 
The other repo is supposed to have the highest priority, so that the solvable will always be taken from this "special" repo. This is to support a use case where someone installs a package using the `somechannel::python` package, where python should be installed from `somechannel` but the other packages from `somechannel` should remain low-priority.

I have some code which works _3 out of 4 times_, but sometimes I get spurious asserts in solver.c, specifically 

`Line 725: assert(idx > 0);`
`Line 758: assert(rlevel > 0 && rlevel < level);`

I was wondering if you can spot some obvious issue here: https://github.com/QuantStack/mamba/blob/b5cfa9fc738b4b3c74bcf94da5dbc6b073378b5e/src/solver.cpp#L134

**Comment by ignatenkobrain** [comment]
You basically need to create new solvable and copy all relevant attributes. Unfortunately there is no such thing as copy solvable :)

**Comment by ignatenkobrain** [comment]
my guess would be that you are not copying strings, but rather use same pointers and that is not going to work/

**Comment by wolfv** [comment]
I am not sure that this is the problem as I am mostly copying IDs that should be in the string pool (at least that's how I understand it, and `repodata_set_str(...)` internally copies the char buffer. But I'll check again. Indeed a copy_solvable function would be very useful. I found some stuff in 

https://github.com/openSUSE/libsolv/blob/33adcd1f21b2426aa06716f7915c63a5aefb644b/ext/repo_rpmdb.c#L1453-L1475

But it looks more complicated vs what I want.

**Comment by wolfv** [comment]
hmm i switched to using what I found in rpmdb 

https://github.com/wolfv/mamba/blob/4cd706ecd34feb59ac5eedcc42c9455c47167de4/src/solver.cpp#L176-L183

and copy the keys like that. 

Still have the same issue unfortunately. I did observed that some retrieved strings from the Solvable attributes were nullptr, indeed. But I don't understand why, as I do set them and I believe that the char string is copied in `repodata_set_str`.

Any hints would be very appreciated. This would be an awesome feature to add to mamba!

**Comment by wolfv** [comment]
ok I can reproduce the error when loading the channel from where packages should be lifted from JSON, but not if I am loading the channel from a `.solv` file. So maybe somewhere there is a slight difference in memory handling :)

**Comment by wolfv** [comment]
I think the code posted above works, but I am initializing the solver before adding this repo to the pool leading to some inconsistencies.

**Comment by wolfv** [comment]
This code implements the functionality and seems to work well when initializing the solver afterwards instead of before :)

https://github.com/QuantStack/mamba/blob/3a5673e9b25441a7a9e6a1df0fc89bf18a470165/src/solver.cpp#L99-L193

**Comment by mlschroe** [comment]
Hmm, I very much doubt that copying solvables around is a good idea. What exactly is it you want to do?

**Comment by mlschroe** [comment]
I think this is about using the correct channel repo if the install spec contains a channel name. But wouldn't it be better to change the job so that it only contains packages from the specified channel?

You can do this by using SOLVER_SOLVABLE_ONE_OF with a set of package ids instead of the SOLVER_SOLVABLE_PROVIDES you currently use.

i.e:
```
<filter packages into queue q>
Id d = pool_queuetowhatprovides(pool, &q);
queue_push2(&m_jobs, job_flag | SOLVER_SOLVABLE_ONE_OF, d);

```

The solver internally works with sets of packages anyway. The SOLVER_SOLVABLE_... mechanism is just multiple ways to specify such sets.

**Comment by wolfv** [comment]
Yeah, this looks exactly like what I need! Thanks!
