### ISSUE TITLE
Lock package without installing

### ISSUE THREAD

**Issue by wolfv** [openSUSE/libsolv#388]
I am wondering if it is possible to lock a certain package, without it being installed.

E.g. if I have two variants of a package that depend on boost, one variant boost =1.70, and the other boost =1.72, then is it possible to add a LOCK command to the solver so that it e.g. only selects packages with `boost =1.70` as dependency?

One way I could do this in the conda-context would probably be if I add a meta-package with constrains and no other alternatives for installation.

**Comment by mlschroe** [comment]
`SOLVER_LOCK boost !=1.70` should work (that is, if there is no boost != 1.70 package installed).

A lock basically says: keep the state of the package. I.e. uninstalled packages stay uninstalled, installed packages stay installed.

Note that locks are hard, if you just want to _prefer_ a package version you can do this with:

`SOLVER_FAVOR boost =1.70`

**Comment by wolfv** [comment]
Thanks, very good to know!
