### ISSUE TITLE
Properly force reinstall

### ISSUE THREAD

**Issue by wolfv** [openSUSE/libsolv#390]
I am wondering how to properly reinstall a package. 

I had the intuitive idea that `api.SOLVER_INSTALL | api.SOLVER_ERASE` might work, but I can't seem to make libsolv uninstall, and install the package yet. 

Any tips on how to do this cleanly?

**Comment by ignatenkobrain** [comment]
hmm, why does libsolv needs to handle that? I mean, it won't change dependencies or anything like that.

**Comment by wolfv** [comment]
the way it is with `conda` right now is that you can add `--force-reinstall` to an install command, and _if_ the package already exists, it will reinstall, otherwise it will install. 

In that case, e.g. if you have `python` installed, and you add another package (`python-flask`) which is not installed, the reinstallation of python would need to occur in the right order:

- remove python
- install python
- install python-flask

that's why it would be great to have the reinstall as part of the solve process. But if that doesn't exist, the options I see are:

- remove the package to be installed from the installed repo, and reinstall with the version pinned
- handle reinstall in some sort of post-process step

Both are less cool then adding a job for `SOLVER_REINSTALL`, and the Transaction class seems to be aware of reinstallations as well, but I can't find how to generate one :)

**Comment by ignatenkobrain** [comment]
> Both are less cool then adding a job for SOLVER_REINSTALL, and the Transaction class seems to be aware of reinstallations as well, but I can't find how to generate one :)

IIRC, those just use `solvable_identical()` when they have same name and EVR.

**Comment by mlschroe** [comment]
You can force a recinstall if you modify your job so that it no longer includes the installed package. So it's kind of similar to your other use case where you want a package from a specific channel.

**Comment by wolfv** [comment]
you mean kick out the package from the installed repo?

**Comment by wolfv** [comment]
ok, I _think_ I got it, trying now. The way I understand what you're saying is to use SOLVABLE_SET_ONE_OF and then select the solvable I want (which does not come from the `installed` repo).

**Comment by wolfv** [comment]
Hm, 
when I solvable_free(old_pkg) it attempts to install the new one, that's good. 
But I also need the previous one to be deleted. I tried to add the same job for the package in the installed repo:

```
queue_init(q1);
queue_push(q1, pkg_id);
Id d2 = pool_queuetowhatprovides(pool, q1);
queue_push2(&m_jobs, SOLVER_ERASE | SOLVER_SOLVABLE_ONE_OF, d2);
```

But then there is 0 elements in the transaction.

The debug output is:

```
pkg rule memory used: 72005 K
pkg rule creation took 790 ms
job: install providing python 3.7.6
  - job Rule #3072911:
    python-3.7.6-h8356626_5_cpython [228]I (w1)
    python-3.7.6-cpython_h8356626_6 [67934] (w2)
    python-3.7.6-cpython_he5300dc_6 [67935]
    python-3.7.6-h357f687_1 [67936]
    python-3.7.6-h357f687_2 [67937]
    python-3.7.6-h357f687_3_cpython [67938]
    python-3.7.6-h357f687_4_cpython [67939]
    python-3.7.6-h8356626_5_cpython [67940]
    python-3.7.6-he5300dc_5_cpython [67941]
    python-3.7.6-h0371630_2 [149774]
    next rules: 0 0
job: erase xtensor-0.21.5-hc9558a2_0
  - job Rule #3072912:
    !xtensor-0.21.5-hc9558a2_0 [328]I (w1)
    next rules: 0 0
job: install xtensor-0.21.5-hc9558a2_0
  - job Rule #3072913:
    xtensor-0.21.5-hc9558a2_0 [105564] (w1)
    next rules: 0 0
choice rule creation took 416 ms
choice rule creation took 416 ms
3072240 pkg rules, 2 * 335 update rules, 3 job rules, 0 infarch rules, 0 dup rules, 0 choice rules, 0 best rules, 0 yumobs rules
overall rule memory used: 72021 K
solving...
resolving job rules
installing python-3.7.6-h8356626_5_cpython
resolving installed packages
keeping _libgcc_mutex-0.1-conda_forge
keeping _openmp_mutex-4.5-0_gnu
keeping _pytorch_select-0.2-gpu_0
...
XTENSOR __not__ mentioned here
```

Any hints?

**Comment by wolfv** [comment]
works perfectly fine after all, i just had some issues with how I printed things. Thanks!
