### ISSUE TITLE
Add support for retrieving SOLVABLE_BUILDHOST

### ISSUE THREAD

**Issue by lukash** [openSUSE/libsolv#400]
`SOLVABLE_BUILDHOST` is a "known id" in libsolv, but it seems the attribute is not read from the repository data and an empty string is returned when I attempt to read it using `solvable_lookup_str(s, SOLVABLE_BUILDHOST)`.

Looking at repodata on Fedora, the information seems to be in primary.xml under "package/format" and is called "rpm::buildhost", not "solvable:buildhost", as the constant is defined in libsolv.

**Comment by mlschroe** [comment]
This needs to be added to the repo parsers, e.g. ext/repo_rpmmd.c

**Comment by mlschroe** [comment]
Closing.
