### ISSUE TITLE
Unified old obsoletes behavior

### ISSUE THREAD

**Issue by kontura** [openSUSE/libsolv#415]
Please consider the following test case:
```
repo r1 0 testtags <inline>
#>=Pkg: b-pkg 1 2 x86_64
#>=Prv: b-pkg = 1-2
#>=Pkg: b-pkg 3.4 0 x86_64
#>=Prv: b-pkg = 3.4-0
#>=Pkg: a-obsoleter 3.4 0 x86_64
#>=Prv: a-obsoleter = 3.4-0
#>=Obs: b-pkg <= 3.0

system x86_64 rpm
poolflags implicitobsoleteusescolors whatprovideswithdisabled
solverflags allowdowngrade allowvendorchange keepexplicitobsoletes bestobeypolicy keeporphans yumobsoletes

job install oneof a-obsoleter-3.4-0.x86_64@r1 b-pkg-1-2.x86_64@r1 b-pkg-3.4-0.x86_64@r1 [forcebest,setevr,setarch]
result transaction,problems <inline>
#>install a-obsoleter-3.4-0.x86_64@r1
```

I beliave the result is technically correct but it would be nice if it produced the same resulting state as this different but similar test case:
```
repo system 0 testtags <inline>
#>=Pkg: b-pkg 1 2 x86_64
#>=Prv: b-pkg = 1-2

repo r1 0 testtags <inline>
#>=Pkg: b-pkg 3.4 0 x86_64
#>=Prv: b-pkg = 3.4-0
#>=Pkg: a-obsoleter 3.4 0 x86_64
#>=Prv: a-obsoleter = 3.4-0
#>=Obs: b-pkg <= 3.0

system x86_64 rpm system
poolflags implicitobsoleteusescolors whatprovideswithdisabled
solverflags allowdowngrade allowvendorchange keepexplicitobsoletes bestobeypolicy keeporphans yumobsoletes

job install oneof a-obsoleter-3.4-0.x86_64@r1 b-pkg-1-2.x86_64@system b-pkg-3.4-0.x86_64@r1 [forcebest,setevr,setarch]
result transaction,problems <inline>
#>upgrade b-pkg-1-2.x86_64@system b-pkg-3.4-0.x86_64@r1
```

Both install and update jobs here result in `b-pkg-3.4-0.x86_64`.

Interestingly if in the first test case a-obsoleter is changed to e.g. c-obsoleter (or generally the changed name is later in alphabetical order than b-pkg) it results in `b-pkg-3.4-0.x86_64` being installed.

For our use case in libdnf we would prefer if the result was consistently `b-pkg-3.4-0.x86_64` in all the mentioned situations. Would something like that be at all possible?

**Comment by mlschroe** [comment]
Well, it can't really be consistent. What happens that the solver has an alternative after pruning to the highest versions:  a-obsoleter-3.4-0 and b-pkg-3.4-0. There is no way to detect with of them is "better", so it takes the lexicographic first.

If you have "b-pkg" installed, it prefers to stay with the "b-pkg" name. If you have an old version of "a-obsoleter" it will go with that one. So it really depends on what's already installed in the system.

**Comment by kontura** [comment]
I see, thank you for the explanation.

**Comment by lukash** [comment]
@mlschroe hmm, couldn't it also prefer `b-pkg` if neither of them is installed though? For the sole reason of having a more consistent rule than leicographical order, which is not useful at all?
