### ISSUE TITLE
libsolv can't solve dependencies from plaindir file

### ISSUE THREAD

**Issue by fedya** [openSUSE/libsolv#431]
Trying to bootstrap OpenSuse Leap with bind in default installation and got this:
```
Problem: nothing provides (/sbin/start_daemon if systemd) needed by bind-9.16.6-12.38.1.x86_64
 Solution 1: do not install bind-9.16.6-12.38.1.x86_64
 Solution 2: break bind-9.16.6-12.38.1.x86_64 by ignoring some of its dependencies
```

strace

```
[pid 391392] uname({sysname="Linux", nodename="silver03.qa.sw.ru", ...}) = 0
[pid 391392] write(12, "2021-01-18 12:37:26 <1> silver03.qa.sw.ru(391392) [zypp] SATResolver.cc(problems):1195 nothing provides (/sbin/start_daemon if systemd) needed by bind-9.16.6-12.38.1.x86_64\n", 173) = 173
```

If i remove bind from chroot packages list everything goes fine.
RPM version 4.14.1
zypper 1.14.41
libsolv-tools-0.7.15

Probably zypper can't properly format repo2solv to correctly work with file deps

**Comment by mlschroe** [comment]
Maybe, but in that case you should open a bug against libzypp. I don't see libsolv doing something wrong here...

**Comment by mlschroe** [comment]
(They will most likely ask you to provide a solver testcase by calling zypper with the --debug-solver option...)
