### ISSUE TITLE
Kind request for a release?

### ISSUE THREAD

**Issue by j-mracek** [openSUSE/libsolv#432]
I am really sorry for the issue but would really appreciate the release of libsolv. Upstream contains a new parsing option of updateinfo that that is critical to us for errata applicability.

**Comment by mlschroe** [comment]
No prob. I'll do a release ASAP.

**Comment by mlschroe** [comment]
libsolv 0.7.17 is released now.

**Comment by j-mracek** [comment]
Thanks a lot
