### ISSUE TITLE
New Release Request

### ISSUE THREAD

**Issue by tl-hbk** [openSUSE/libsolv#437]
Could we get a new release so that mamba can get the fix to the windows build?  I did mention one other possible issue here though https://github.com/openSUSE/libsolv/pull/436#issuecomment-792800523 and if that's something that needs follow up on I can create a PR to get that resolved first

**Comment by tl-hbk** [comment]
@mlschroe could you take a look at this please

**Comment by mlschroe** [comment]
libsolv 0.7.18 has been released.

**Comment by wolfv** [comment]
thanks!
