### ISSUE TITLE
Advisory ID related questions

### ISSUE THREAD

**Issue by j-mracek** [openSUSE/libsolv#440]
I am really sorry to create an issue that is not a real issue. I would like to ask some questions related to ID `di.solvid` generated by following code (we use it to iterate over all advisories). I need to be sure that our expectations are valid for future design of libdnf.
```
    dataiterator_init(&di, pool, 0, 0, 0, 0, 0);
    dataiterator_prepend_keyname(&di, UPDATE_COLLECTION);
    while (dataiterator_step(&di)) {
        dataiterator_setpos_parent(&di);
        Advisory advisory(sack, di.solvid);
```
We would like to store advisory Id in Map therefore we need to know following. Is always `Id` of `di.solvid` in range between 0 and `pool->nsolvables`?
When we iterate over all pool solvables can we assume that for all solvables with name that starts with `patch:` prefix that it is an advisory? Will we get always the same set of advisories when we will use `dataiterator` (code above) in comparison to iteration over solvables with test for name prefix?

**Comment by mlschroe** [comment]
The following is just for the current implementation, so take it with a grain of salt:

1) yes, di.solvid is a valid solvable and thus in the range 1 .. pool->nsolvables
2) the "patch:" prefix is used by the metadata parser, it doesn't say anything about the content. But ':' is not allowed as rpm package name, so there can't be a conflict. Also, that prepend_keyname() call you do makes sure that you only get solvables that contain this data.
3) the dataiterator always iterates in solvid order, so you will get the same set as manually iterating over the solvables.
