### ISSUE TITLE
Question: Iterate over all translations of comps names and descriptions

### ISSUE THREAD

**Issue by pkratoch** [openSUSE/libsolv#441]
Hello,

During the comps parsing (in `ext/repo_comps.c`), all translations of names and descriptions are stored, and for each language, I can access the translation. However, that requires to know which language I am looking for. Is there any way to iterate over all stored translations?

If not, can this feature be added? Can you give me some pointers how it should be done?

Thanks!

**Comment by mlschroe** [comment]
I think the only way do do it right now is to use a dataiterator to iterate over everything stored in the package. (You can use `dataiterator_skip_attribute()` to skip over data you don't want.)

**Comment by pkratoch** [comment]
This works for me. Thank you for the tip and I'm closing the issue.
