### ISSUE TITLE
rpmdb fallback to non-rootdir

### ISSUE THREAD

**Issue by cgwalters** [openSUSE/libsolv#451]
See discussion in https://github.com/coreos/rpm-ostree/pull/2826

There's a *lot* of history for this code, but I think the silent fallback to ignoring `rootdir` appeared in 10a1ecf4f00b9472039412244d2ab6947bf074bd

Was there a reason for this?

**Comment by mlschroe** [comment]
Libsolv should not ignore rootdir. It's true that state->dbpath does not have the rootdir prepended, but it should be added in the places when state->rootdir is used.

What exactly does not work?

**Comment by mlschroe** [comment]
(The state->rootdir should also be state->dbpath in the comment above)

**Comment by cgwalters** [comment]
OK yeah I misread that code, sorry.  Closing for now.
