### ISSUE TITLE
Cannot use disfavor to not install packages as weak deps.

### ISSUE THREAD

**Issue by j-mracek** [openSUSE/libsolv#452]
I tried to use disfavor to prevent of installing of unmet weak deps during upgrade (See https://github.com/rpm-software-management/libdnf/pull/1257 and https://github.com/rpm-software-management/dnf/pull/1774). It works like expected with one exception - Obsoletes.

```
repo @System 0 testtags <inline>
#>=Pkg: pkg-A 1.0 1 noarch
#>=Prv: pkg-A = 1.0-1
#>=Rec: pkg-C
#>=Pkg: pkg-B 1.0 1 noarch
#>=Prv: pkg-B = 1.0-1

repo available -99.-1000 testtags <inline>
#>=Pkg: pkg-A 1.0 3 noarch
#>=Prv: pkg-A = 1.0-3
#>=Rec: pkg-B
#>=Pkg: pkg-B 1.0 2 noarch
#>=Prv: pkg-B = 1.0-2
#>=Pkg: pkg-C 1.0 1 noarch
#>=Prv: pkg-C = 1.0-1
#>=Obs: pkg-B
#>=Prv: pkg-B = 5.0-1

system x86_64 rpm @System
poolflags implicitobsoleteusescolors
solverflags allowvendorchange keepexplicitobsoletes bestobeypolicy keeporphans yumobsoletes
#job update all packages [forcebest]
#job update all packages
job update oneof pkg-A-1.0-1.noarch@@System pkg-B-1.0-1.noarch@@System pkg-A-1.0-3.noarch@available pkg-B-1.0-2.noarch@available pkg-C-1.0-1.noarch@available [forcebest,targeted,setevr,setarch]
job disfavor name pkg-C
#job disfavor oneof pkg-C-1.0-1.noarch@available
result transaction,problems <inline>
#>erase pkg-B-1.0-1.noarch@@System pkg-C-1.0-1.noarch@available
#>install pkg-C-1.0-1.noarch@available
#>upgrade pkg-A-1.0-1.noarch@@System pkg-A-1.0-3.noarch@available
```

Related: https://github.com/openSUSE/libsolv/issues/173

**Comment by mlschroe** [comment]
It does not happen when I run the testcase locally. Is your libsolv patched in some weird way?

**Comment by j-mracek** [comment]
I use `libsolv-0.7.17-3.fc34.x86_64` from Fedora distribution. The build of the package was performed according to spec -  https://src.fedoraproject.org/rpms/libsolv/blob/f34/f/libsolv.spec. There is no additional patches, only set of swiches is used to modify the build.

**Comment by mlschroe** [comment]
Maybe, but when I do a `./testsolv -r` on your testcase, I just get:
```
upgrade pkg-A-1.0-1.noarch@@System pkg-A-1.0-3.noarch@available
upgrade pkg-B-1.0-1.noarch@@System pkg-B-1.0-2.noarch@available
```

**Comment by j-mracek** [comment]
> Maybe, but when I do a `./testsolv -r` on your testcase, I just get:
> 
> ```
> upgrade pkg-A-1.0-1.noarch@@System pkg-A-1.0-3.noarch@available
> upgrade pkg-B-1.0-1.noarch@@System pkg-B-1.0-2.noarch@available
> ```

@mlschroe Is it expected result from my testcase? Is it expected that `disfavor` is stronger rule then obsoletes, or repo priority? I need to clarify that the current behaviour of `disfavor` is correct or not.

I do not say that disfavor behaves incorrectly. I only say that I cannot use disfavor to only disable packages as candidates to satisfy weak dependencies without interfering with other rules.

**Comment by mlschroe** [comment]
Yes, that's the expected output. Basically "disfavor" says that I don't want that version of the package, e.g. you can disfavor a specific kernel version. Obsoletes and repo priorities are just means to order the versions of a package, disfavor is expected to be stronger.

If you just want to get rid of weak dependencies we need to add something else.

**Comment by mlschroe** [comment]
(I'm not so sure about usability though, how would you present this option to the user?)

**Comment by Conan-Kudo** [comment]
Maybe we should reset a bit: the problem we're trying to solve is ignoring unsatisfied weak dependency stanzas in packages that remain unchanged as those packages upgrade. That is, given the installed package `foo-1` with weak dep `bar` that's _not_ installed, upgrading to `foo-2` that sill has weak dep `bar` will not trigger an install of `bar`. However, if the weak dep _changes_, (such as changing to `bar >= 50` from just `bar`), then it should activate.

**Comment by j-mracek** [comment]
@mlschroe Thanks for explanation. I am going to try to implement some basic mechanism in libsolv for exclusion of weak deps.

**Comment by j-mracek** [comment]
I propose a new mechanism (https://github.com/openSUSE/libsolv/pull/454) that will only ignore packages to satisfy weak deps. I also prepare a logic to detect unmet weak dependencies of installed packages and prevent installing them on upgrade, reinstall and so on (https://github.com/rpm-software-management/dnf/pull/1780 - new option `weak_exclude_unmet_weak_deps`).

It is supposed to resolve a strange behaviour with fresh system when the first update installs a lot of weak dependencies.

The mechanism must be also supported by PackageKit therefore I have to move the code to libdnf or libsolv. @mlschroe Do you have an interest to have such a mechanism in libsolv?

**Comment by mlschroe** [comment]
I don't think you're doing this right. If a weak dep couldn't be installed because of a package conflict or a broken dependency you do want it to be installed on update.

Why are all the weak deps missing in a fresh system? Why wouldn't the user want to have them installed?

Don't you need something different? We had a discussion about this some time ago at SUSE. One idea was to store in the dnf db (that also has the userinstalled info) if the package was installed with weak deps disabled or not. This information could be passed to the solver in the next run, so that an update known if weak deps are on or off.

**Comment by j-mracek** [comment]
Personally I agree with you. It is not a best solution to auto detect unmet weakdeps. The long discussion about the topic is here - https://bugzilla.redhat.com/show_bug.cgi?id=1699672.

I think that the fist part with implementation of weak_exclude is a good start. Any future logic for auto-handling of weak deps can use it.

**Comment by adelton** [comment]
> I don't think you're doing this right. If a weak dep couldn't be installed because of a package conflict or a broken dependency you do want it to be installed on update.

This is a valid point. That's why it's useful to have this as an option that the end admins could enable or disable. On fast moving systems (Fedora rawhide), that may happen. On stable systems (RHEL), that shouldn't happen.

> Why are all the weak deps missing in a fresh system? Why wouldn't the user want to have them installed?

Because the admin used `dnf install -x ...` or `-package` in anaconda kickstart. Because they want to minimize their system installation to limit security exposure. Or they know better than the packager how they want the software to be used, and they know that specific weak depenency (which often pulls in huuuuuuge list of additional depenencies) will never be used, so it should not waste space on their systems.

> Don't you need something different? We had a discussion about this some time ago at SUSE. One idea was to store in the dnf db (that also has the userinstalled info) if the package was installed with weak deps disabled or not. This information could be passed to the solver in the next run, so that an update known if weak deps are on or off.

The problem is that for existing installations you'd need to populate such database somehow.

**Comment by mlschroe** [comment]
I'm not very happy with the proposed patches. The weakexcludes jobs go (like all other jobs) over packages, but this is maybe not what's needed. If installed package A recommends not-installed B, and I now install package C that also recommends B, shouldn't B be installed then?

It would be way easier to do this in the weak deps handling phase in libsolv, where we directly deal with the dependencies.

And we also need to figure out how supplements should work (because currently they don't). Are they even in scope of this or would it be ok to just concentrate on recommends?

**Comment by j-mracek** [comment]
When supplements start to work in libsolv we will need to apply weak excludes also to them.

When I investigate the problem I discovered that there are multiple contradicting point of view. Maintainers and developers want to use weak deps, because they have additional value for them, but they are not required. Distribution point of view is different. They want to not install some packages for good reasons (size of image, security problems). End-users don't to see such a packages because they chose deployment probably for some reasons (size of image, no security problems) and they want to keep that value. But they also don't want to disable weak deps but they want keep some weak deps out of their systems. Unfortunately this not all. Dependency can be versioned, or represented by a file or written as reach dependency. With versions there is a fun because `Recommends: foo = 4.4` is in update changed to `Recommends: foo = 4.5` or even something else. With such an environment it is not easy to create a static list of rules (created by distribution or user) and also difficult to generate dynamic one.

I want to say that we are not looking for the perfect solution, because there is none. We are looking for solution with maximum value for most of the users with reduce risk of misbehavior and limited requirements for maintenance.

**Comment by j-mracek** [comment]
> I'm not very happy with the proposed patches. The weakexcludes jobs go (like all other jobs) over packages, but this is maybe not what's needed. If installed package A recommends not-installed B, and I now install package C that also recommends B, shouldn't B be installed then?

In case when B was not installed on purpose (but we don't know) what I don't like:
1. Package B on my system
2. Package A together with B
3. Satisfied recommend of package A

When answer `1` is correct for most of users then when I install C that recommend B I also don't want to install B.

**Comment by j-mracek** [comment]
The issue is resolved by an alternative approach in libsolv. Thank you all for help.
