### ISSUE TITLE
bindings: solv.lookup_idarray actually calls lookup_deparray

### ISSUE THREAD

**Issue by lnussel** [openSUSE/libsolv#453]
'solv.lookup_idarray' internally calls `solvable_lookup_deparray`:
https://github.com/openSUSE/libsolv/blob/e2ed3f290d588642b454d19e8c993d76b7a58f15/bindings/solv.i#L3051-L3057

That's already done by `solv.lookup_deparray` so I suppose it should call `solvable_lookup_idarray` instead?

**Comment by mlschroe** [comment]
No, idarray returns raw ids whereas deparray returns dependency objects.
