### ISSUE TITLE
A worse choice is picked when resolving transaction

### ISSUE THREAD

**Issue by pkratoch** [openSUSE/libsolv#465]
Hi, I've encountered a situation where a transaction can be resolved in two ways and libsolv picks one that is in some sense worse. I understand that both are valid, but is there something that could be done to prefer the other choice without breaking other use cases?

The situation is following:

`yolo-2.0` recommends `yolo-selinux` (any version)
`yolo-selinux-1.0` requires `selinux-policy-1.0`
`yolo-selinux-2.0` requires `selinux-policy-2.0`

When `selinux-policy-1.0` is installed, and I install `yolo-2.0`, there are two options how to resolve it:

1. install `yolo-2.0` and `yolo-selinux-2.0` and upgrade `selinux-policy to 2.0`
2. install `yolo-2.0` and `yolo-selinux-1.0`

From user perspective, the first option is preferred, because of newer versions of dependencies.

Corresponding testcase:
```
repo @System 0 testtags <inline>
#>=Pkg: selinux-policy 1.0 1 x86_64
#>=Prv: selinux-policy = 1.0-1

repo updates 0 testtags <inline>
#>=Pkg: yolo 2.0 1 x86_64
#>=Prv: yolo = 2.0-1
#>=Req: yolo-selinux
#>=Pkg: yolo-selinux 1.0 1 x86_64
#>=Prv: yolo-selinux = 1.0-1
#>=Req: selinux-policy = 1.0
#>=Pkg: yolo-selinux 2.0 1 x86_64
#>=Prv: yolo-selinux = 2.0-1
#>=Req: selinux-policy = 2.0
#>=Pkg: selinux-policy 2.0 1 x86_64
#>=Prv: selinux-policy = 2.0-1

system x86_64 rpm @System
poolflags implicitobsoleteusescolors

solverflags allowvendorchange keepexplicitobsoletes bestobeypolicy keeporphans yumobsoletes
job install pkg yolo-2.0-1.x86_64@updates [forcebest,targeted,setevr,setarch]

result transaction,problems <inline>
#>install yolo-2.0-1.x86_64@updates
#>install yolo-selinux-2.0-1.x86_64@updates
#>upgrade selinux-policy-1.0-1.x86_64@@System selinux-policy-2.0-1.x86_64@updates
```

**Comment by ignatenkobrain** [comment]
> From user perspective, the first option is preferred, because of newer versions of dependencies.

I don't think so, IIRC libsolv prefers smalles possible transaction.

**Comment by ignatenkobrain** [comment]
You can, however use `focusbest` (`SOLVER_FLAG_FOCUS_BEST`) to achieve what you are saying.
