### ISSUE TITLE
Kind request for release of 0.7.20

### ISSUE THREAD

**Issue by j-mracek** [openSUSE/libsolv#476]
To resolve https://bugzilla.redhat.com/show_bug.cgi?id=1699672 in DNF/libdnf upstream, we need related functionality in released libsolv. The release of libsolv is not a blocker for backports of functionality to Fedora/ RHEL, but other distribution (OpenSuse, Mageia) will not benefit from it.

**Comment by mlschroe** [comment]
0.7.20 is now released!

**Comment by j-mracek** [comment]
@mlschroe Thanks a lot.
