### ISSUE TITLE
qsort_r.c does not build against musl-1.2.2

### ISSUE THREAD

**Issue by terefang** [openSUSE/libsolv#480]
qsort_r.c does not build against musl-1.2.2 since musl does not have internal glibc header sys/cdefs.h

removing sys/cdefs.h from the include builds fine

```diff
 $ diff -u target/libsolv/libsolv-0.7.20/src/qsort_r.c src/main/dist/qsort_r.c 
--- target/libsolv/libsolv-0.7.20/src/qsort_r.c 2021-09-25 22:54:41.000000000 +0200
+++ src/main/dist/qsort_r.c     2021-11-09 10:25:14.101595296 +0100
@@ -38,7 +38,6 @@
 static char sccsid[] = "@(#)qsort.c    8.1 (Berkeley) 6/4/93";
 #endif /* LIBC_SCCS and not lint */
 #ifndef _WIN32
-#include <sys/cdefs.h>
 #endif
 
 /* $FreeBSD: src/lib/libc/stdlib/qsort.c,v 1.13.2.1.8.1 2010/12/21 17:10:29 kensmith Exp $ */
```

**Comment by terefang** [comment]
see also https://wiki.musl-libc.org/faq.html#Q:_When_compiling_something_against_musl,_I_get_error_messages_about_%3Ccode%3Esys/cdefs.h%3C/code%3E

**Comment by mlschroe** [comment]
I was under the impression that musl supports qsort_r, so why do we need our qsort_r.c?

**Comment by Conan-Kudo** [comment]
musl does _not_ support `qsort_r(3)`,  it got `fopencookie(3)` a few years ago. It's always used our `qsort_r(3)` implementation.

**Comment by mlschroe** [comment]
But there is a qsort_r in https://git.musl-libc.org/cgit/musl/tree/src/stdlib/qsort.c

**Comment by mlschroe** [comment]
Anyway, seems like stdlib.h pulls in sys/cdefs.h on bsd, so it should be ok to drop the include. Merging.

**Comment by terefang** [comment]
welcome

**Comment by terefang** [comment]
which release will include this fix ?

**Comment by mlschroe** [comment]
Oops, I forgot to answer this. 0.7.21 has the change.

**Comment by terefang** [comment]
hello

just to shine light to the missing `sys/cdefs.h` in genuine musl-libc.

it looks like most distros add the `musl-bsdcompat` package on top of the genuine musl-libc which includes the `sys/cdefs.h` file (among others).

this has nothing to do with the availability of `qsort_r`.

musl actually declares `qsort_r` in `stdlib.h` but it is fenced by `#if defined(_GNU_SOURCE) || defined(_BSD_SOURCE)`.

this may be the actual cause that embedded qsort is chosen.

hope that helped
