### ISSUE TITLE
Versioning solv files

### ISSUE THREAD

**Issue by kontura** [openSUSE/libsolv#481]
Recently we ran into an issue where older libsolv is used to generate solv files, update is performed, and then libdnf uses the old solv files (so they are up to date just generated with older libsolv).
The specific problem is that they are missing `UPDATE_COLLECTIONLIST` section (added in 0.7.16) and libsolv reports it as empty.

I found that there is a `REPOSITORY_TOOLVERSION` id, is this intended to be used to store the solv file version?
Should we increase and use [ `LIBSOLV_TOOLVERSION`](https://github.com/openSUSE/libsolv/blob/master/src/solvversion.h.in#L51) or is that specific for libsolv tools?

Could all of this be taken care of by libsolv itself? So the user doesn't have to set the solv file version at all. Libsolv could detect version mismatch and report it when trying to load such data.

**Comment by j-mracek** [comment]
@mlschroe May I ask you for information related to the issue. Basically we would like to know whether `REPOSITORY_TOOLVERSION` can we uses as a marker that the cache generated by libsolv is compatible with current version. If we will get a positive answer we will provide a patch that will increase  `LIBSOLV_TOOLVERSION`.

There was also a question whether there is or will be a functionality in libsolv that can identify whether the solv file was created by a proper version of libsolv?

Thank you very much for your help.

**Comment by mlschroe** [comment]
TOOLVERSION is supposed to reflect changes in libsolv's repo parsers, so yes, it should have been bumped when UPDATE_COLLECTIONLIST was added.

(libsolv does not use it, libzypp uses it to check if the cached solv file can be reused or should be regenerated.)

**Comment by j-mracek** [comment]
@mlschroe Thank you very much for your update
