### ISSUE TITLE
libsolv seems to be incompatible with RPM 4.17

### ISSUE THREAD

**Issue by mrc0mmand** [openSUSE/libsolv#483]
Recently in systemd and mkosi [we noticed](https://github.com/systemd/mkosi/issues/861) that OpenSUSE builds keep failing with newer versions of certain packages. After [further investigation](https://github.com/systemd/mkosi/issues/861#issuecomment-1003624115) the culprit seems to be libsolv. There's already a workaround in place for RPM 4.16 (https://github.com/openSUSE/libsolv/commit/c78a330a27bb3844b97e694552efc4a373cf217b), but the same issue seems to apply to RPM 4.17 as well.

For the time being we patch libsolv on the fly (https://github.com/systemd/mkosi/pull/878) so it doesn't disrupt CI runs, but in the long term it would be great to have an *official* solution.

Some logs for completeness:

zypper with RPM 4.17.0 and libsolv 0.7.19:
```
$ sudo zypper -vv --root /var/tmp/hello-world update
Verbosity: 2
Initializing Target
Target initialization failed:
Failed to cache rpm database (1).
History:
 - 'rpmdb2solv' '-r' '/var/tmp/hello-world' '-X' '-p' '/var/tmp/hello-world/etc/products.d' '-o' '/var/tmp/hello-world/var/cache/zypp/solv/@System/solvjNSBOh'
warning: using dummy database, installs not possible
rpmdb2solv: no error
```

The patch we currently use as a workaround:
```diff
diff --git a/ext/repo_rpmdb_librpm.h b/ext/repo_rpmdb_librpm.h
index 3f9798c2..e1b30a0f 100644
--- a/ext/repo_rpmdb_librpm.h
+++ b/ext/repo_rpmdb_librpm.h
@@ -136,7 +136,7 @@ opendbenv(struct rpmdbstate *state)
       return 0;
     }
 #ifndef HAVE_RPMDBNEXTITERATORHEADERBLOB
-  if (!strcmp(RPMVERSION, "4.16.0"))
+  if (!strcmp(RPMVERSION, "4.16.0") || !strcmp(RPMVERSION, "4.17.0"))
     set_db_backend();
 #endif
   if (rpmtsOpenDB(ts, O_RDONLY))
```

zypper with RPM 4.17.0 and libsolv 0.7.19 + the patch above:
```
$ sudo LD_LIBRARY_PATH=/usr/local/lib/ zypper -vv --root $PWD/hello-world update 
Verbosity: 2
Initializing Target
Loading repository data...
Reading installed packages...
Force resolution: No

Nothing to do.
```

**Comment by mlschroe** [comment]
I guess this means you're using a non-standard rpm database path?

**Comment by mlschroe** [comment]
(rpm-4.17's database autodetection  should work because of https://github.com/rpm-software-management/rpm/commit/0644e4e79c841b03d606fc8bb035ec311f4bfb17, so it must be something else that breaks database reading)

**Comment by Conan-Kudo** [comment]
Well, openSUSE is using `/usr/lib/sysimage/rpm` instead of `/var/lib/rpm`.

**Comment by mrc0mmand** [comment]
Ah, I forgot to mention that the failing `zypper --root` command runs on Ubuntu Focal (not OpenSUSE), so it most likely uses a "non-standard" RPM path (as Neal already mentioned).

**Comment by Werkov** [comment]
Accidentally, I noticed systemd/mkosi@44dfd9e719b1b0563a93e4e1695598921cc4c263 has been merged recently. That makes this issue less pressing (or even straight obsolete).

**Comment by mrc0mmand** [comment]
Closing this one as it's no longer relevant.

**Comment by mlschroe** [comment]
Thanks for the update!
