### ISSUE TITLE
Custom dnf solv file format

### ISSUE THREAD

**Issue by kontura** [openSUSE/libsolv#487]
This is a kind of follow up to: https://github.com/openSUSE/libsolv/issues/481

We want to use `solv_toolversion` to decide whether we need to regenerate the solv files but we would like to know this before loading the solv file itself (so we cannot store it inside under the `REPOSITORY_TOOLVERSION` id).

We are thinking we could introduce our own header for the solv file, something like:
```
4 bytes dnf .solv file magic
4 bytes dnf .solv file version
8 bytes solv_toolversion (with some extra padding)
32 bytes repodata checksum
libsolv solv file data
```
and when loading we would just pass a `FILE *` pointing to the beginning of the `libsolv solv file data` to `repo_add_solv()`.

@mlschroe can you please provide some feedback on this? We'll be relying on the `FILE *` passed to `repo_add_solv()` being read from its current position, do you see any problem with this or any other issue that could occur here?

**Comment by mlschroe** [comment]
The "solv" demo solver appends extra information at the end of the solv file. Maybe you want to do something like this as well.

**Comment by lukash** [comment]
Well, we're doing something like that already. The way we've got it implemented is far from ideal (which is more related to it being just the plain checksum being appended without any version or explicit identifier of the data, not the fact that it's placed at the end).

The conventional way is to start a file with a header that contains the metadata, and with a magic right at the beginning. Having this structure at the end is a bit harder to work with in addition to unconventional. Unless there's a relevant reason to put the metadata structure at the end, I'd stick with the conventional way.

**Comment by mlschroe** [comment]
Prepending another header has the disadvantage that you can no longer use the standard tools like dumpsolv on the files.
I can certainly add support for a "comment" section that's at the start of the solv data and can be read/written by two new functions:

  unsigned char *solv_read_comment(FILE *fp, int *lenp);
  void repowriter_set_comment(Repowriter *writer, unsigned char *comment, int len);

Would that work for you?

**Comment by kontura** [comment]
We have discussed it and it seems like a good solution that will work for us.
Thank you @mlschroe for helping us!

Maybe one suggestion, how about naming the section for example `appdata` instead of `comment`? `comment` kind of implies just text.

**Comment by mlschroe** [comment]
`appdata` is already used both for the pool/repo user data and the AppStream metadata. How about `custom` or `userdata`? But I'm also ok with `appdata` if you insist ;-)

**Comment by Conan-Kudo** [comment]
`userdata` makes sense to me here.

**Comment by kontura** [comment]
`userdata` sounds good to me as well.

**Comment by lukash** [comment]
@mlschroe thanks for implementing the API! I made a comment on the commit: https://github.com/openSUSE/libsolv/commit/fee19a416cb965858ba6c810b3d6ed9b8ac7ae9a#r67882012
