### ISSUE TITLE
Issue with added recommends

### ISSUE THREAD

**Issue by kontura** [openSUSE/libsolv#489]
We have a bug that started happening since https://github.com/openSUSE/libsolv/commit/958c8396ade46920b87f29f1f75456d97cc63812 before this commit `php-fpm` is installed together with `libcrypt` but with newer libsolv only the upgrades are preformed.

```
repo @System 0 testtags <inline>
#>=Pkg: glibc 2.17 325 x86_64
#>=Prv: libcrypt
#>=Pkg: php 5.4.16 48 x86_64

repo available 0 testtags <inline>
#>=Pkg: php 7.2.24 1 x86_64
#>=Rec: php-fpm = 7.2.24-1
#>=Pkg: php-fpm 7.2.24 1 x86_64
#>=Req: libcrypt
#>=Pkg: php-fpm 8.0.13 2 x86_64
#>=Req: libcrypt
#>=Pkg: libcrypt 4.1.1 6 x86_64
#>=Req: libc
#>=Pkg: glibc 2.28 181 x86_64
#>=Prv: libc

system x86_64 rpm @System
job update all packages

result transaction,problems <inline>
#>install libcrypt-4.1.1-6.x86_64@available
#>install php-fpm-7.2.24-1.x86_64@available
#>upgrade glibc-2.17-325.x86_64@@System glibc-2.28-181.x86_64@available
#>upgrade php-5.4.16-48.x86_64@@System php-7.2.24-1.x86_64@available
```

Interestingly if only the desired version of `php-fpm` is available it works as expected.

**Comment by mlschroe** [comment]
Yeah, known issue. It's on the top of my TODO list. Thing is, it's not easy to get the choice rule creation right if package splits are present. I'll add this to the choice rule testcases.
