### ISSUE TITLE
Support simultaneous binding builds for Python 2 _and_ Python 3

### ISSUE THREAD

**Issue by sunweaver** [openSUSE/libsolv#50]
HI,

I spent the night with finding a patch that will introduce support to libsolv for simultaneously building bindings for Python2 _and_ Python3.

Patch will come during the day...

Mike (aka sunweaver at debian.org)

**Comment by thopiekar** [comment]
:+1:

**Comment by mlschroe** [comment]
Hmm, I now added a python3 target and you need to feed cmake the correct PYTHON3_EXECUTABLE/PYTHON3_INCLUDE_DIR and not rely on the autodetection.
