### ISSUE TITLE
Uninstallation order is wrong after using "Enhances:" tag in sub package

### ISSUE THREAD

**Issue by sshedi** [openSUSE/libsolv#501]
Hi All,

We are using Enhances tag in our kernel specs.

For instance:
https://github.com/vmware/photon/blob/f43b02c4401dd9d2f0fb4807c8208eac6f3ec089/SPECS/linux/linux.spec#L563

We did this change based on the suggestion here: https://github.com/openSUSE/libsolv/issues/370

Now the problem is, sub package is getting removed after main package. In other words, in our systems `linux-hmagen` is getting removed after `linux` when we do `tdnf erase -y linux linux-hmacgen`

Find the attached log for more details.

```
Removing: linux-esx-hmacgen-4.19.247-2.ph3.x86_64
D: erase      100744  1 (   0,   0)  4444 /lib/modules/4.19.247-2.ph3-esx/extra/hmac_generator.ko.xz
D: erase      100644  1 (   0,   0)   197 /lib/modules/4.19.247-2.ph3-esx/extra/.hmac_generator.ko.xz.hmac
```
Can we make the order or removal right somehow? We want to use Enhances and at the same time want the sub-package to get removed before main package. Please assist.

[tdnf-log.txt](https://github.com/openSUSE/libsolv/files/9000758/tdnf-log.txt)

**Comment by mlschroe** [comment]
This seems to be a bug in rpm. Libsolv's order code would work like expected, but dnf does not use it. Instead, it relies on rpm calculating the correct order (which is good, because rpm has more information about the packages).

Unfortunately rpm treats "Enhances" like "Requires" for ordering purposes. This is wrong, as "Enhances" is a reverse dependency. A "Enhances: linux" in the linux-hmagen package should work the same as "Suggests: linux-hmagen" in the linux package.

**Comment by mlschroe** [comment]
Oh wait, that's actually not true. I misread the rpm code, it should deal correctly with reverse deps.

**Comment by mlschroe** [comment]
(Anyway, all this is not a libsolv issue...)

**Comment by sshedi** [comment]
You mean to say we should remove `Requires: linux` and use only `Enhances: linux`?

**Comment by mlschroe** [comment]
No, the Requires is the important dependency. You may be able to fix this by adding a extra dependency to the hmacgen package:
```
Requires(postun):      %{name} = %{version}-%{release}
```
I.e. tell rpm that the uninstall of the hmacgen package needs the kernel, i.e. that it needs to be uninstalled before the kernel.

**Comment by mlschroe** [comment]
(It would be better to fix this in rpm, obviously)

**Comment by sshedi** [comment]
Thanks a lot. I will try this.
