### ISSUE TITLE
Provides not honored after package is renamed

### ISSUE THREAD

**Issue by sshedi** [openSUSE/libsolv#515]
Hi All,

In PhotonOS we have a python2 variant of libtalloc package

https://github.com/vmware/photon/blob/3.0/SPECS/libtalloc/libtalloc.spec#L27

In one of our changes while upgrading libtalloc to v2.3.4, we want to rename this package to `python3-talloc` and our changes look like below:

```
%package -n python3-talloc
Group: Development/Libraries
Summary: Python bindings for the Talloc library
Requires: libtalloc = %{version}-%{release}
Provides: python-talloc = %{version}-%{release}
Obsoletes: python-talloc < 2.3.4-1
````

The problem now is, both `python-talloc` and `python3-talloc` are present in our repo. And when we do `tdnf install python-talloc`, python2 variant is getting installed even though we are saying that `python3-talloc` is Obsoletes and Provides `python-talloc`.

The expectation is: `tdnf install -y python-talloc` should implicitly bring in `python3-talloc` and not the older python2 variant. Is it possible to do so? Please assist.

cc: @tapakund @YustasSwamp @oliverkurth @bhllamoreaux

**Comment by mlschroe** [comment]
I can't answer this as I don't know the job dnf generates. Could you please move this issue over to the dnf project, i.e. https://github.com/rpm-software-management/dnf/

**Comment by sshedi** [comment]
Hi @mlschroe, this is not dnf. We have our own package manager `tdnf` (written completely in C).
Do you need any supporting logs? Can you give more info what do you mean by `job dnf generates`?

**Comment by sshedi** [comment]
To add to my original info, if `python-talloc` older rpm is not present in the repo and if it's just `python3-talloc`, then `tdnf install python-talloc` will bring in `python3-talloc` automatically. Only when `pytohn-talloc` older rpm is present, it's not working as expected.

**Comment by mlschroe** [comment]
I would need a solver testcase, i.e. you need to call `testcase_write(solv, dir, 0)` after solving. dnf or zypper have a `--debug-solver` option for this.

**Comment by mlschroe** [comment]
Hey, tdnf already supports this. Try `--debugsolver`, it should create a `debugdata` directory.

**Comment by sshedi** [comment]
With both python-talloc and python3-talloc rpms present in the repo:
```
root@ph3dev:~ # tdnf install python-talloc --debugsolver

Installing:
python2-libs                          x86_64             2.7.17-7.ph3             local               15.97M 16741596
python2                               x86_64             2.7.17-7.ph3             local                2.03M 2129829
libtalloc                             x86_64             2.1.14-3.ph3             local               91.62k 93824
python-talloc                         x86_64             2.1.14-3.ph3             local               35.22k 36064

Total installed size:  18.12M 19001313
Is this ok [y/N]: y

Downloading:
python2-libs                           5970687   100%
python2                                 817279   100%
libtalloc                                48268   100%
python-talloc                            18147   100%
Testing transaction
Running transaction
Installing/Updating: python2-2.7.17-7.ph3.x86_64
detected install of python3, linking python to python3
Installing/Updating: python2-libs-2.7.17-7.ph3.x86_64
Installing/Updating: libtalloc-2.1.14-3.ph3.x86_64
Installing/Updating: python-talloc-2.1.14-3.ph3.x86_64

Complete!
```

With only `python3-talloc` in repo:
```
root@ph3dev:~ # tdnf install python-talloc --debugsolver
[using capability match for 'python-talloc']
[using capability match for 'python-talloc']

Installing:
libtalloc                             x86_64             2.3.4-1.ph3              local               98.35k 100712
python3-talloc                        x86_64             2.3.4-1.ph3              local               40.91k 41896

Total installed size: 139.27k 142608
Is this ok [y/N]: y

Downloading:
libtalloc                                49207   100%
python3-talloc                           19935   100%
Testing transaction
Running transaction
Installing/Updating: libtalloc-2.3.4-1.ph3.x86_64
Installing/Updating: python3-talloc-2.3.4-1.ph3.x86_64

Complete!
```

Attaching the corresponding debugdata files with debugsolver enabled.

[debugdata-with-both-rpms.tar.gz](https://github.com/openSUSE/libsolv/files/10227314/debugdata-with-both-rpms.tar.gz)

**Comment by mlschroe** [comment]
I don't know. That's all code in tdnf. I guess SolvFindHighestAvailable() in tdnfs's solv/tdnfpackage.c behaves different.

**Comment by mlschroe** [comment]
It seems like it checks if a package with the specified name is available. If one exists, it uses the package. Otherwise it falls back to looking at the provides of other packages.

**Comment by sshedi** [comment]
Thanks a lot @mlschroe for the excellent inputs. We will discuss this internally and conclude. I will close this issue with next few days. Have a nice time ahead.

**Comment by mlschroe** [comment]
Just as a pointer: libdnf checks for obsoletes if the input is just a name (see hy-subject.cpp). Maybe you can do something like this as well.

**Comment by oliverkurth** [comment]
Thanks @mlschroe for your support!

Currently, as you have observed, tdnf searches for the latest version available, then constructs a job using the solvable id found with `SOLVER_SOLVABLE`. I wonder, if instead (in the case just a name is supplied), we would create the job with `SOLVER_SOLVABLE_NAME` and the supplied name. Would the solver then do what is expected? That is: find the highest version or a package that obsoletes it? That could save us some work.

**Comment by oliverkurth** [comment]
Alright, I tested this. Unless I am missing something it just installs the latest version, but not the packages that obsoletes it. `SOLVER_FLAG_ALLOW_NAMECHANGE` is unchanged, but I also tried setting it explicitly.

**Comment by sshedi** [comment]
@mlschroe Indeed it was an issue with tdnf. In case you want to check, PR link: https://github.com/vmware/tdnf/pull/378
Thanks for your assistance. Thanks @oliverkurth for fixing this.

**Comment by oliverkurth** [comment]
I think this issue can be closed.

**Comment by sshedi** [comment]
Thanks a lot @oliverkurth. Huge thanks to @mlschroe for his inputs and his time.
