### ISSUE TITLE
distupgrade recognize disabled packages as best candidates

### ISSUE THREAD

**Issue by j-mracek** [openSUSE/libsolv#518]
We've got a report about weird DNF5 behavior for ditrosync (https://github.com/rpm-software-management/dnf5/issues/222). The issue is easy to reproduce with DNF5 when modular repository is enabled => it means many disabled packages are in transaction. I believe that the issue is in untargeted transaction with `distupgrade` where installed package is present in job and the best candidate is disabled and even not in job. But I cannot to proof it using testsolv. Even when DNF5 generates testdebug data, rerun with testsolv pass and say a differenc, that there is no error in comparison to stored transaction results.

Our solution is to mark job as TARGETED, but I report the issue anyway, because someone else could be affected.

The reproducer of reported issue would as follows, but it pass the testcase run. 
```
repo @System 0 testtags <inline>
#>=Pkg: nss 1.0.4 2 x86_64
#>=Prv: nss = 1.0.4-2


repo updates 0 testtags <inline>
#>=Pkg: nss 1.0.4 3 x86_64
#>=Prv: nss = 1.0.4-3
#>=Pkg: nss 1.0.6 1 x86_64
#>=Prv: nss = 1.0.6-1


system x86_64 rpm @System
poolflags implicitobsoleteusescolors
solverflags allowvendorchange keepexplicitobsoletes bestobeypolicy keeporphans yumobsoletes
disable pkg nss-1.0.6-1.x86_64@updates

job distupgrade oneof nss-1.0.4-2.x86_64@@System nss-1.0.4-3.x86_64@updates [forcebest,setevr,setarch]

result transaction,problems <inline>
#>upgrade nss-1.0.4-2.x86_64@@System nss-1.0.4-3.x86_64@updates
```

**Comment by mlschroe** [comment]
It's weird that "whatprovideswithdisabled" is not set in the pool flag. Doesn't dnf5 do that anymore? That flag was added because dnf4 changed the disabled map without rebuilding the whatprovides index. See #301  

That would also explain why it is not reproducible with a testcase.

**Comment by j-mracek** [comment]
Thank you very much for the tip. We will add the flag to DNF5.

**Comment by mlschroe** [comment]
(Maybe you should also revert the "make distupgrade targeted" change.)

**Comment by j-mracek** [comment]
In DNF we removed installed packages from the candidate set therefore I guess that libsolv used that transaction as targeted. In DNF5 we would like to keep the same behavior like DNF4 therefore we could remove TARGETED flag but also we have to removed installed packages form candidate set. I think we have to revisit it when we will try to improve messages for distrosync when a package is installed but no available package. @mlschroe Thank you very much for help. I completely forget about the flag.
