### ISSUE TITLE
What is the logic in the rule sorting?

### ISSUE THREAD

**Issue by wolfv** [openSUSE/libsolv#534]
Hi @mlschroe! 

We have been hard at work porting your wonderful library to Rust (for extra memory safety and because it's much easier to read for ourselves).

We have been debugging the remaining differences between libsolv and our port and one difference is the order the rule evaluation. 

I was wondering if the `unifyrules_sortcmp` is supposed to do an optimization for the order of rule evaluation or if it's just to remove duplicates?

We saw that in pubgrub there is an optimization to pick packages with fewest versions first (https://pubgrub-rs-guide.netlify.app/pubgrub_crate/strategy.html).

PS: if you are interested in the port, you can check it out in this PR - https://github.com/mamba-org/rattler/pull/236. It doesn't implement everything that libsolv can do (only what we need for `conda` packages so far). We are interested in expanding that a bit further though :) Would love to hear from you!

**Comment by mlschroe** [comment]
It's just used to remove duplicated rules.

**Comment by wolfv** [comment]
Thanks for the reply! I guess that will make it tricky to get _exactly_ the same results as libsolv in all cases but let's see!

I am closing this issue – have a nice weekend!
