### ISSUE TITLE
solvable_lookup_bin_checksum() returning only sha256

### ISSUE THREAD

**Issue by shivania2** [openSUSE/libsolv#538]
I am trying to get the checksum of a package and using solvable_lookup_bin_checksum() function. But solvable_lookup_bin_checksum() is returning only SHA256 even if checksum type is REPOKEY_TYPE_SHA512, REPOKEY_TYPE_SHA1 or REPOKEY_TYPE_MD5.

Is it a expected behaviour that solvable_lookup_bin_checksum() function will return only SHA256?

Query: solvable_lookup_bin_checksum() function will either return the specified checksumtype if it is present in file or if specified checksumtype is not present then it will return any checksumtype which is present?

**Comment by mlschroe** [comment]
The type pointer is just used to return the checksum type, so setting it before doing the checksum lookup does not do anything.

The repository parsers from the "ext" directory only store one checksum for each package. If the input data contains multiple checksum they will choose the "strongest" one.
