### ISSUE TITLE
Non consistent behavior of installonly packages

### ISSUE THREAD

**Issue by j-mracek** [openSUSE/libsolv#550]
The issue has following trigger:
All installed version must be available
The update triggers removal of dependent package (`kernel`) that has also update but the package is not requested to be updated.
The behavior is modified by order of installed package (`kernel`). If removed dependent package (kernel-1.0.2) is first on the list it trigger install of kernel-1.0.5. But in opposite situation, kernel-1.0.2 is only removed.

I am not sure whether libsolvs reads RPM DB in order of package ID in RPMDB.

Anyway it would be great if solver provides consistent results on multiple systems regardless of package order.

```
$ testsolv -W kernel-1.0.5-2.x86_64@updates test_multiversion2.txt 
conflicted kernel-1.0.5-2.x86_64@updates:
  it is unrelated
```
```
$ testsolv -W kernel-1.0.5-2.x86_64@updates test_multiversion.txt 
installed kernel-1.0.5-2.x86_64@updates:
  update installed
```

Libsolv testcases:

[test_multiversion.txt](https://github.com/openSUSE/libsolv/files/14207358/test_multiversion.txt)
[test_multiversion2.txt](https://github.com/openSUSE/libsolv/files/14207359/test_multiversion2.txt)

**Comment by mlschroe** [comment]
Fixed now.

**Comment by j-mracek** [comment]
Thank you very much
