### ISSUE TITLE
lua bindings?

### ISSUE THREAD

**Issue by lnussel** [openSUSE/libsolv#554]
Minimal systems intentionally do not ship with script interpreters like perl or python which leaves only shell and therefore makes it hard to write decent programs. There's one exception that we cannot avoid though: lua. It's built into rpm.
So how about adding lua bindings to libsolv so we can have fancing libsolv programs even on minimal systems?

**Comment by Conan-Kudo** [comment]
My initial response to that is "maybe you've made the system _too_ minimal".

**Comment by lnussel** [comment]
yes

**Comment by Conan-Kudo** [comment]
Well, SWIG supports generating Lua bindings, so you could try to extend the CMake scripts so it can do it.

**Comment by mlschroe** [comment]
We have tcl bindings, so lua should not be that hard ;-)

**Comment by mlschroe** [comment]
Done.

**Comment by lnussel** [comment]
U :rock:
