### ISSUE TITLE
Question: prefer one repository over another

### ISSUE THREAD

**Issue by oliverkurth** [openSUSE/libsolv#572]
I have two repositories. One is preferred, the other only to be used for particular packages (cherry-picks). Both have required packages. The second one may have newer versions of the required packages. Now I want to have a way to install a package (cherry-pick) from the second repository. But I want all its requirements installed from the preferred (first) repository, even if their versions are lower, unless the requirement cannot be fulfilled (for example, it requires a particular version, or the package exists only in the second repo).

Is that possible? Can I maybe use the flag `SOLVER_DISFAVOR` to mark all packages in the cherry-pick repo? Or is there another way?

**Comment by Conan-Kudo** [comment]
That sounds like repo priorities?

**Comment by oliverkurth** [comment]
You are right, I just found that would work. I missed that it's documtented: "A higher number means that packages of this repository will be chosen over other repositories, even if they have a greater package version." I missed that. I will try that.
