### ISSUE TITLE
rename repo2solv.sh to repo2solv

### ISSUE THREAD

**Issue by sunweaver** [openSUSE/libsolv#58]
Hi,

I am not sure what the policy in SUSE is for the below, but...

In Debian, it is "forbidden" to have files with file extensions (.sh) in /usr/bin/, /usr/sbin/, etc. For the Debian package of repo2solv I had to rename repo2solv.sh -> repo2solv.

It is ok to reject this request, but maybe it is an approach suitable for libsolv on SUSE, as well.

Greets,
Mike

**Comment by ignatenkobrain** [comment]
In Fedora we rename it too.

**Comment by Conan-Kudo** [comment]
We rename this in Mageia as well.

**Comment by Conan-Kudo** [comment]
@sunweaver You don't need the Zypp stack for building SUSE chroots with `obs-build`. It only needs `perl-BSSolv` and a sufficiently new (or patched) `rpm`.

**Comment by sunweaver** [comment]
On  Mo 02 Jul 2018 12:52:13 CEST, Neal Gompa (ニール・ゴンパ) wrote:

> @sunweaver You don't need the Zypp stack for building SUSE chroots  
> with `obs-build`. It only needs `perl-BSSolv` and a sufficiently new  
> (or patched) `rpm`.

Yeah, I realized this a while ago after I had zypper packaged. Some  
people in Debian play with it for what-not-purpose. So I keep it  
maintained +/-.

Greets,
Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by mlschroe** [comment]
(perl-BSSolv is build service only, you do not need it at all to run obs-build.)

**Comment by mlschroe** [comment]
Now done. And it also has a manpage!
