### ISSUE TITLE
Make package RECOMMENDS a stronger dependency

### ISSUE THREAD

**Issue by kirgene** [openSUSE/libsolv#63]
Hi,
For Debian packages RECOMMENDS is a strong dependency (but not absolute - https://www.debian.org/doc/debian-policy/ch-relationships.html).
They should be treated as DEPENDS, unless some (new) flag is set that makes libsolv ignores these dependencies (NO_RECOMMENDS maybe).

**Comment by mlschroe** [comment]
But isn't that already what libsolv does? It tries to install all recommended packages, unless it's not possible. And there's already a flag to turn this off (SOLVER_FLAG_IGNORE_RECOMMENDED).

**Comment by kirgene** [comment]
Actually it doesn't.
The following test fails:
```
repo system 0 testtags <inline>
#>=Pkg: A 1 0 all
#>=Pkg: C 1 0 all
#>=Pkg: Z 1 0 all
#>=Rec: A = 1-0
#>=Rec: C = 1-0
repo test 0 testtags <inline>
#>=Pkg: A 2 0 all
#>=Pkg: B 1 1 all
#>=Pkg: C 2 0 all
#>=Pkg: Z 2 0 all
#>=Rec: A = 2-0
#>=Rec: B = 1-1
#>=Rec: C = 2-0
system i686 deb system

job install name Z [orupdate]
result transaction,problems <inline>
#>install B-1-1.all@test
#>upgrade A-1-0.all@system A-2-0.all@test
#>upgrade C-1-0.all@system C-2-0.all@test
#>upgrade Z-1-0.all@system Z-2-0.all@test
```

with the result:
```
Results differ:
-upgrade A-1-0.all@system A-2-0.all@test
-upgrade C-1-0.all@system C-2-0.all@test
```

**Comment by mlschroe** [comment]
Yes, that's true. It solves your example that way because it currently has a focus on doing minimal changes to your system, and thus it prefers not updating A and C and breaking the recommends dependency over the update. Is this some real issue that needs fixing?

**Comment by mlschroe** [comment]
I can add a solver flag that makes it add weak rules for the recommends, this will make the solver try hard to fulfill all recommends.

**Comment by kirgene** [comment]
Good idea.

**Comment by adelcast** [comment]
The libsolv backend of opkg has the same problem, it's a regression from when the internal solver is used. A flag that will allow opkg to keep the same behavior across backends would be fantastic!

https://bugzilla.yoctoproject.org/show_bug.cgi?id=9939

**Comment by mlschroe** [comment]
Now done: the SOLVER_FLAG_STRONG_RECOMMENDS makes the solver create rules for recommends dependencies. Pretty much untested, though...

**Comment by adelcast** [comment]
While testing SOLVER_FLAG_STRONG_RECOMMENDS, I found a potential issue.  In a repo that has the following (pseudo code form opkg ATS):

o.add(Package="x")
o.add(Package="a", Recommends="b")
o.add(Package="b", Recommends="c")
o.add(Package="c", Conflicts="x")

And package 'x' is installed, when an 'install a' operation is run, only 'a' is installed. Seems to me like a better solution would be to install 'a' AND 'b', which is what you get without SOLVER_FLAG_STRONG_RECOMMENDS. Would it make sense to have SOLVER_FLAG_STRONG_RECOMMENDS follow that behavior? I can open an issue, if you think this suggestion makes sense.

**Comment by adelcast** [comment]
@mlschroe
