### ISSUE TITLE
Removing auto-installed orphaned packages

### ISSUE THREAD

**Issue by kirgene** [openSUSE/libsolv#70]
How to achieve removing auto-installed orphaned DEBIAN packages? Seems there is no mechanism for it in libsolv.
I can create a patch to store auto-installed property of STATUS file in solvable, but I don't know what to do with it next.

**Comment by mlschroe** [comment]
Well, as libsolv is coming from a rpm system, and rpm does not store the auto-installed/user-installed flag in its database, the information is currently passed with the standard job mechanism.

This means that you're supposed to add "SOLVER_USERINSTALLED" jobs for every package that does not have the auto-installed property set.

**Comment by kirgene** [comment]
OK, maybe you could point me the way of how to implement this task with setting some new property (like SOLVABLE_USERINSTALLED) in solvable since I'm not very familiar with the code of libsolv.

**Comment by mlschroe** [comment]
Seems like apt stores the autoinstalled package information in /var/lib/apt/extended_states. I've added a little helper function to libsolv to parse this file, so you can do something like (untested):
```
Queue autoinstalledq;

/* after reading the repos and the pool_createwhatprovides call */
queue_init(&autoinstalledq);
if ((fp = fopen("/var/lib/apt/extended_states", "r")) != 0)\
  {
    pool_deb_get_autoinstalled(pool, fp, &autoinstalledq);
    fclose(fp);
  }

/* after constructing the job */
pool_add_userinstalled_jobs(pool, &autoinstalledq, &jobq, GET_USERINSTALLED_INVERTED);
```

**Comment by ignatenkobrain** [comment]
Seems to be fixed.
