### ISSUE TITLE
Mark solvables as "not installed" in installed repo

### ISSUE THREAD

**Issue by kirgene** [openSUSE/libsolv#74]
In DEBIAN status file there might be packages that are half-installed (already unpacked but not yet configured). So after parsing status file and populating its content into installed repo, half-installed packages need to be marked as "not installed" since they have to be present in install transaction (if some package depends on them) for configuration.

**Comment by ignatenkobrain** [comment]
Hmmm, can it be added not to "installed" repo and then just copied into installed one once it is done?

Anyhow, this issue seem to be 3.5 years old, so I'm going to close it. If you think it's still an issue, feel free to reopen.
