### ISSUE TITLE
GLib dependency?

### ISSUE THREAD

**Issue by cgwalters** [openSUSE/libsolv#78]
We're discussing adding a GLib dependency for hawkey (a libsolv wrapper).  Currently librepo already depends on GLib, and higher level libraries such as https://github.com/hughsie/libhif (which is itself consumed by PackageKit and https://github.com/projectatomic/rpm-ostree ) all use GLib.

There are quite a number of cleanups that could occur with a GLib dependency:
 - the MD5, SHA1, and SHA2 copies
 - `solv_validutf8` -> `g_utf8_validate`
 - `Queue` is just `GQueue` with `int` as a data value

etc.  Would you consider a patch for this?

**Comment by mlschroe** [comment]
Nope, sorry, no dependency on glib for libsolv, please. Queue is one of the fundamental objects in libsolv, I don't want to depend on some other lib for it. solv_validutf8 is pretty small.

I can add a config options to disable the hash implementations (although they are also pretty small),

**Comment by cgwalters** [comment]
I only noticed after filing this that libsolv is BSD licensed, which puts it in a different grouping than GLib's LGPLv2+ world.  Is there any libsolv consumer that's purely BSD?  librpm is LGPLv2+, and dpkg is GPLv2+.

For any project that's not one of the BSDs or Android, LGPLv2+ is usually fine, but it is something to note.

Anyways, we can close this I guess. Just reading the code though, there is soooo much "C utility library" duplication.

Maybe something like an optional build-time dependency on GLib 2 where we can use those implementations of the crypto primitives, and I can be satisfied there?
