### ISSUE TITLE
Internal ids in repo_lookup_idarray

### ISSUE THREAD

**Issue by mluscon** [openSUSE/libsolv#79]
Hello,

I am wondering whether the functions repo_lookup_idarray or lookup_idarray_solvable(repo.c) should not filter libsolv internal ids e. g. for SOLVABLE_REQUIRES I get ids: 15(solvable:prereqmarker), -2147483646(rpmlib(PayloadFilesHavePrefix)), ... . Is there any preferred way how to filter out those ids to obtain only "real" dependencies?

**Comment by jsilhan** [comment]
Hi Michael,
to give you the context, repoquery and plugins extras (https://github.com/rpm-software-management/dnf-plugins-extras/blob/master/plugins/debug.py#L334 , https://github.com/rpm-software-management/dnf-plugins-extras/blob/master/plugins/leaves.py#L56 , https://github.com/rpm-software-management/dnf-plugins-extras/blob/master/plugins/repoclosure.py#L92 and https://github.com/rpm-software-management/dnf-plugins-extras/blob/master/plugins/repograph.py#L113 prints these delimiters. We don't know how lookup_idarray_solvable should work. Please let us know whether it's a libsolv bug or not so we can fix it in hawkey. Thanks.

**Comment by mlschroe** [comment]
It's not a libsolv bug, lookup_idarray is the raw interface. The question is if repo_lookup_deparray should filter the marker if the marker argument is set to zero.
(As for rpmlib(PayloadFilesHavePrefix), that's a true dependency, why should it be filtered?)

**Comment by jsilhan** [comment]
> The question is if repo_lookup_deparray should filter the marker if the marker argument is set to zero.

feel free to close this issue if no other component like zypper don't expect it to be there. We will do that in hawkey then.

> (As for rpmlib(PayloadFilesHavePrefix), that's a true dependency, why should it be filtered?)

That's the same behavior as yum repoquery has. Createrepo filter them out and so we filter them from the installed ones too. That's what users request. We don't want `rpmlib(*` deps to be suppressed from libsolv or hawkey though.

**Comment by mlschroe** [comment]
Regarding rpmlib() deps: Looks like you want to use RPM_ADD_NO_RPMLIBREQS for your repo_add_rpmdb and repo_add_rpm calls?

**Comment by ignatenkobrain** [comment]
Seems like this problem has been resolved, closing.
