### ISSUE TITLE
erase all deps flag

### ISSUE THREAD

**Issue by jsilhan** [openSUSE/libsolv#80]
Hi, is in libsolv any solver flag that would allow to delete whole dependency tree of package marked for removal instead of installing new packages to satisfy broken deps? E.g.:
```
repo system 0 testtags <inline>
#>=Pkg: elinks 1 1 x86_64
#>=Prv: browser
#>=Pkg: xmlto 1 1 x86_64
#>=Req: browser
repo available 0 testtags <inline>
#>=Pkg: links 1 1 x86_64
#>=Prv: browser
system x86_64 rpm system
job erase name elinks
result transaction,problems <inline>
#>erase elinks-1-1.x86_64@system
#>erase xmlto-1-1.x86_64@system
```
I just wondering whether zypper supports that as it's common use case of yum users. If there's no such flag I can find all requires recursively and add them to erase job - I want to find the cleanest solution to solve that.

**Comment by mlschroe** [comment]
There's no such solver flag, you would simply only add the "System" repo and no other repo to do that.

**Comment by jsilhan** [comment]
Thanks

**Comment by jsilhan** [comment]
Actually, it prints errors.
```
problem 0f9b3e50 info package xmlto-1-1.x86_64 requires browser, but none of the providers can be installed
problem 0f9b3e50 solution 61335167 deljob erase name elinks
problem 0f9b3e50 solution 84360740 erase xmlto-1-1.x86_64@system
```
but I will find them all manually.

**Comment by mlschroe** [comment]
That's because you didn't set "allowuninstall". dnf does that for the "erase" operation.

**Comment by jsilhan** [comment]
It works, thanks again
