### ISSUE TITLE
ABI break in libsolv 0.6.x compared to 0.1.x without soversion bump

### ISSUE THREAD

**Issue by thp** [openSUSE/libsolv#85]
We've been using libsolv 0.1.x and libzypp 12.16.x for some time in Mer. When upgrading to libzypp 14.35.0, we also upgraded libsolv to 0.6.8, but as libsolv 0.6.8 still has the same soversion as 0.1.x, in some cases the new libzypp (14.35.0) was installed with the old libzypp (0.1.x), which caused symbol lookup error.

We worked around this with two relationships:

https://git.merproject.org/mer-core/libzypp/blob/master/rpm/libzypp.spec#L21
`Requires:       libsolv0 >= 0.6.8`

https://git.merproject.org/mer-core/libsolv/blob/master/rpm/libsolv.spec#L69
`Conflicts:  libzypp < 14.35.0`

However, I guess in this case, the soversion of libsolv should have been bumped? Then again, the 0.x version might suggest that there's no ABI compatibility guarantee for libsolv yet(?).

**Comment by mlschroe** [comment]
Yeah, my plan was to postpone the soversion bump until the 1.0 release. However, as the Fedora guys nowadays also use libsolv for dependency solving, I'll probably need to do this sooner ;)
