### ISSUE TITLE
provide solver_describe_weakdep_decision via bindings

### ISSUE THREAD

**Issue by lnussel** [openSUSE/libsolv#91]
solver_describe_weakdep_decision is missing in solv.i so no binding generated for that

**Comment by lnussel** [comment]
Something like this is minimal but really hard to use:

  Queue describe_weakdep_decision(XSolvable *s) {
    Queue q;
    queue_init(&q);
    solver_describe_weakdep_decision($self, s->id, &q); 
    return q;
  }

I don't know what to do with the 3rd parameter in the triplet of the queue:

                        my @q = $solver->describe_weakdep_decision($s);
                        while(my ($why, $p1, $p2) = splice(@q, 0, 3)) {
                                my $s1 = solv::XSolvable->new($pool, $p1);
                                dd $s->{name}, $reason_by_id{$why}, $s1->{name}, $s1->lookup_idarray($p2);
                        }

**Comment by lnussel** [comment]
any change to get this? It's really useful for the minimal pattern and JeOS development

**Comment by mlschroe** [comment]
I added the method with commit fc03bb62917dfd599503a47d9c9fde9ff371706e.

The 3rd parameter is the dependency.
