### ISSUE TITLE
file conflicts multilib

### ISSUE THREAD

**Issue by damianatorrpm** [openSUSE/libsolv#94]
Hello all,

As a fun test I compiled libzypp+zypper for Fedora 22
https://build.opensuse.org/project/show/home:damianator:fedora:zypper

On a vanilla Fedora 22 install I installed libzypp+zypper and did
zypper remove yum* dnf*

On Fedora the 32-bit lib packages are the 'normal' i686 packages of
the lib copied to the x86-64 repos.

So when you install a lib like alsa-lib.i686 it contains the same
files (the .so files reside in their respective /usr/lib or /usr/lib64
folders) the x86-64 version does.

For non binary files (which on both architectures are the same) no
conflict is there.

But alsa-lib (and other packages) contains also binaries like
'aserver' which differs for both architectures and zypper warns about
a file conflict and if I continue the
/usr/bin/aserver file from the x86-64 will be replaced with the one
from the i686 package, zypper says.

I was wondering why zypper warns about that and yum/dnf doesn't and
just installs the alsa-lib package.
Turns out even with zypper the file won't be replaced with the one
from the i686 package!
Explanation here:
https://lists.fedoraproject.org/pipermail/devel/2010-January/129725.html

When installed in parallel, multilib RPM packages may contain files that
live in common paths. When this happens, RPM uses the following algorithm:

- If the file in both packages is identical, installation is allowed
  and the file is written
- If the file in both packages is an ELF binary, the file used is the
  file in the package for the primary architecture
- If the file in both packages is not an ELF binary a RPM conflict is
  raised

So my suggestion here would be zypper also not to warn about a file conflict
if you're installing a package for a secondary architecture that
contains an elf file that conflicts with an elf file for your primary
architecture.
RPM heuristics will anyway not overwrite the elf file for you primary
architecture,
so zypper warning about that happening makes no sense (as it won't happen).

After discussion on libzypp-devel mailing list, we agreed that I open bug report @libsolv
http://lists.opensuse.org/zypp-devel/2015-07/msg00001.html

libsolv is installed from fedora repo http://fedora.c3sl.ufpr.br/linux/updates/22/SRPMS/l/libsolv-0.6.11-1.fc22.src.rpm

**Comment by mlschroe** [comment]
Turned out that it was libsolv checking the wrong flag. Sorry that this took so long.

**Comment by damianatorrpm** [comment]
Thanks @mlschroe
