### ISSUE TITLE
SOLVER_FLAG_NO_INFARCHCHECK not working as expected

### ISSUE THREAD

**Issue by EricAustinYu** [openSUSE/libsolv#98]
The documentation states:
> *SOLVER_FLAG_NO_INFARCHCHECK*::
> Turn off the inferior architecture checking that is normally done
> by the solver. Normally, the solver allows only the installation
> of packages from the "best" architecture if a package is available
> for multiple architectures.

Suppose pool_setarch() is called with "x86_64" and there are two packages available for installation:
A 1-0 with architecture x86_64
A 2-0 with architecture i686

Without SOLVER_FLAG_NO_INFARCHCHECK set, solving with a job to install A results in a transaction saying to install A 1-0 as expected since x86_64 is the best architecture. 
However, with SOLVER_FLAG_NO_INFARCHCHECK set for the solver and a job to install A, I expected the inferior architecture checking to be turned off and A 2-0 to be installed because it has the better version. Instead, A 1-0 is installed. To be sure that it was possible to install A 2-0, I also tried giving a job to explicitly install a A 2-0 which worked.

Is there something that I'm missing or misunderstanding?

Here is the previous example as a test case (which will fail on the last line since A-1-0.x86_64 is chosen to be installed instead):
```
repo system 0 testtags <inline>
repo test 0 testtags <inline>
#>=Pkg: A 1 0 x86_64
#>=Pkg: A 2 0 i686
system x86_64 rpm system

job install name A
result transaction,problems <inline>
#>install A-1-0.x86_64@test

nextjob
job install name A = 2
result transaction,problems <inline>
#>install A-2-0.i686@test

nextjob
solverflags noinfarchcheck
job install name A
result transaction,problems <inline>
#>install A-2-0.i686@test
```

**Comment by mlschroe** [comment]
This is a bit tricky. The solver works with two mechanisms, there are rules that define what  solutions are allowed, and there are policies that define what to choose if there are multiple candidates.

The "infarchcheck" is from the rule class, it makes sure that a i686 package is not chosen if there's a x86_64 version. But there's also a policy to prefer x86_64 packages over i686 packages.
So even if you disable the infarchcheck, it solver will still prefer x86_64 packages.

You can set the architecture policy with pool_setarchpolicy(). (The pool_setarch() function just translates the specified architecture to a policy and calls pool_setarchpolicy(), see poolarch.c.)

The "x86_64" from the testcase gets translated to "x86_64:athlon:i686:i586:i486:i386", where the ':' means "is better than". An equivalence can be specified with "=", i.e.
"x86_64=athlon=i686=i586=i486=i386" would make x86_64 equal to i686, leading to A 2-0 being chosen.

The testcase line would be:
```
system :x86_64=athlon=i686=i586=i486=i386 rpm system
```
