### ISSUE TITLE
CMake detects Python3 = 3.4.3+ and fails

### ISSUE THREAD

**Issue by thopiekar** [openSUSE/libsolv#99]
I use Ubuntu wily and found this problem. It is currently under heavy development and unreleased - However, I would love to see the CMake script more failsave for cases where a "+" appears in the version string. (At least I beleave this is the problem here.)

```
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.4m.so (found version "3.4.3+") 
CMake Error at bindings/python/CMakeLists.txt:4 (FIND_PACKAGE):
  find_package called with invalid argument "3.4.3+"


-- Python executable: 
-- Python installation dir: 
CMake Error at bindings/python/CMakeLists.txt:31 (INSTALL):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "bindings_python".


CMake Error at bindings/python/CMakeLists.txt:32 (INSTALL):
  install FILES given no DESTINATION!

```

**Comment by thopiekar** [comment]
Just found an own fix for this problem. Details and patch can be found at:
http://bazaar.launchpad.net/~thopiekar/zypper/libsolv-packaging/view/head:/patches/fix_python_detection

**Comment by ignatenkobrain** [comment]
Is this still relevant?

**Comment by thopiekar** [comment]
I have no idea. But I think it is that old, that it has been fixed already.

**Comment by ignatenkobrain** [comment]
Perfect, thanks!
